### ISSUE TITLE
OreSpawn Weapons?

### ISSUE THREAD

**Issue by Spudddy** [RiskyKen/Armourers-Workshop#104]
I added in every Sword and Bow from **OreSpawn** into the .config (by hand) but they did not seem to work, do you think you could add them into the default .config as there are many and its a fun mod to be able to customize.

### **[.config after i added OreSpawn.txt](https://github.com/RiskyKen/Armourers-Workshop/files/202318/default.config.after.i.added.OreSpawn.txt)**

did i do something wrong?

**Comment by RiskyKen** [comment]
When the game is loading do you get any errors in the log like "Invalid sword override in config file" or "Unable to override item renderer for" you may need to turn on showing the log on whatever launcher you are using.
