### ISSUE TITLE
Bug - Player's Model Render Error

### ISSUE THREAD

**Issue by kociara81** [RiskyKen/Armourers-Workshop#107]
I was with my friend lots of fun with your mod on our private server and we use our private modpack that combines the element of what they used to in the past most loved modpack (if it is necessary, 
I can give you a list of used mods). And most of the time everything worked without problems. Our server world already exist for three months and bug suddenly appeared today. I created a new world, and the problem still exist.

(Sorry for my English. It isn't my native language)

Description of the bug:
Well, the player's model lacks the legs, head,and arms are messed up and player's skin is total chaos. Here are screenshots of this bug:

http://oi64.tinypic.com/33vj2x0.jpg
http://oi66.tinypic.com/rh7rqx.jpg

I did various steps to eliminate most common problems.

Hardware:
At first, I thought this happens, because I have a poor graphics card on my laptop. But my friend with totally different (and much better) graphic card has the same problem too. My graphics card is AMD Radeon HD 6320 with 4022 MB VRAM and my friend's is GeForce GTX 550Ti with 1 GB VRAM. This may give a clue that the problem didn't lies on the hardware site.

Mods:
I activated in this mod's config file option of an alternative rendering. My friend too. Nothing happens. 

We using Liteloader mods (because we love their map and chat mod) and It isn't the cause of the problem (after removal nothing changes. And we used Liteloader for a long time with this mod, without any problems). 

I checked whether Fastcraft caused the problem (after update what had improved compatibility with other mods, nothing changes. And return to the version that worked before, done nothing too).

I checked Optifine which had in its history, the magnitude of this type of problems. We launched the game with it and without it. I turned on and turned off the most troublesome options. Nothing has changed.

I checked, other mods which modify the player's rendering on our modpack and nothing. I really don't know what causing this bug.

**Comment by RiskyKen** [comment]
First of can you make sure you are using the newest version of the mod, you can download it here: http://minecraft.curseforge.com/projects/armourers-workshop/files

Can you also send me a list of the other mods you are using. Just do a debug crash to get the list (Hold F3 + C for about 10 seconds)

You said you changed some config options what ones? Try setting both "useAttachedModelRender" and "skinTextureRenderOverride" to true. If they don't do anything just set them back to false.

If you are using a resource pack try turning it off to see if that helps.

**Comment by kociara81** [comment]
This problem exist on the latest version of which is available to the public (1.7.10-0.38.1.98 from December 12, 2015). 

When it comes to setting "useAttachedModelRender" and "skinTextureRenderOverride" to true, no it didn't help (Yes, I had changed those configs, when bug appeared. And so I read a description of these options. Therefore I activated it at the beginning to see if this will fix the bug). 

Disabling resource pack didn't help (We use Faithful 32 texture pack and We don't use HD player's skins). 

Debug crashlog: http://pastebin.com/GsBCWe2P

**Comment by kociara81** [comment]
I found the cause of this bug. Now, after a more detailed check I found a mod that can cause this conflict. It's Et Futurum. After removing it from the game everything is back to normal. I found it using the route of elimination 

Give you have any logs if necessary? Maybe a full forge's log when the game starts and runs some old and new save with those mods?

**Comment by RiskyKen** [comment]
Ah am guessing it adds the new player rendering with the extra skin layer. If it has an option to turn that off it may be possible to use it with AW.

I will have a look into supporting it but am not sure if I can. :|

**Comment by RiskyKen** [comment]
Settings "Skin overlays" to false in the Et Futurum config seems to fix it. Will look into it and try and add support but it's not likely. (
