### ISSUE TITLE
Should Add MapleCrafted Compatibility

### ISSUE THREAD

**Issue by JayGhoul** [RiskyKen/Armourers-Workshop#108]
Heyo! You should add MapleCrafted Compatability! Just a though <3 Thank you :D Have a great day! ✌️
http://minecraft.curseforge.com/projects/maplecrafted?gameCategorySlug=mc-mods&projectID=240555

**Comment by RiskyKen** [comment]
Added in 5e899ff9842e4fc2aaa5b6b7cbff125efcf3e8bb
