### ISSUE TITLE
Draconic Evolution Compatibility

### ISSUE THREAD

**Issue by bhuvan21** [RiskyKen/Armourers-Workshop#111]
Sorry if this is stupid, but I believe that armourer's workshop and draconic evolution do not work together. The drac. evolution items cannot be reskinned in a skinning table (they show the correct text but don't display that way) as well as this, the armour rendering for them cannot be turned of via the equipment wardrobe (the box ticks but nothing happens)

Again, sorry if I'm missing something obvious.
Thanks in advance!

**Comment by Alexismachina** [comment]
This is not risky's fault. it's @brandon3055 and its been already adressed in an issue with Draconic Evolution.

**Comment by brandon3055** [comment]
I believe this is directly related to DE's custom rendered but i dont know if there is actually any simple way for me to fix this from my end. I know it is still possible to prevent my armor from rendering because another mod that dose something similar dose it. @RiskyKen How exactly do you prevent armor from rendering?

**Comment by RiskyKen** [comment]
@brandon3055  Weapon rendering is most likely my fault and should be fix in the next build. I cancel the RenderPlayerEvent.SetArmorModel event to stop armour rendering on the player. I will need to have a look at how your armour render and see what I can do.

**Comment by brandon3055** [comment]
@RiskyKen Oh i think i may have actually found the problem...
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/client/handler/ClientEventHandler.java#L163-L176
Im bot checking if the event has been canceled... Do you have your listener set to a higher priority so it will be fired first?

**Comment by RiskyKen** [comment]
I don't but I will add that. Curious how other mods are stopping the armour render, can you remember the name of the other mod that stops the render?

Jelly of your much cleaner code.
https://github.com/RiskyKen/Armourers-Workshop/blob/master/src/main/java/riskyken/armourersWorkshop/client/handler/EquipmentWardrobeHandler.java#L102-L135

**Comment by brandon3055** [comment]
It may have been this one
http://minecraft.curseforge.com/projects/cosmetic-armor-reworked
