### ISSUE TITLE
skin bug

### ISSUE THREAD

**Issue by TheChronomancer** [RiskyKen/Armourers-Workshop#112]
when i used the dev build posted on #110 my skin ended uplooking al pink and black
my mods list
![image](https://cloud.githubusercontent.com/assets/8211402/15078462/3845381e-1368-11e6-8929-cbe938d3bb96.png)

**Comment by RiskyKen** [comment]
Are you getting any errors in the console?

**Comment by RiskyKen** [comment]
Can you test without Et Futurum?

**Comment by RiskyKen** [comment]
Try setting "Skin overlays" to false in the Et Futurum config.

**Comment by TheChronomancer** [comment]
i just got rid of et futurum  and everything worked fine

**Comment by RiskyKen** [comment]
Duplicate of https://github.com/RiskyKen/Armourers-Workshop/issues/107
