### ISSUE TITLE
1.9 port megathread

### ISSUE THREAD

**Issue by asiekierka** [RiskyKen/Armourers-Workshop#115]
Could you let me know when the codebase will be stable enough to start looking into a 1.9 port (for BTM)?

**Comment by RiskyKen** [comment]
I plan to start porting mid June, that should give me time to have it working for BTM.

https://twitter.com/RiskyKen/status/730702142261108736

**Comment by 4rz0** [comment]
And one month to go until BTM :D

**Comment by alekso56** [comment]
Sad that it didn't make it for the second btm :<

**Comment by 4rz0** [comment]
Surprise :D

**Comment by RiskyKen** [comment]
The 1.11 master race cares not for this issue!
