### ISSUE TITLE
a little bug with 0.39.0 per3

### ISSUE THREAD

**Issue by EthanJJC** [RiskyKen/Armourers-Workshop#116]
the sword‘s size is wrong, too small

and  suggestions were that
1:add a commands to other slots (now only have the first row)
2:may the equipment bar is six row?(when the equipment apply a skin,can let it superimposed not replace all)

**Comment by RiskyKen** [comment]
Sword should be scaled when in inventory slots, it should be the normal size when holding it.

1: Commands to other slots? Are you talking about adding more than 1 sword and bow slot?
2: I am not sure what you are asking :S

**Comment by EthanJJC** [comment]
the sword armour be equiped is small,not in inventory slots
Commands to the add slots---the second skin slots and the third skin slots and more（I wanna ,made player's setSkinColumnCount to 1, and use the commands to control them，may add an admin GUI like ess's invsee :)  ）

**Comment by RiskyKen** [comment]
So you know about the "/armourers setSkinColumnCount <PlayerName> <Value>" command?

Are you saying you want something like "/armourers addSkinColumn <PlayerName>" ?????

I was planning to make an item that players could find/craft and it would unlock another skin column.

**Comment by EthanJJC** [comment]
yeah
I tried the command that is useful，we plat set some misson to get medals and player can not take them out themselfs.if someone derss a skin in five row slots, then /armourers setSkinColumnCount 4, the five row slots is can not edit. both admin or player

**Comment by RiskyKen** [comment]
I think I understand what you are saying now. If you put something in column five then change the count to 4 the item is still there but you can't access it.

**Comment by EthanJJC** [comment]
( • ̀ω•́ )✧
so need a command to add or delete it

**Comment by EthanJJC** [comment]
( • ̀ω•́ )✧
so need a command to add or delete it
