### ISSUE TITLE
Armor Currently Can´t Be Equiped

### ISSUE THREAD

**Issue by KyubiHitashi** [RiskyKen/Armourers-Workshop#12]
I Dont Know Why. When I Try To Equip The Armor On My Character It Does Not Show The Armor On It. And No More Armors Show When I Equip In The Equipment Wardrobe What Can I Do To Fix This?

**Comment by RiskyKen** [comment]
What armour is not showing? Armourer's Workshop skins or vanilla armour?

What Armourer's Workshop version are you using?

**Comment by KyubiHitashi** [comment]
I Am Using The Last Version Launched. My Friend And I Was Playing Multi-player and i dont know why i was the only who has seen the armor equiped on me but sometimes the armor dosent show equiped on the character. i am equiping right on the Equipment Wardrobe

**Comment by RiskyKen** [comment]
Are you playing in off-line mode?

**Comment by KyubiHitashi** [comment]
Nop. I Am Playing On Online Mod I Have Original Minecraft Account

**Comment by RiskyKen** [comment]
What other mods do you have installed?

**Comment by KyubiHitashi** [comment]
Just Better Storage Mod

**Comment by KyubiHitashi** [comment]
Maybe In The Next Update You Can May Fix This Bug

**Comment by karorogunso** [comment]
Yep I got this too.
In Single Player is Fine
Proof : http://puu.sh/eGUnd/e2db9a8f22.png

But in Multiplayer is Gone but still can make any custom
I test on Cauldron server (bukkit + forge) 
 - MinecraftForge v10.13.2.1236 
 - minecraft server version 1.7.10
Proof : http://puu.sh/eGV2b/e503743c17.png

But If you Equip any Custom Armor in Single player and 
Go to Multiplayer you going to see any Custom Armor in Singleplayer
but multiplayer still ... Nope.avi like this
Proof : http://puu.sh/eGVpD/a770ba06e2.png

Here it's FYI for you <3 keep do a good works <3
:tea: time 
KimoiEngineGuy

**Comment by RiskyKen** [comment]
Is the server in off-line mode?

**Comment by karorogunso** [comment]
yep it's offline mode
let me try online mode for a sec thanks :D

**Comment by karorogunso** [comment]
Server in Offline mode cant Using Custom armor right and...
That bug i said about if you play in server offline mode you'll get this bug.

but it's okay :D thanks for you infomation about server off-line mode :D
:tea: phew~

**Comment by F-G-Elf** [comment]
I am also struggling with an issue like this. I have the latest version of this mod installed plus Rei's Minimap, Better Storage mod and Not Enough Items mod. The difference is that I am playing in a singleplayer world. I made a helmet and it shows up on the mannequin, but not on me neither in F5 mode nor the armor inventory. Any suggestions?

**Comment by RiskyKen** [comment]
Off-line mode sync fix in https://github.com/RiskyKen/Armourers-Workshop/commit/396133a9d844749020b190542112baa75f86ffc9 Will be in the next build.
