### ISSUE TITLE
Rendering Bug with Tress

### ISSUE THREAD

**Issue by chiligreen21** [RiskyKen/Armourers-Workshop#122]
The Mod makes the Trees very strange

Trees with Mod: [](http://imgur.com/yQJn0es)

I tested it after takeing the mod out it was fine so
how do i solve this problem??

**Comment by chiligreen21** [comment]
http://imgur.com/yQJn0es

**Comment by RiskyKen** [comment]
What am I looking at? A before and after screenshot would help.

**Comment by chiligreen21** [comment]
1. Thats the World with the Mod

2. Before: http://imgur.com/ouq4A4E
    After: http://imgur.com/7SfPKB6

**Comment by RiskyKen** [comment]
Looks like mipmaps are turned off. What version of the mod are you using?

**Comment by chiligreen21** [comment]
1.2.4

**Comment by chiligreen21** [comment]
Ohh sry looking at the false Mod XD

0.39.3

**Comment by RiskyKen** [comment]
So is this an issue with Armourer's Workshop?

**Comment by chiligreen21** [comment]
Yes it is

**Comment by chiligreen21** [comment]
Its only this mod not with anything else

**Comment by RiskyKen** [comment]
Can you post your startup log
