### ISSUE TITLE
Stuck at downloading skin 

### ISSUE THREAD

**Issue by Danielv123** [RiskyKen/Armourers-Workshop#124]
Armourers version 0.39.3

 After dying and reloading the server, my hat turned white and says "downloading skin". It never finishes. The server is hosted via the lan option in the single player menu.

Using -X-magica modpack.

The skin can still be placed in the armourers block and be loaded into the world for editing.

**Comment by RiskyKen** [comment]
Not really tested LAN play much. Have you tried restarting both the client and the server? Also can the person playing on the server computer see the skin?

**Comment by Danielv123** [comment]
I have tried restarting both client and server, did not have any effect. I am playing on the server, and it still says downloading skin. I fixed it by placing it in the armourers block, loading it and saving it onto a new template. Neither client nor server was able to see the skin.

**Comment by BLSK** [comment]
The skins are still doing this in Armourer 41.0 - Forge 1614

I think its a loading issue.  I did a lot of time testing out the same bug and here are my finding:
1) Restarting Client(maybe server haven't gotten there just yet) causes the skins to detach:
2) CustomNPCs showed it to me the most and I think it was a major culprit
3) Creating new worlds prior to restarts carried over the skins properly and I figure cause of 'Caching' in Configs?
4) Opening up Creative Library PRIOR to spawning a CustomNPC allowed the skins to load fine(first picture below is representive of this for some reason?)

I think Armourers Mod isn't loading early enough.  It should load in the skins sooner if it can be done.  My NPCs keep getting deskinned and my costumes seem to get deskinned.

I intend to try doing this on a server but haven't just yet. but here is what one of my npcs during my testing was suppose to look like:
![2016-10-10_05 06 59](https://cloud.githubusercontent.com/assets/8443396/19231365/a73e0556-8ea7-11e6-8717-ffdb8b23e658.png)


This is what I saw when I noticed something was wrong:
![2016-10-10_03 40 31](https://cloud.githubusercontent.com/assets/8443396/19231374/b9e025e0-8ea7-11e6-84ac-b3554f35dfe5.png)


Also here is the same npc after a client restart:
![2016-10-10_03 41 02](https://cloud.githubusercontent.com/assets/8443396/19231416/e3459c9e-8ea7-11e6-8851-b4d17787c442.png)


These items won't load very fast at all:
![2016-10-10_04 30 30](https://cloud.githubusercontent.com/assets/8443396/19231441/fde43d58-8ea7-11e6-93c2-51efe6a1fae8.png)

Some won't ever load for some reason?:
![2016-10-10_04 31 29](https://cloud.githubusercontent.com/assets/8443396/19231464/293a3d86-8ea8-11e6-9c64-4620f9864fc8.png)

And after restarts this is the kind of items I keep having presented:
![2016-10-10_04 03 50](https://cloud.githubusercontent.com/assets/8443396/19231487/457f8e60-8ea8-11e6-833e-302892f3cf4b.png)

**Comment by Danielv123** [comment]
The only fix I have found is placing them into the world and creating a new skin from it.

**Comment by BLSK** [comment]
It doesn't seem you have to.  As I said I am still doing some research as to hopefully figure out if it can be fixed without an updated mod

**Comment by RiskyKen** [comment]
After you have seen a skin do this please check your server logs for

"Equipment id:<id> was requested by <playername> but was not found.
or
"Failed to load skin id:<id> from disk."

It sounds like the skin cache on the server has become corrupted. Have you been copying skins from one world to another using an external tool?

**Comment by RiskyKen** [comment]
@BLSK are you playing on LAN?

**Comment by BLSK** [comment]
Not technically LAN... but Running off Curse Client right now... not 100% sure what relation Lan is to Clients but I don't activate the lan connections

**Comment by RiskyKen** [comment]
So you are just playing single player?

**Comment by BLSK** [comment]
Yes

**Comment by BLSK** [comment]
Trying to figure it out before I fully bring up my server as its a major breaking things :(

**Comment by BLSK** [comment]
Found a Equipment ID not found :)
http://pastebin.com/apt72KZv

5:54:34 was an occurance

**Comment by BLSK** [comment]
Ok to answer your other question:
some my skins are actually like 7 months old(or somewhere around there)
I added them to my Armourers as I didn't wanna loose the progress.
Um... adding them to my Server I haven't just yet checked if I have the same issue...
But um... some of my skins were made in 38.1
The Ender Queen and Allisa were made in 41.0(I am 80% sure... got kinda sidetracked when I noticed and issue so yeah...
Using CustomNPCs 21feb16

Not sure if any thing else...

**Comment by RiskyKen** [comment]
So how did you move the skins from the old world? Just copying the files in the library? Did the NPCs get moved from the old world?

**Comment by BLSK** [comment]
Clones but as long as I open the creative library before spawning them the skins all load in even if slow in early world generation time(pc has alot of stuff going on with the pack)

I am testing NEI LOADs now as I wonder if its just the skins don't get loaded in early enough... almost think it might be that the world didn't access the library of costumes prior to the opening of the library(however that may work)

**Comment by RiskyKen** [comment]
Clones????

**Comment by RiskyKen** [comment]
Sorry I don't know much about custom npcs

Has it got a system that lets you save NPCs onto the disk then load them into another world?

**Comment by BLSK** [comment]
CustomNPC cloning mechanic:  You save it in your Client customnpc folder and I think Daniel is using the exact same thing as me but the clones already exist so they aren't clones I have had worlds were I put down an NPC change when I restart client.  I think the Library didn't load in before the player hit the world

**Comment by BLSK** [comment]
Trying to think how to explain give me a second trying out NEI

**Comment by RiskyKen** [comment]
OK I think this is the issue. You need to get the skin database from the old world that you made the NPCs in.

If you still have the old world go into the world folder and copy all the files in skin-database into the skin-database folder in your new world. After a game restart everything should be working.

If you don't have your old world folder you will need to remake the NPCs.

Please let me know if this fixes it.

**Comment by BLSK** [comment]
Ok here is the tricky part of what I meant for you... let me try to explain all my testing:
I make and NPC: Fine: Added Costume
I restart into a new world and spawned an NPC:  Buggy armor

I make and NPC: Fine: Added Costume
I restart into the same world and the NPC has:  Buggy armor

I make and NPC: Fine: add Costume:
Restart Open new world:  Open CLibrary: Spawn NPC:  Fine

I Open CLibrary: Spawn myself armor: Saved the inventory
I open a new world: Load Inventory:  Buggy armor


Give me another fewish minutes... it takes time to restart my client

**Comment by BLSK** [comment]
Ok looking at a new world where I did do the NEI thing and it shows in the skin-database:  No skins at all
I don't believe the world looks at the armourersWorkshop Folder on the main folder and copy them in.

Other worlds where I already opened the Library though have lot sof skins

**Comment by BLSK** [comment]
Sorry this is taking so long for your method... just so much to load :(

**Comment by BLSK** [comment]
Ok yes I think that is the culprit:  The world doesn't identify the Skins early enough:  Now that I pasted them all it looks like it is working so might we need a preload of the library before the world spawns?  

Cause the main factor has mainly been;:  Have to Open the Library prior to spawning in the stuff.  

Things do bypass this method:  Copying the Folder over did work though

**Comment by RiskyKen** [comment]
Opening the library will not always work. You need to copy the skin-database folder over.

**Comment by BLSK** [comment]
Then can you give us the Option in the Configs to 'Specify' A skin-database to copy to new worlds?

so its like a Preinit of the world in some fashion?

**Comment by BLSK** [comment]
Another new world I just made:  DId a Database paste during the world load and like always: spawned my EnderQueen:  SHE IS FINE!  Finally points to figuring out the issue XD

**Comment by RiskyKen** [comment]
Are you making a mod pack that lets players create their own world?

You should check Info for Map & Mod Pack on the main forum post. Makers http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2309193-wip-alpha-armourers-workshop-weapon-armour-skins

If you make a folder called equipment-database inside your main mod folder (next to mods, config and other stuff) all the files in it will be copied to the skin-database folder of the new world.

**Comment by RiskyKen** [comment]
This will only work for new worlds.

**Comment by BLSK** [comment]
so let me just get this straight:
I make this folder you speak of:
Copy the database into it(not the folder itself just the files in database)
It will load those each time... wonder if this will work for NPCs just to validate as...going to check

In the long run each time I decide to make a new world and have a new database in that world I added costumes to it will need to be repasted into the equipment database older just so it doesn't mess up things elsewhere?

Might you have a equipment-database folder autospawn with the installation of the mod then:
maybe a tiny readme in it saying how to go about this?  as I spent a lot of time trying to figure all this out :(...

**Comment by BLSK** [comment]
And no I am not going to have 'new world' play for players just yet.  I have a mod I am working on to let this happen cause its the 'CORE MOST' mod the pack needs... sadly a year behind on figuring it out due to depression and frustration I gave up on my pack back then and only minorly fiddled with it in the last year... now at it hardcore again due to being reenergized XD and happy :)

**Comment by BLSK** [comment]
So far everything is working... just validating the last concern:
CustomNPC not loading armors even on a world I had already loaded the database into with CLibrary.

Its just 1 final check to validate all world npcs don't bug out

**Comment by RiskyKen** [comment]
I will most likely add a new folder with a read me that checks and copies the files each time the world loads. Will call it global-skin-database or something.

Keeping this issue open as this is not related to the LAN syncing issues.

**Comment by BLSK** [comment]
Ok wow... was just about to post a screenshot of still a failed 'prior' world with the database it needed for the CustomNPCs but for some reason this time it auto corrected itself... not sure what just happened but it started out as the ironhelm like look then popped into existence.

So everything Looks like ti is working properly.  I should be able to see this issue no more as long as I update my e-db with the s-db.  Appreciate the help.

**Comment by RiskyKen** [comment]
added global skin database in https://github.com/RiskyKen/Armourers-Workshop/commit/8c25878562022b16e0a0959743c491f8a783f62c
