### ISSUE TITLE
translate to kor

### ISSUE THREAD

**Issue by ISJump** [RiskyKen/Armourers-Workshop#126]
https://1drv.ms/u/s!Ap0mgbW5jtXOhy_MGtLtt0h1upJf 

i`v translate to korea and it will be fine to people to under stand what they mean 

it`s the new one that link on me
https://github.com/RiskyKen/Armourers-Workshop/blob/1.7.10/develop/src/main/resources/assets/armourersworkshop/lang/en_US.lang#L227-L233

it`s not 100% translate so i`v post in some other to check so it will be changed in soon

**Comment by ISJump** [comment]
sorry that the translate ver was old i did the new ver that can be used at 1.9.4 same as 1.7.10

https://1drv.ms/u/s!Ap0mgbW5jtXOhy_MGtLtt0h1upJf

**Comment by RiskyKen** [comment]
The flavour text for the soap item is very long. You can add %n to create a new line.

Added for the next update.

**Comment by ISJump** [comment]
fix the problem 
just re download https://1drv.ms/u/s!Ap0mgbW5jtXOhy-lHXfrtengz1BJ
