### ISSUE TITLE
More Player Models Skin Url Conflict

### ISSUE THREAD

**Issue by mew6666** [RiskyKen/Armourers-Workshop#130]
Armourers-Workshop-1.7.10-0.39.4.105.jar conflicts with More Player Models 1.7.10b. Unable to change skin url online with MPM. Sometimes goes invisible or stays Steve.

Tested with 70 mobs. Tested with only armours workshop and more player models.

Working build: Armourers-Workshop-1.7.10-0.38.1.98

**Comment by mew6666** [comment]
1.7.10-0.38.1.98 is the last working build. The rest conflict. I really want the items previews, but this one that works with mpm doesn't have that.

**Comment by RiskyKen** [comment]
Is the skin URL you are setting the same size as a normal player skin(64x32)?

**Comment by mew6666** [comment]
No, it's 2048x1024. (More Player Models is capable of high resolution skins. - I used imgur.com to upload to skin url) More Player Models I use is 1.7.10, so it uses 64x32 skins.

**Comment by RiskyKen** [comment]
Only 64x32 skins are supported. I will probably add a configuration option to disable skin painting.

**Comment by mew6666** [comment]
Right! I'm on 1.7.10 using 1.7.10 mods. Custom npcs can use high resolution skins. (as long as its 64x32 and not 64x64 - so I use 2048x1024 AND NOT 2048x2048)

AW 1.7.10-0.38.1.98 works, the builds after that don't work. I think I tested them all.

Is skin painting the issue, maybe its something you added in 0.39

**Comment by RiskyKen** [comment]
Yes skin painting is the issue it only supports 64x32 skins. I have added a configuration option for the next version to disable it.
