### ISSUE TITLE
[Suggestion] Gravity Hair

### ISSUE THREAD

**Issue by EnderHamner** [RiskyKen/Armourers-Workshop#131]
hey, so i thought it would be cool that hair coming off of a head would stop before it went through a player, but if it fell down like gravity it would be better. i have 3D hair that comes down the back from the head and if i look too far up it passes through me, and so this is where the idea came from. like this.
![2016-08-02_09 41 41](https://cloud.githubusercontent.com/assets/20797068/17332737/6098e406-5895-11e6-9fee-163346cddfd1.png) so it would be cool to stay with the gravity and point down all the time if it is textured as hair.

**Comment by RiskyKen** [comment]
Sadly this can't be done with the current AW code. Something like this is planned for AW2.

Nice hair!
