### ISSUE TITLE
(sugestion) Stairs

### ISSUE THREAD

**Issue by RageNTonic** [RiskyKen/Armourers-Workshop#132]
stair blocks to add that little bit of extra finish

**Comment by EnderHamner** [comment]
you can make them using normal blocks...

**Comment by EthanJJC** [comment]
stair blocks sounds good, but how to color it？

**Comment by LordPhrozen** [comment]
This is almost nonsensical, please open a more detailed ticket if you are seeking an enhancement or feature. Closing this for now.
