### ISSUE TITLE
Question: Will you update the mod to 1.8,1.9 and 1.10?

### ISSUE THREAD

**Issue by 5igm** [RiskyKen/Armourers-Workshop#133]
Hi, I am a fan of your mod. Will you update this mod to newer versions? I am looking forward to it very much.

**Comment by RiskyKen** [comment]
Yes a 1.9.4 version is being worked on, I will probably bring out a 1.10 version soon after. Skipping over 1.8.

I don't know when the 1.9.4 port will be done, very busy at the moment.
