### ISSUE TITLE
Some crazy ideas for AW

### ISSUE THREAD

**Issue by EthanJJC** [RiskyKen/Armourers-Workshop#135]
There are two ideas，leave ur opinions guys
1：Rainbow Color(color conversion)
Add a  special color table,which is allow to make choice how many frames u need,and what color is displayed for each frame,and each frame display time(include none type color),and trigger mechanism
Like flash equipment :p

2：Motion Parts(maybe it can imitate the wings)
Add a tool and a skin type.
The skin type is named part,which can choice rotary motion or pendulum motion,and trigger mechanism
The motion can option speed, angle or others.
Tool is like block marker,to mark where the part put on.
Like bamboo dragonfly,wings, straps  XD  

Look at this [one](http://49.212.65.192/forum/viewtopic.php?f=13&t=29577&sid=cd8b9f301c9d655438426db42eb80dab) ,It can be used as reference

About the trigger mechanism,there are : 
normal
flight
attack
defense
excavation
sneak

**Comment by RiskyKen** [comment]
Most of this is planned for AW2. Rainbow paint was scrapped because of performance issues.
