### ISSUE TITLE
Project doesn't show up

### ISSUE THREAD

**Issue by KatyPlayz** [RiskyKen/Armourers-Workshop#136]
ok, so

every time i create a project for the player head, torso, arms, etc. it doesn't show up once i put it on. i put it on using the 'P' key and just wearing it as it is supposed to. but for some reason i can't see it. i tried deleting all the other mods i had and using on Armourers Workshop but it still didn't work. I'm on a Mac just in case it's a problem. Help or just tell me why it doesn't show up, please.

KatyPlayz

**Comment by RiskyKen** [comment]
Please to a debug crash and post the log here. To do a debug crash hold F3 + C for about 10 seconds.

You can also try changing the option useAttachedModelRender to true in the config file.

**Comment by KatyPlayz** [comment]
before i can send a debug crash, is there any way i can copy-paste it?

**Comment by KatyPlayz** [comment]
[crash-2016-08-29_18.48.46-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/442942/crash-2016-08-29_18.48.46-client.txt)

**Comment by KatyPlayz** [comment]
I hope this wil help you.

**Comment by RiskyKen** [comment]
Try the newest version and see if that works.

https://minecraft.curseforge.com/projects/armourers-workshop/files

**Comment by RiskyKen** [comment]
No replay. Presuming it's fixed.
