### ISSUE TITLE
[Suggestion] Quick equip methods

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#137]
Ideas about ways to quick equip AWS parts, skipping the GUI:
1. **Shift+rightclick**: swaps skin piece between player's body part and mannequin's body part that you shift-rightclicked on. Example: shift-rightclicking mannequin torso will equip player's torso, and vice-versa.
2. **Redstone powered mannequin**: if the mannequin is redstone powered and the player shift-rightclicks it, all skin pieces are swapped between mannequin and player
3. **Dispenser**: pretty much like what you can do with the dispenser with vanilla armor.

**Comment by EthanJJC** [comment]
Redstone is a good idea

**Comment by LordPhrozen** [comment]
Swapping skins with Man. is going to be an issue due to the number of skins a player can have equipped. Also there are commands to force skins to the player, even in specific slots. Imo this is unneeded. 

If you feel otherwise, please open a new ticket.
