### ISSUE TITLE
[Suggestion] Sloped Equipment Blocks

### ISSUE THREAD

**Issue by xSable** [RiskyKen/Armourers-Workshop#140]
I think it would make for some amazing skins if you added sloped equipment blocks, like the carpenter's mod has.

Letting you make edged blades instead of blocks, etc.

Either that, or being able to add support for Carpenter's Blocks so that you can use them, and fill them with equipment blocks, that would be super cool!

Here's a picture of one edged with carpenter's blocks, and textured as equipment cubes. They aren't dyable, but it still gives you a general idea of what I mean.

http://puu.sh/rBf76/d9d50c5275.png

**Comment by LordPhrozen** [comment]
This request has been denied. Performance issues.
