### ISSUE TITLE
[1.10.2] Idea Itzy Bitzy Tinzy Weeny Yellow Pokedot Bikini

### ISSUE THREAD

**Issue by BLSK** [RiskyKen/Armourers-Workshop#142]
I know you have expressed you are looking to update your mod.  As I have said I am seriously hoping 1.10.2 will be one such update for the modpack I have constructed.

I love chisel & bits... not sure how many people would say they don't XD.
Mind you if you were to look into it for 1.7.10 I would love you :)  Granted not expected.

Might it be a consideration for either:
1)Compatibility:  With it and in cases were we have bit armor it checks if the mod is present as to not allow the spawning of it in library if the mod isn't present

or/and

2) Figure out how to do it yourself so you could make the purely customizable without a mod presence.  I hear Chisels & Bits is a bit brilliant on the Anti-lag field so yeah...
2a) Worst case possiblity maybe a more Redpower 2 multiblock nature

I hope the new name of the post is more humorous :)

**Might even call it an Anti Bulky Armor as sometimes... just seems so huge for only having 2 layers**
![2016-10-09_02 49 26](https://cloud.githubusercontent.com/assets/8443396/19218555/13997876-8dcb-11e6-940f-ddde7aa7a223.png)
![2016-10-09_02 51 22](https://cloud.githubusercontent.com/assets/8443396/19218562/4b8097c4-8dcb-11e6-89ae-599f360ddfb5.png)

I can understand it not being done now but I hope it is considered :)

Oh and if possible:  Precolored blocks:  Put in dye machine and creative block placement which would benefit the above and the current.

**Comment by LordPhrozen** [comment]
I believe this basically asking for different sized/shaped blocks. This request has been denied a few times, as it causes performance concerns.

Pre-colored blocks would really help a very select few, for now I'm closing this and we can revisit this later if need be.
