### ISSUE TITLE
[Suggestion] Equipment replacer/updater 

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#143]
I have the following situation:
1. I release a set of AWS equipments ([as I did](http://ezerarch.com/armourersworkshop.html))
2. People download it.
3. Later on, I fix, change or update something ([as I'm planing to do](https://twitter.com/EzerArch/status/788922104066498561)). And then I release the update (Note: the armor skins have the same file name, but their IDs are obviously different).
4. People download it.

**Now I raise the problem:** People will then have both the outdated and the updated versions of my skin pack. They have to remove manually the outdated skins from items and containers.

**Idea:** There'll be a tool to replace or update a skin with another of same type.

Say, download an update pack, some *.armour files are overwritten. In game, you open the Equipment Library and select a skin. Click on "Check for duplicates", the mod would search all skin IDs with the same `customName`. If it returns there are more than 1 ID for the selected skin's customName, the mod would ask if you'd like to replace all skins with the one saved in my HD/library.

**Comment by LordPhrozen** [comment]
I believe this is now a feature with the tracked skin checkbox. closing.
