### ISSUE TITLE
Skinpaint causes misalignment

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#144]
After I used direct skin paint to add a head strap to a mask:

![2016-10-23_14 59 13](https://cloud.githubusercontent.com/assets/6743303/19627941/92d676e0-9931-11e6-800a-616f91c37790.png)

The mask skin became misaligned, it moved 1/2 block height up:

![2016-10-23_14 44 20](https://cloud.githubusercontent.com/assets/6743303/19627945/b8183b14-9931-11e6-9b80-a63e53368fd6.png)

**Comment by RiskyKen** [comment]
Aware of this. It affects all skins that have texture paint. I need to rewrite the system that scales and centres the skins in inventory slots.

**Comment by EthanJJC** [comment]
now could hide skin maybe remove skinpaint？but keep the skin color type

**Comment by RiskyKen** [comment]
Fixed!

**Comment by EzerArch** [comment]
BRAVO!
