### ISSUE TITLE
Custom gear doesn't go into OpenBlocks grave

### ISSUE THREAD

**Issue by kayila** [RiskyKen/Armourers-Workshop#145]
Not sure if this  is a bug in your code in how items are handled, or something that they will need to specifically add support for, but if the player dies, their gear doesn't get stored into an OpenBlocks grave and instead float next to it as if no grave mod was installed. Figured I'd start here and report there if you think it's not something you can fix.

**Comment by EthanJJC** [comment]
u should ask the OpenBlocks‘s author to support Armourer’s Workshop

**Comment by Mylezz** [comment]
# Should skins be dropped on player death.
    # 0 = use keep inventory rule
    # 1 = never drop
    # 2 = always drop
    I:dropSkinsOnDeath=0

**Comment by Mylezz** [comment]
Thears a config For it

**Comment by LordPhrozen** [comment]
Between config and reaching out to open graves. I think this one is a bit aged and should be closed. If you feel differently please submit a new ticket.
