### ISSUE TITLE
Feature Request: Ability to use color picking tool without selecting paint type

### ISSUE THREAD

**Issue by kayila** [RiskyKen/Armourers-Workshop#146]
It'd be nice if options were added for the color picking tool that allowed you to select a paint color without type, this would allow you to grab a color off of a skin, drop it into a paint mixing block with shift rightclick, then immediately put it on a brush with another shift rightclick instead of having to go into the block and change it from `None` to `Normal` first.

**Comment by RiskyKen** [comment]
Sounds like a good idea.
