### ISSUE TITLE
doll crashes client when placed in the world

### ISSUE THREAD

**Issue by louthinator** [RiskyKen/Armourers-Workshop#148]
like is stated in the title i randomly got a gift sack with a doll inside but when i placed that doll in the world my game crashed however when i log back on the item is placed with no issues, the crash log is attached.
[crash-2016-12-01_13.03.38-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/625129/crash-2016-12-01_13.03.38-client.txt)

**Comment by RiskyKen** [comment]
Is this only happing on a server? Is the server also crashing or just the client?

**Comment by louthinator** [comment]
yes its happening on a server but only my client crashes the server is fine

**Comment by louthinator** [comment]
and as a correction it happens in single player too

**Comment by RiskyKen** [comment]
Fixed in 8add252ccb829bd1cd997f73b6fd6184e61b23fa
