### ISSUE TITLE
Crash when create new World. 

### ISSUE THREAD

**Issue by Lightarow** [RiskyKen/Armourers-Workshop#149]
Hi, I installed the Last version of Armourer WorkShop and a Crash happen when I create a new world. 
I made some research and I found that this is because of the Aether mod because of a contradiction. Could you fix it ? I need a lot this fix for upgrade the mod on my server. 

Here is my Crash Report : 

[crash-2016-12-10_01.15.41-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/643455/crash-2016-12-10_01.15.41-client.txt)

Here is part of of my Mod list :

http://prntscr.com/dhj6j4

**Comment by RiskyKen** [comment]
Try setting disableDollRecipe to true in the common config.

**Comment by Lightarow** [comment]
Problem fixed, thanks

**Comment by RiskyKen** [comment]
Fixed in newer versions of the Aether mod.
