### ISSUE TITLE
Skin loading Bug

### ISSUE THREAD

**Issue by Lightarow** [RiskyKen/Armourers-Workshop#151]
With the last version of Armourer (Thanks for help), at the connection, the Skin do not always load on multiplayer. Also, HD skins are bugged ><. 
Can You fix it ?

**Comment by EthanJJC** [comment]
HD skins  u should : clouse the SkinPaint in config,

**Comment by Lightarow** [comment]
I didn'T fond the  l'une for it. What is the name  of the parameter  ?
