### ISSUE TITLE
[Error] When wearing Armourers item

### ISSUE THREAD

**Issue by Chering031** [RiskyKen/Armourers-Workshop#152]
Reinstall Minecraft and Workshop mode. But the same thing repeats.
Could you fix this bug?
mod version 0.42.5
[https://www.youtube.com/watch?v=wWnigf_FxjM](url)

**Comment by RiskyKen** [comment]
Seen the video when I got up this morning.

If you don't have smart moving installed you set skinRenderType to 1 in the client configuration file. That should fix it.

Duplicate of #117
