### ISSUE TITLE
(Dragon Block C) Can't see Armour on the player

### ISSUE THREAD

**Issue by OkappaAN** [RiskyKen/Armourers-Workshop#155]
The mod causing this thing to happen is part of the Dragon Block C mods, in particular the JRBA Client. This mod gives the player hair, and probably this mod is interfering with your mod. Is there a way for you guys/you to give me a version where this doesn't happen? thanks. if you need me to give you the mod just tell me

**Comment by RiskyKen** [comment]
Sorry about the long wait been busy. So it's an issue with JRBA client not allowing the models to render? I can take a look into it.

Have you tried chaging "skinRenderType" in the client.cfg?

I will just reply to you on here.

**Comment by OkappaAN** [comment]
Thanks a lot for answering! I just tried with both 1 and 2. 2 didn't do a
thing but 1 kinda fixed it. Now, it fixed it because it is now rendering,
but it is rendering as if I was using the ''Child Model'', so it's smaller
and lower ecc.... How do I fix it? (Thanks a lot)

2017-03-03 23:11 GMT+01:00 RiskyKen <notifications@github.com>:

**Comment by OkappaAN** [comment]
Oh sorry, since it's a bit hard to ask questions here, and we're on a
schedule, could you give me your skype/discord id or even your telephone
number so that we can talk a bit more? It would be awesome, thanks for
listening!

2017-03-04 7:51 GMT+01:00 Okappaverde Caccs <governoluo@gmail.com>:

**Comment by RiskyKen** [comment]
I don't think the child model thing is a bug on my end. Someone is changing the isChild flag on the player model and not resetting it. What other mods do you have installed?

**Comment by OkappaAN** [comment]
Well, I had the Years C and the Family C that changed the size of the
player, but to see if they were the problem, I removed them, but it was
still happening. Still, do you have a skype account or something else?

2017-03-05 11:32 GMT+01:00 RiskyKen <notifications@github.com>:

**Comment by OkappaAN** [comment]
I just checked and as I can state the problem is again in the JRBA Client.
Isn't there a way to change it maybe using your mod?

2017-03-05 11:58 GMT+01:00 Okappaverde Caccs <governoluo@gmail.com>:

**Comment by RiskyKen** [comment]
I will have a look when I get back to my computer. I only have a TeamSpeak server "plushie.moe" but I am only on later at night.
