### ISSUE TITLE
Skin Bug 1.7.10

### ISSUE THREAD

**Issue by darkxbunny** [RiskyKen/Armourers-Workshop#161]
Hi. Help please.
HD skins and default skins displayed not correctly.
Mod list: http://niceminecraft.ru/bug/4.png

Bug:
http://niceminecraft.ru/bug/s1.png
http://niceminecraft.ru/bug/s2.png
http://niceminecraft.ru/bug/s3.png

Server core: Thermos 1.7.10

If I restarts my client many times - then skins was display correctly, but after a few minutes skins displayed transparent or incorrect.

**Comment by RiskyKen** [comment]
Try settings disableTexturePainting to true in config/armourersWorkshop/client.cfg.

**Comment by darkxbunny** [comment]
I have tried, no result
http://niceminecraft.ru/bug/s5.png

**Comment by RiskyKen** [comment]
Can you turn on the debug text(F3) then hold ctrl and tell me what skin render types says.

**Comment by darkxbunny** [comment]
done
http://niceminecraft.ru/bug/s6.png

**Comment by RiskyKen** [comment]
Can you start up the game go into any world, make sure you see your player in 3rd person then exit the game and send me your logs/fml-client-latest.log file.

**Comment by darkxbunny** [comment]
done
http://niceminecraft.ru/bug/logs.zip


Thermos 1.7.10 core
https://github.com/CyberdyneCC/Thermos/releases

**Comment by darkxbunny** [comment]
"Try settings disableTexturePainting to true in config/armourersWorkshop/client.cfg" - my apologize, this way was right. I changed it only server part, but in client part not. Now all working. Thanks ^^
