### ISSUE TITLE
Player Skin Inventory

### ISSUE THREAD

**Issue by DrPiggy** [RiskyKen/Armourers-Workshop#166]
Hey, I'm making a capture the flag mini game mod for my friend's server, now because i dont want people to lose there inventory i save there inventory clear it, and when they finish the game, i restore it, BUT they also have AW on there server, so i imported the deobf jar into eclipse but i CANT find where you are saving the list of skins a player is wearing, so i cant save/clear/restore it, and people lose it if they die in the game. can someone tell me where you save it? thanks.

**Comment by RiskyKen** [comment]
Do you just not want them to drop skins when they die? Try changing the dropSkinsOnDeath option in the config file.

**Comment by RiskyKen** [comment]
Am going to guess that worked if not reopen the issue.
