### ISSUE TITLE
DivineRPG crash when opening creative tab

### ISSUE THREAD

**Issue by duhadventure** [RiskyKen/Armourers-Workshop#168]
[crash-2017-04-15_12.09.58-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/924368/crash-2017-04-15_12.09.58-client.txt)
[crash-2017-04-15_12.13.18-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/924369/crash-2017-04-15_12.13.18-client.txt)
I was attempting to add skin support for all the weapons in divinerpg, this happened. Mods installed:
[1.7.10][SMP]DivineRPG-1.4.1.3
Armourers-Workshop-1.7.10-0.43.0
CustomNPCs_1.7.10d(21feb16)

**Comment by RiskyKen** [comment]
Fixed in https://github.com/RiskyKen/Armourers-Workshop/commit/cba87008e8d87eeef7a42fc8dfdcec5dabba89c9 maybe if not reopen.
