### ISSUE TITLE
Invisible Equipment Block

### ISSUE THREAD

**Issue by dcsrewster** [RiskyKen/Armourers-Workshop#169]
Hello,

I'm having an issue with my equipment blocks. When placed, they are invisible. It doesn't matter whether I paint them or not. When I break them, I noticed that they're a pink and purple checker board pattern. I'm not sure if this is relevant or not. One thread I saw said to uninstall Optifine, which I can't do because it's tightly intertwined with Vivecraft. Any advice?

Thanks in advance.

I'm using the 1.7.10 version of Armourer's Workshop (1.7.10 is the only version with Forge support for Vivecraft.)

Mod List:

3D Furnace
Battlegear 2
Bibliocraft
3D block particles
Chisel
CoFH
DecoCraft
MoCreatures
Dynamic Lights
Dynamic Surroundings
Extended Workbench
iChun
ItemPhysics
Polearms Mod
ragdollCorpses

**Comment by duhadventure** [comment]
If you can, delete each mod one by one until you find which one is causing it to do that.

**Comment by RiskyKen** [comment]
Do you have an AMD/ATI GPU?

**Comment by RiskyKen** [comment]
No info given :disappointed:
