### ISSUE TITLE
FEATURE REQUEST: Dyes used on skins.

### ISSUE THREAD

**Issue by LordPhrozen** [RiskyKen/Armourers-Workshop#173]
Server option 

Use-Dyes:  0/1

Our server uses dyes, and they had to be made super expensive, as as soon as you unlock a color... you can basically use it on anything for the rest of the game. I could lower the prices if they were USED when you put them in the slot.

This would need to be acompanied by the ability to place another dye over that slot. to change it to the new color.

**Comment by RiskyKen** [comment]
added in https://github.com/RiskyKen/Armourers-Workshop/commit/df17d84907e7b5449c94b741cd447d5930b21129
