### ISSUE TITLE
Suggestion: Adjustable Build Size for Blocks

### ISSUE THREAD

**Issue by Richhobo1216** [RiskyKen/Armourers-Workshop#178]
I have been building some blocks recently, and I noticed that often times, I must make multiple blocks to get what I want. While this works, it would be much more convenient to be able to adjust the size. I'm not saying you can insert any value, because I know that's not practical, but I was thinking that you could make options. Like, instead of just 16x16x16, there could be 8x8x8, 32x32x32, 64x64x64, etc.

**Comment by RiskyKen** [comment]
Sounds like you want 32x32x32 in one block space. I will not be changing it from 16x16x16 because that is the scale Minecraft works at.

If that is not what you are talking about and just want more build space for your blocks then the next build has multi-blocks in it.
