### ISSUE TITLE
Suggestion: More types of blocks/items

### ISSUE THREAD

**Issue by Richhobo1216** [RiskyKen/Armourers-Workshop#179]
This means that when you save the block, you can save it as chest, furnace, crafting table, hopper, redstone, etc. It's basically an extension of the Ladder, Glowing, and Seat options that you currently have. This can also be extended into items. For example, pickaxes, axes, shovels, hoes, clocks, compasses, maps, etc. I understand that this might be difficult to implement, but it would increase the customization possibilities by a lot, and the entire premise of the mod is basically: More customizability for armor, tools, and blocks.

**Comment by RiskyKen** [comment]
Added block inventory skin option in https://github.com/RiskyKen/Armourers-Workshop/commit/c86a778d951b84776d381db38e90ca36626060e0

Other options will be added in time
