### ISSUE TITLE
Minefantasy II Weapon support

### ISSUE THREAD

**Issue by Cinamonfire** [RiskyKen/Armourers-Workshop#181]
I kind of understood how the weapon override in the config works but I don't know how to make an add on for minefantasy 2 for 1.7.10 and I was hoping if you can help out or at least help me with the config, the weapons there have an I'D for each weapon type but not for the material it was made of, if you could help you can send me a message or an email or something, I need help xc

**Comment by RiskyKen** [comment]
This is an error on MineFantasy2 side. They are registering renderers in post init and not init.

List of override here if it ever gets fixed.

sword:minefantasy2:standard_waraxe
sword:minefantasy2:standard_katana
sword:minefantasy2:standard_lance
sword:minefantasy2:standard_dagger
sword:minefantasy2:standard_warhammer
sword:minefantasy2:standard_sword
sword:minefantasy2:standard_greatsword
sword:minefantasy2:standard_halbeard
sword:minefantasy2:standard_mace
sword:minefantasy2:standard_battleaxe
sword:minefantasy2:standard_spear

**Comment by Sirse** [comment]
@RiskyKen, can you provide unobfuscated (dev) version of mod? Your Jenknis are down (http://jenkins.rx14.co.uk/)

**Comment by RiskyKen** [comment]
Some here that a little older I will add some for the newest version later on https://minecraft.curseforge.com/projects/armourers-workshop/files/2407574
