### ISSUE TITLE
Wand of style hurting entities

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#183]
The wand of style requires mouse left-click to apply skins on entities.

The problem is: they get hurt. No mercy for the poor entities and NPCs? :<

I suggest right-click instead.

**Comment by RiskyKen** [comment]
Right click should work for all entities apart from CNPCS, There is a bug on CNPCS side that stops left clicking from working, so nothing I can do about it.

Re-open if not not true!

**Comment by EzerArch** [comment]
> Reopen if not not true!

That's true, actually. Well, at least, is there a way to avoid dealing damage? In Galacticraft, we can left-click entities with a tool called [Frequency module](https://wiki.micdoodle8.com/wiki/Frequency_Module#Telemetry) without causing any damage.

**Comment by RiskyKen** [comment]
It hurts entities really?

**Comment by EzerArch** [comment]
Yes, it hurts mobs, passive entities and non-friendly NPCs.
