### ISSUE TITLE
Game Crash:java.lang.StackOverflowError: Rendering entity in world

### ISSUE THREAD

**Issue by mimiceolo** [RiskyKen/Armourers-Workshop#185]
I found a game crash:

https://pastebin.com/u93CK0yS

(It's little long)

**Comment by RiskyKen** [comment]
Please use paste bin for crash logs!

**Comment by mimiceolo** [comment]
You mean: https://pastebin.com/u93CK0yS
or this link: https://drive.google.com/open?id=0B1-oPK-aXvnlU3UxZGFiUXdXelk     (pastebin is limited words)

**Comment by RiskyKen** [comment]
looks like something was added to the skinnable items list that is not supported

**Comment by RiskyKen** [comment]
Fixed in https://github.com/RiskyKen/Armourers-Workshop/commit/cba87008e8d87eeef7a42fc8dfdcec5dabba89c9
