### ISSUE TITLE
Small sword item bug 

### ISSUE THREAD

**Issue by Warfreeworld** [RiskyKen/Armourers-Workshop#186]
![2017-06-06_03 38 56](https://cloud.githubusercontent.com/assets/29227679/26825547/5bce4d18-4a6a-11e7-94dd-97a2870f586a.png)

this is the result I get whenever I try to make a sword. 
Help :(

**Comment by RiskyKen** [comment]
Looks like you are holding a sword skin and not a skinned sword.

Press P to open the wardrobe and put the skin in the sword slot then hold a normal sword and it will show the skin

or 

put the skin and a sword into the skinning table to lock that skin into the sword.

**Comment by RiskyKen** [comment]
Reopen if this was not the issue.
