### ISSUE TITLE
Rendering Error

### ISSUE THREAD

**Issue by fireninja109** [RiskyKen/Armourers-Workshop#189]
When ingame, the skins don't render unless it's a solid block in place of the player's skin. For instance wings don't work but if you put solid white blocks on the same layer as the player's skin it will load the white.

**Comment by RiskyKen** [comment]
I don't understand what the bug. Please explain better, images maybe?

**Comment by fireninja109** [comment]
Basically, if you make a texture that replaces your skin it works but anything attached or floating off of your skin does not
