### ISSUE TITLE
Skin glitching through.

### ISSUE THREAD

**Issue by Dylsnake** [RiskyKen/Armourers-Workshop#194]
Here is the glitch...
![2017-06-24_23 30 04](https://user-images.githubusercontent.com/29675832/27509017-4ff01c1c-5936-11e7-9bf3-fd6e250a8a8a.png)
And here are the mods that I have...
![screenshot 66](https://user-images.githubusercontent.com/29675832/27509025-7912b23a-5936-11e7-8f14-2ca9f793d670.png)

**Comment by RiskyKen** [comment]
Try removing SkinPort.

**Comment by Dylsnake** [comment]
Still got the problem.

**Comment by RiskyKen** [comment]
Try updating AW

**Comment by Dylsnake** [comment]
Will that work on a server with this version?

**Comment by RiskyKen** [comment]
No the server will need to update but you can test it in single player

**Comment by Dylsnake** [comment]
It still didn't work

**Comment by RiskyKen** [comment]
Need to remove mods 1 by 1 to find out what one is doing it.

**Comment by Dylsnake** [comment]
Other people on the server don't have the same problem. I am using a mod pack so we all have the same mods.

**Comment by RiskyKen** [comment]
Have they tried putting on the armourers skin you are using?

**Comment by Dylsnake** [comment]
No, but it happens for any skin even the ones that render on others. Also its only the pixels that are merging with my skin. The shoes aren't glitching because they are one pixel of the skin.

**Comment by RiskyKen** [comment]
How did you make this skin? Did you turn the override option on when making it?

**Comment by Dylsnake** [comment]
I made it normally. And the override option is off, I will try with it on.

**Comment by Dylsnake** [comment]
Is it something to do with the config? I have tried it without other mods, but now I am convinced that it's something to do with the settings in the config. Also I have tried changing my graphics settings in game to see if that would do anything, that didn't work.

**Comment by Dylsnake** [comment]
I have been trying to fix it all morning, I still have not fixed it.

**Comment by RiskyKen** [comment]
Have you tried deleting your config file?

**Comment by Dylsnake** [comment]
I fixed it....
I first removed SkinPort, then changed something in the config (I forget what I changed) then it worked.
