### ISSUE TITLE
broken images in guide 0.5.1

### ISSUE THREAD

**Issue by Qazplm601** [RiskyKen/Armourers-Workshop#2]
https://imgur.com/a/Iul5q

the images appear to be broken in 0.5.1

**Comment by ghostbuster3210** [comment]
i have a problem, it worked great but the next time i got on MC, the gui's worked, but when i put the armor on, nothing happens, it wont appear!

**Comment by RiskyKen** [comment]
@ghostbuster3210 please make a new issues

**Comment by ghostbuster3210** [comment]
ok  i iz sowwy .-.

**Comment by RiskyKen** [comment]
Forgot to close this!
