### ISSUE TITLE
Outdated TiC compat

### ISSUE THREAD

**Issue by Mortvana** [RiskyKen/Armourers-Workshop#20]
As of build 893, built a week ago TiC compat is broken and causes all "Weapons" to not render, the same is true in the latest, 906 (what I am using). Disabling compat fixes it as expected.

This is the commit which changed the renderer:
https://github.com/SlimeKnights/TinkersConstruct/commit/075b769db2be26adc5b492240f67d09defee2535

**Comment by RiskyKen** [comment]
Has TiC got a build server? I can't find any builds over 858.

**Comment by Mortvana** [comment]
On Prog's jenkins, https://dvs1.progwml6.com/jenkins/
