### ISSUE TITLE
Really weird texture bug

### ISSUE THREAD

**Issue by BatVenomPL** [RiskyKen/Armourers-Workshop#201]
I don't even know how to call it... I'll just show picture 
![image](https://user-images.githubusercontent.com/30902656/29175245-cd75f69e-7de8-11e7-9324-04c5cc0627b3.png)

**Comment by EzerArch** [comment]
Could you test with Armourer's Workshop only? Probably another mod is affecting it.

**Comment by RiskyKen** [comment]
Please send me a debug crash log. (Hold F3 + C for 10 seconds then let them go)

**Comment by RiskyKen** [comment]
No info given!
