### ISSUE TITLE
Bug like #203 (Invalid Equipment Skin)

### ISSUE THREAD

**Issue by Flashback083** [RiskyKen/Armourers-Workshop#205]
Hello ! I didn't find a solution for this bug (#203) :/ i delete the skin database folder but i have still the bug with last version of AW
Also, im not good to explain, i just make a little video to show my bug ^^'
https://www.youtube.com/watch?v=sU7uLgu8kA0&feature=youtu.be

Thanks for your help !

**Comment by RiskyKen** [comment]
One of the mods you have installed must be editing the NBT of items in your hand.

**Comment by RiskyKen** [comment]
Let me know if you see any errors in the console.

**Comment by Flashback083** [comment]
I have no errors and this bug appears only in multiplayer not solo, i check for any mod can modify NBT

**Comment by Flashback083** [comment]
Oops forget its in solo mod too sorry

**Comment by Flashback083** [comment]
I think i found the mod its MagicCrusade <_<

**Comment by RiskyKen** [comment]
Last commit was years ago so they are maybe not modding any more :( https://github.com/rpereira-dev/Magic_Crusade_1_8/issues
