### ISSUE TITLE
possible export to json or obj format?

### ISSUE THREAD

**Issue by jomyhuang** [RiskyKen/Armourers-Workshop#207]
I want to do some MC video by 3DS MAX. 
any possible able to export/convert .amrour to MC json (use cubik studio) or 3D obj format?

**Comment by RiskyKen** [comment]
I would like to add this but I don't really know much about 3D modelling. AW models are not textured so most modelling programs will not be able to read them even if they are obj files.

I can export the models as obj files but am not sure what programs will read them. 

https://gamedev.stackexchange.com/questions/21303/how-can-i-include-vertex-color-information-in-obj-files

I need someone that has a program that can read models like this so it can be tested.

**Comment by jomyhuang** [comment]
maybe consider format Cubik studio (2.8.446) can import list?
JSON: minecraft model
MCPE
OBJ
PNG
QB: Qubicle binary voxels
QEF: Qubicle exchange voxels
SCHEMATIC: MCedit voxels
NBT: structure voxels
VOX: magicvoxel voxels
ZOX: Zoxel voxels

**Comment by jomyhuang** [comment]
I can help to test 3D model output format as you wish.

**Comment by RiskyKen** [comment]
I have started working on a ply exported for the mod. If you want to try messing around with the files I have a attached one.

![blender_2018-07-31_19-58-51](https://user-images.githubusercontent.com/5360809/43481012-b4c20c38-94fc-11e8-8e4e-6a69c9221715.png)

https://plushie.moe/share/files/yuno%20gasai%20head.ply
