### ISSUE TITLE
Dyes don't work with Creepers

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#208]
Pretty specific bug: dyes don't work with Creepers (head slot).

![2017-09-21_03 16 33](https://user-images.githubusercontent.com/6743303/30681641-baefd2b0-9e7c-11e7-9be4-94d6555a2ee4.png)
Here both zombie and creeper are sharing the same dyed helmet.

**Comment by RiskyKen** [comment]
Seems they where only working on biped mobs.

**Comment by RiskyKen** [comment]
Any chance of us getting space suits in the global library? :stuck_out_tongue:

**Comment by EzerArch** [comment]
> Any chance of us getting space suits in the global library?

I'm working on something, but..... how do I do that?
