### ISSUE TITLE
Skinport compatibility with ArmorWorkShop mod

### ISSUE THREAD

**Issue by runescapejon** [RiskyKen/Armourers-Workshop#209]
when you have SkinPort-1.7.10-v8c and Armourers-Workshop-1.7.10-0.47.1
and go ingame look at your inventory this spam in clientside
https://pastebin.com/myHB7Z3m
it's make it annoying when your trying to debug something
but anyways can you do something about 
`FileNotFoundException` and not make it spamming 

 thanks

**Comment by RiskyKen** [comment]
Go into the AW client config and set texturePainting = 2 to disable it. That should fix the issue.
