### ISSUE TITLE
Help me with the bug MOD

### ISSUE THREAD

**Issue by g966** [RiskyKen/Armourers-Workshop#21]

**Comment by g966** [comment]
Armourers-Workshop Bug  https://www.facebook.com/photo.php?fbid=683610711761326&set=pcb.683610891761308&type=1&theater

**Comment by g966** [comment]
image1> https://www.facebook.com/photo.php?fbid=683610711761326&set=pcb.683610891761308&type=1&theater
image2> https://www.facebook.com/photo.php?fbid=683610805094650&set=pcb.683610891761308&type=1&theater
image3> https://www.facebook.com/photo.php?fbid=683610811761316&set=pcb.683610891761308&type=1&theater

**Comment by RiskyKen** [comment]
You need to say what the bug is or I can't help you.

**Comment by asiekierka** [comment]
@RiskyKen - just fix any bug in the mod and close this.

**Comment by Razorskills** [comment]
lol fix the bug

**Comment by RiskyKen** [comment]
No info given.
