### ISSUE TITLE
Disabling wings animation

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#210]
I'm thinking of using wings to make backpack-like skins, such as scuba tank, gliders (static wings) etc. For example:  I tried to mimic a Mekanism jetpack.

![2017-01-04_02 01 54](https://user-images.githubusercontent.com/6743303/31225890-65d5d53e-a9aa-11e7-81d6-06a287fb0c3a.png)

But the chest bounding box is limited.
![2017-01-04_01 58 57](https://user-images.githubusercontent.com/6743303/31225907-7e8486fc-a9aa-11e7-81ca-188695deca48.png)

Then, the wing addition has opened that possibility. I found out I can set wing angles to zero to disable the flapping animation, and place the markers anywhere. My question is, since I'm making something not expected, can I make wings this way without any problem? 

_Suggestion:_  An "animated wings?" checkbox in the Skin Settings tab would enable/disable the wing animation options (speed and angles) and dismiss the need of markers.

_Nitpick suggestion:_ is it possible to align the torso model in the wing mode with the torso model in the chest mode? Because if I want to use the chest skin as base for wing skin, the skin will be 2 blocks off N-S ward.

**Comment by RiskyKen** [comment]
Yes setting both angles to the same value will work fine. If you are having issue setting them to the same value, there is a preview build on the discord server that has fine tune buttons and a bigger wing size. https://discord.gg/SMjJj5R

and yes I will fix the offset, I will also fix the sword/bow offset.
