### ISSUE TITLE
Compatibility with Naruto C

### ISSUE THREAD

**Issue by midas22** [RiskyKen/Armourers-Workshop#211]
There are two main problems that i have noticed with these two mods; one being the armour staying in place, while the running animation from Jin's mod takes place, two being that Jin's skin which is slightly different than the normal Minecraft skin, is in conflict with the armour when you use the override function. If you could fix this at any time, i and presumably many other people would be very happy.

**Comment by MERENDA22** [comment]
I also want a solution for this.

**Comment by RiskyKen** [comment]
As far as I know this was fixed. Both mods added stuff to make it work. Painting onto the players texture will most likely never work but the model blocks should render and rotate with the player.

**Comment by LordPhrozen** [comment]
No further comments in a significant length of time. closing.
