### ISSUE TITLE
more player models skin url not working

### ISSUE THREAD

**Issue by breezyflu** [RiskyKen/Armourers-Workshop#212]
As the title says the skin url isn't working. I read on issue #130 that i need to disable texture painting which is what i did i set the texture painting to 2 and it still doesn't work. Is there another option for disabling it?

**Comment by RiskyKen** [comment]
I don't know what feature you are talking about. If you have turned off texture painting then it is most likely nothing do to with AW. Mojang changed something that stopped a lot of older mods loading textures am guessing that is the issue you are having. If not reopen this issue.
