### ISSUE TITLE
Skinnable Everything?

### ISSUE THREAD

**Issue by RangerNorth** [RiskyKen/Armourers-Workshop#214]
Just because I love this mod so much I wanted to ask can you make everything skinnable? Such as a feather could be used for the skin of a feather sword? Or a candle I make with Armourers Workshop could be skinned to a custom candle texture I make? That way you could skin everything without restrictions to item properties. It would be neat I think to skin custom models to custom textures.

**Comment by LordPhrozen** [comment]
Custom items can be injected with ease. with whatever texture you wanted. check out the mod "MetaMod". If you're looking for something else, please clarify

**Comment by EzerArch** [comment]
As per "need info" label, just an opinion:

If I had to choose, I would make horse and pig saddles and donkey chests skinnable. These items are the closest things to armor pieces.

**Comment by LordPhrozen** [comment]
There are a few of these requests that are about skinning non bipedal creatures. im going to consolidate them.
