### ISSUE TITLE
Armour Rendering Possibility? 

### ISSUE THREAD

**Issue by RangerNorth** [RiskyKen/Armourers-Workshop#215]
Is it possible to have it so when you skin your custom armour you make to a piece of armour in game it still keeps the armours texture and then adds your custom armour as an overlay so to speak? For instance I want to have a vanilla iron helmet with custom horns I make with armours workshopand combine the two together so I have a Iron Horned Helmet and the helmet and the horns both render with one canceling the other out. Could be a new GUI and block involved as well Binding Block perhaps... anyone?

**Comment by LordPhrozen** [comment]
I see this as an enhancement to the skinning block. Checkbox to allow for original model/art to render as well. I feel this would look ugly 90% of the time however, im leaving this open unless Ken says hes not interested in doing this feature.

**Comment by RangerNorth** [comment]
I don't know I feel it would look nice imagine all the plain old boring helmets most mods add with no real appeal to wear. But add a spike or horns to say a bronze helmet from a mods it would look great. Or say for instance the Black Ones from Nilfgaard from the Witcher 3, they have 2 rods with feathers mounted to the side of their helmets. I purely see this as a enhancement personally though I do understand the reason you may not. I run a RPG server and having that extra bit of variety to all armor pieces would be ideal.

**Comment by LordPhrozen** [comment]
Yes but you can use blocks + skin-paint to achieve nearly the same result. OR do what i did for my mmo, make complete replacements of everything and keep the art style consistent :)

**Comment by RangerNorth** [comment]
Good idea and for the most part anything I can't achieve usually I make within your mod out of the materials you provide. I just think that feature would be amazing I already mod most of my items and blocks into the game it's just I can't achieve custom armor models. So adding that feature is like critical for some of my ideas. I love the mod just I'm limited at certain points. Maybe I'm a fool but I've never used the skin paint feature maybe I'm missing a big part of your mod. Is there a current tutorial or how too for your newer mod elements.

**Comment by LordPhrozen** [comment]
Not my mod, its Kens, Im just cleaning up the issue tracker :)

Do yourself a favor and join the community for the mod, lots of talented artists you can learn from : https://discord.gg/5Z3KKvU

Closing this issue, as i think this will solve your problem.
