### ISSUE TITLE
Tinkers' construct compatibility unreliable

### ISSUE THREAD

**Issue by praryboy** [RiskyKen/Armourers-Workshop#22]
In singleplayer the custom weapons work for tinkers' construct weapons, although I noticed that the transparent blocks in the "lightsaber" become opaque if used with a TiC weapon.

In multiplayer however, only vanilla swords work

**Comment by praryboy** [comment]
running armourers workshop 0.28.0.7
forge 1291
minecraft 1.7.10

**Comment by RiskyKen** [comment]
What TCon version are you using? Updating it may fix the transparency issue.

**Comment by praryboy** [comment]
whoops, forgot to mention.

1.7.10-1.8.2a, so I guess I'm a little behind now. Is that what's causing the multiplayer issue as well?
