### ISSUE TITLE
1.12.2 / 1.13 Update?

### ISSUE THREAD

**Issue by eksynn** [RiskyKen/Armourers-Workshop#220]
Could we have a 1.12 update, please? And 1.13 when it's finally out, though i'd recommend waiting for the patches that usually comes afterwards xD
But i'm sure they wouldn't break the mod anyway

Thanks in advance!

**Comment by eksynn** [comment]
i don't understand the invalidation xD but ok

**Comment by RiskyKen** [comment]
Bug tracker is for bugs!

**Comment by eksynn** [comment]
op, my apologies xD i didn't know where to go to request this - since this is a sort of issue, figured it'd be ok to post in the issues tab for github (◠‿ ◠ )
but since you're here, do you have any plans to update it to 1.12/1.13?
