### ISSUE TITLE
Bug occurs when changing version

### ISSUE THREAD

**Issue by xiaoguai0992** [RiskyKen/Armourers-Workshop#221]
I'm trying to update mod version from 0.40 to 0.47. Then bug occurs.
When I run minecraft using version 0.47, I found following bug.
First, wear a wing created from **0.47**.
Then, hold a wing created from **0.40** (the wing was created by previous version 0.40)
Next, right click. This operation is going to wear the old-version's wing.
You find that you wear the old-version's wing successfully (and successfully rendered on your screen), but when you press P to view your container, you found nothing. So I can't take off the wing anymore.
Repeat these steps, you can have at most 3 wings on your body and cannot take them off.
I hope you can fix it. Thanks a lot!

**Comment by RiskyKen** [comment]
This should be fixed in newer versions, not sure when the fix was added.

Will maybe need to use the command `/armourers setUnlockedWardrobeSlots @p armourers:wings 8` so  the extra wardrobe slots can be accessed to remove this skins.

If you are still having this issue please reopen this issue.
