### ISSUE TITLE
Why does not the player's skins apply to mannequins and equipment tool?

### ISSUE THREAD

**Issue by DeathTic** [RiskyKen/Armourers-Workshop#222]
Why does not the player's skins apply to mannequins and equipment tool?

The player's skins have not been applied to mannequins or equipment builders since 2 weeks ago.

Was there any notice about this?

This information may not be accurate due to the use of a translator.

**Comment by EzerArch** [comment]
> Was there any notice about this?

I did. :3

I even blamed another mod that I had updated. Now I know I'm not alone. What a relief!

**Comment by RiskyKen** [comment]
Mojang changed something and the skin API is not working anymore. I have added a temporary fix for the next build.

The latest preview build already has the fix. https://discord.gg/SMjJj5R

**Comment by DeathTic** [comment]
Has the issue been resolved in the latest version? Beta version 0.48.0 still does not solve the problem

I've experimented with a few people and found that a few years ago the skins were applied instead.

I hope it is not a problem with the translator.

**Comment by RiskyKen** [comment]
Fixed in 0.48.1 https://github.com/RiskyKen/Armourers-Workshop/commit/f36ffd6be601b37470b0296f3bf409dccb8ec504
