### ISSUE TITLE
Skin preview crash.

### ISSUE THREAD

**Issue by duhadventure** [RiskyKen/Armourers-Workshop#226]
One of our players had a crash with the new Skin Display GUI when hovering over a Skinned weapon in a Blood Chest from evilcraft (repairs Items)
[crash-2018-03-26_20.03.04-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/1852879/crash-2018-03-26_20.03.04-client.txt)

**Comment by RiskyKen** [comment]
Have then been able to recreate this crash more than once?
