### ISSUE TITLE
Translation / PT-BR

### ISSUE THREAD

**Issue by evernife** [RiskyKen/Armourers-Workshop#23]
This is not an inssue, but... I am a brazilian player, and i like your mod, i can translate him to porguese-brazilian if you want.

^^

**Comment by RiskyKen** [comment]
I would be happy for any translations you can provide. The newest language file can be found here: https://github.com/RiskyKen/Armourers-Workshop/blob/develop/src/main/resources/assets/armourersworkshop/lang/en_US.lang

Sorry I did not get back to you sooner, I have been a bit busy.
