### ISSUE TITLE
Sind cool ideas

### ISSUE THREAD

**Issue by karmathehoe** [RiskyKen/Armourers-Workshop#231]
Some cool ideas
Number 1. holster which you can BIND to a weapon. The holster is made of 2 parts . with weapon and none weapon. When you Holding the binded weapon the holster has no weapon.         
2. Carpenters support.
3. custom Render like make a big weapon rendered small . small weapon but mich details and more. 

And i had a moreplayermodels bug. The armor is showen small with big model

**Comment by LordPhrozen** [comment]
1) This is a fair suggestion, I would love to have sheathed/back tool style skins.

2) This has been denied. and with good reason. Performance would plummet

3) Stylistically seems like a bad idea, from an art direction perspective to deal with multiple voxel sizes on a player. This will unlikely not be added.

**Comment by LordPhrozen** [comment]
I think this is really out of scope, the more i think on this. point 1 would need additional functionality that is out of scope for the mod. ( sheathing a weapon ). 

Closing this.
