### ISSUE TITLE
Pry skin off of container.

### ISSUE THREAD

**Issue by LordPhrozen** [RiskyKen/Armourers-Workshop#233]
We sometimes accidently put our final skin version into a container. For these mistakes, it would be good to be able to remove them from the container.

Even if it was putting it in a crafting grid, and you get the skin ( container item destroyed) seems like a decent way of doing it.

Alternitively, Shift-Clicking the armourer with a skinned continer, could load the data like its loading from a skin file.

**Comment by LordPhrozen** [comment]
note: we were able to do this with one of the commands and a command block, pulling the skin id

**Comment by EzerArch** [comment]
Question: I've seen a tooltip "Skinning table: Apply and remove skins from items", but I couldn't use it remove the skin. How to do it?

Using: Armourers-Workshop-1.7.10-0.48.3.jar
