### ISSUE TITLE
Visualization error with Optifine and Shaders

### ISSUE THREAD

**Issue by DerGudeBuckelwal** [RiskyKen/Armourers-Workshop#237]
Greetings everybody,
i have and issue when im trying to play with AW and Optifine E3 or E7 1.7.10
When im playing with any Shaderpack, the armors and Tools with AW Skins disappear in first person and looks completly weird in third person.
![unbenannt](https://user-images.githubusercontent.com/40107035/41190306-53685882-6bdc-11e8-86dd-8d8db01483ad.png)

**Comment by LordPhrozen** [comment]
There is an option in the config to address this. please check configs.

**Comment by dragonbaron1** [comment]
what configs? from optifine or armors workshop? This answer is so vague that it needs a university level of interpretations to understand. 
And what options in the config? I doubt there is a one-labeled "armors workshop fix"
