### ISSUE TITLE
Custom npc clone doesnt spawn if they have dyable AW armor

### ISSUE THREAD

**Issue by Zakkaroom** [RiskyKen/Armourers-Workshop#239]
Im currently working with Cnpc 1.7.10 and when I save a clone with some armor that I have dyed and then spawn it with the axe, it wont spawn.

**Comment by LordPhrozen** [comment]
After some additional tinkering, it looks like other mods have this issue with CNPC as well. clone saves are different then spawn crystal saves. I've brought this up to Noppes.

**Comment by LordPhrozen** [comment]
I dont believe this error lies with AW mod, closing this issue.
