### ISSUE TITLE
Mannequin Perm - Config request

### ISSUE THREAD

**Issue by LordPhrozen** [RiskyKen/Armourers-Workshop#240]
Server Option - mannequinEditRequireOP : True/False

Server Option - notOPEditMessage : String - Displayed if the above option is enabled, and someone without op tries to edit, and this string is not empty

**Comment by RiskyKen** [comment]
Permission node `armourers_workshop.tile.mannequin.open-gui` was added to mannequins for 1.12.2, can't remember when it got added.
