### ISSUE TITLE
Minecraft Crashes (Possibly too much armor?)

### ISSUE THREAD

**Issue by Cheezarito** [RiskyKen/Armourers-Workshop#243]
so I've played this mod for a while now but just recently today, I was logging into my Minecraft world and it crashed, I had other mods installed to I removed them except the amours workshop mod and it still crashed, I made a backup world and removed the mod from the world, it worked perfectly fine, I'm not sure what the issue is with the world or possibly mod, I had a lot of custom armour in that world so that might be the problem, I also have a lot of finished armor that haven't been backed up, I didn't want to use older versions as I fear it might affect the world, please help me, thank you

**Comment by Cheezarito** [comment]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/8/18 6:47 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -16
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:26)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75)
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548)
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878)
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.12.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 227502232 bytes (216 MB) / 436207616 bytes (416 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.48.1} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.48.1.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Cheezarito'/145, l='My Hero Academia', x=51.54, y=92.09, z=666.19]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by RiskyKen** [comment]
I think one of your world chunks has corrupted, it should crash with or without the mod installed. Check and make sure it's really not crashing without the mod it's most likely when a certain chunk loads.

You can try a tool like [Minecraft Region Fixer](https://www.minecraftforum.net/forums/support/server-support-and/1903200-minecraft-region-fixer) it will maybe be able to fix it for you. 

If you only care about getting the models out of the world then;
1. make a new world
2. copy "<mc instance>/saves/<old world>/skin-database" in to your new worlds folder.
3. load into your new world and type "/armourers adminPanel" then press the recover skins button (this will take a min)
4. after that copy "<mc instance>/recovered-skins" into "<mc instance>/armourersWorkshop"
5. open the library block and press refresh
6. all the models from the old world should now be in the recovered-skins folder

**Comment by Cheezarito** [comment]
thank you so so much
