### ISSUE TITLE
Player Skins Not Showing

### ISSUE THREAD

**Issue by SoraXRoxas1** [RiskyKen/Armourers-Workshop#244]
I have tried to locate and fix this problem for a few weeks. Whenever i play on a server or singleplayer world the Armourer Just will not show my player skin when I set it down and press SET. 
Minecraft 1.7.10
FML 7.10.99.99
Forge 10.13.4.1614
Armours Workshop 1.7.10-0.42.5

**Comment by LordPhrozen** [comment]
Looks like a pretty old version of AW. Please update. If the issue persists with an updated version of the mod, please re-post the issue and we'll look into it. 

This stems from some changes mojang/Microsoft made, and are addressed in newer versions.

**Comment by Dovahkiin-Warrior** [comment]
I'm having this issue, armourer's workshop 0.48.1. It works for all other players on a 16 player server except two of us, whom which do own a valid minecraft account and skin. Forge is 1614.
