### ISSUE TITLE
Skin not rendering

### ISSUE THREAD

**Issue by Doidaohc** [RiskyKen/Armourers-Workshop#246]
Hi, I've been trying to recover some skins from a server (Because dumb me didn't save the .armour files).
I have access to the server files and the skins I want to recover are currently equiped on my character.
For some unknown reason the skins (at least the ones equipped on me) won't load anymore, I have a matching version of the ID in the skin-database folder.
I was running on an old version of the mod and updating it to the newest one made half my skin load (Weapon, feet and legs are loading. Chest and head aren't, they are just blank skins with a loading icon).

So far, browsing through the forums and github, I've found and tried the following solutions:
None of them solved my problem.

- In the config file client.cfg I edited texturePainting to false and skinTextureRenderOverride to true (one at a time).
- Reloaded server multiple times.
- Used the adminPanel to try to recover the skins, most of them worked, but again, head and chest aren't in the middle of the skins that successfully loaded.
- I have even got to the point of downloading version by version to try and get it to work, no success there.

All of these have been attempted on both versions (The one I had and the newest one) and nothing seems to make the chest and head show up.

I don't know what else to try.
Thanks in advance for taking the time to read this.

**Comment by Doidaohc** [comment]
Hello again, 
After many trials and errors I had a friend of mine take a look at the files and he figured it out. The skin files were actually corrupted and he managed to "fix" it, something along the lines of a "pattern" that could be undone.
I have no idea what caused the files to get corrupted and no idea if this information can help anyone who has the same issue and search the forums, either way, I got my skin back and I'm posting it as soon as I improve it a little more.
Thanks!
![yasuo](https://user-images.githubusercontent.com/1452210/43298765-c229b506-912d-11e8-9cc6-d33c2f24a12f.png)

**Comment by LordPhrozen** [comment]
Glad to see you resolved your issue. Unsure what sort of corruption was seen, but would love to know what the exact fix for the issue was, may help in preventing issues in the future.  please feel free to open a new issue here to share them. closing this for now.

**Comment by Doidaohc** [comment]
" Everytime the byte 0A was supposed to show up on the file it was replaced by the bytes 0D 0A, so I just searched and replaced 0D 0A for 0A and things worked fine. "

His words, hope it helps.
