### ISSUE TITLE
Armourer Get More Range ?

### ISSUE THREAD

**Issue by Zakkaroom** [RiskyKen/Armourers-Workshop#247]
When we are moving with the xyz axis the skin to hide the real armourer block from the player, Its difficult to hide cause the range is only 1. Do you think we could maybe have move range ? Maybe 2 or 3 ?

**Comment by RiskyKen** [comment]
I don't understand, are you talking about the Hologram Projector block?

**Comment by Zakkaroom** [comment]
Im talking about the armor stand

**Comment by LordPhrozen** [comment]
One neat use for mannequins is ghost NPCs by using an invisible CNPC over where the mannequin is being rendered.

so [M][W][R]   ( Mannequin, wall, render of mannequin) is what's being requested here.

**Comment by LordPhrozen** [comment]
Again, to be clear, it currentlly needs to be in some weird grid diagonal from the mannequin, and surrounded by transparent blocks, to achieve this effect. Being able to hide them in the floor, or behind walls, would be helpful. ( by extending the range you can render the skins away from the mannequin block )

**Comment by RiskyKen** [comment]
Am thinking of allowing a 3 block offset, that seem OK? Currently only allows 1.
