### ISSUE TITLE
Sever Tick Loop Error Caused by "java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException"

### ISSUE THREAD

**Issue by Alaberti** [RiskyKen/Armourers-Workshop#25]
This error happened in the latest version (29.1.75) on a dedicated server. Forge 1307.

Edit: Cat jumped on keyboard while posting, it was kinda funny.
---- Minecraft Crash Report ----
// Oops.

Time: 4/13/15 2:45 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at net.minecraftforge.client.MinecraftForgeClient.getStencilBits(MinecraftForgeClient.java:51)
	at net.minecraftforge.client.MinecraftForgeClient.<clinit>(MinecraftForgeClient.java:55)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:140)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1057)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1038)
	at java.lang.reflect.Field.get(Field.java:379)
	at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117)
	at riskyken.armourersWorkshop.common.addons.AbstractAddon.getItemRenderer(AbstractAddon.java:48)
	at riskyken.armourersWorkshop.common.addons.AbstractAddon.overrideItemRenderer(AbstractAddon.java:62)
	at riskyken.armourersWorkshop.common.addons.AddonBattlegear2.init(AddonBattlegear2.java:18)
	at riskyken.armourersWorkshop.common.addons.Addons.init(Addons.java:53)
	at riskyken.armourersWorkshop.ArmourersWorkshop.postInit(ArmourersWorkshop.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.LWJGLException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-504.3.3.el6.x86_64
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1657243624 bytes (1580 MB) / 3025666048 bytes (2885 MB) up to 3025666048 bytes (2885 MB)
	JVM Flags: 7 total; -Xms3000M -Xmx3000M -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:ParallelGCThreads=4 -XX:MaxPermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.88.1307 Minecraft Forge 10.13.2.1307 135 mods loaded, 135 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.88.1307} [Forge Mod Loader] (gm.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1307} [Minecraft Forge] (gm.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2-core{rv2-beta-18} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMiner_coremod{0.26.0_build.unknown} [Core mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WitchingGadgetsCore{1.1.5} [Witching Gadgets Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FEPreLoader{1.4.0-beta2} [Forge Essentials|PreLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.1} [CoFH Core] (CoFHCore-[1.7.10]3.0.1-254.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfare{2.4.83-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareAutomation{2.4.83-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareNEIPlugin{2.4.83-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareNpc{2.4.83-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareStructure{2.4.83-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AncientWarfareVehicle{2.4.83-beta-MC1.7.10} [Ancient Warfare Vehicles] (ancientwarfare-2.4.83-beta-MC1.7.10-RC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	appliedenergistics2{rv2-beta-18} [Applied Energistics 2] (appliedenergistics2-rv2-beta-18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	armourersWorkshop{1.7.10-0.29.1.75} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.29.1.75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Automagy{0.22.2} [Automagy] (Automagy-1.7.10-0.22.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalExpansion{1.7.10R4.0.0} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0-176.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1210-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1_B44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BloodUtils{1.4} [BloodUtils] (BloodUtils-1.4_B0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Botania{r1.6-176} [Botania] (Botania r1.6-176.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	props{1.12} [Decocraft] (Decocraft-v1.12b_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderStorage{1.4.6.31} [EnderStorage] (EnderStorage-1.7.10-1.4.6.31-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	extracells{2.2.53} [ExtraCells] (ExtraCells-1.7.10-2.2.53b82.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.1.321} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-163.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeEssentials{1.4.0-beta2} [Forge Essentials] (forgeessentials-1.7.10-1.4.0-beta2-servercore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.317.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.317.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	GregsLighting{1.11.1} [Greg's Lighting] (GregsLighting-1.11.1-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	HardcoreEnderExpansion{1.8} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	hexxitgear{1.5.2R1.0} [Hexxit Gear] (hexxitgear-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	hyperioncraft{1.7.10-0.2.3a} [HyperionCraft] (hyperioncraft-1.7.10-0.2.3a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ImmibisCore{59.0.5} [Immibis Core] (immibis-core-59.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	JABBA{1.2.0b} [JABBA] (Jabba-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	levelup{0.10} [Level Up!] (LevelUp!-0.10(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	mdeco{0.3.3} [Magical Decorations] (MagicalDecorations-0.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neiintegration{1.0.6} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OmnisCore{0.1.0} [Omnis Core] (OmnisCore-1.7.10 - 0.0.6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenPeripheralCore{0.5.0} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenPeripheral{0.2.0} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OCS{1.7.3} [OpenCCSensors] (openccsensors-1.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PneumaticCraft{1.6.3-65} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.3-65-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PowerConverters{1.7.10-3.0.4.47} [Power Converters] (PowerConverters-1.7.10-3.0.4.47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	quiverchevsky{b96} [QuiverBow] (QuiverBow_1.7.10_b96.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RedLogic{59.1.5} [RedLogic] (redlogic-59.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	runicdungeons{1.1.1} [Runic Dungeons] (runicdungeons-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Sanguimancy{1.1.8} [Sanguimancy] (Sanguimancy-1.7.10-1.1.8-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Stackie{1.5.1.32} [Stackie] (Stackie-1.7.10-1.5.1.32-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	thaumicenergistics{0.8.9.0b-rv2} [Thaumic Energistics] (thaumicenergistics-0.8.9.0b-rv2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicHorizons{1.1.1} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	thaumicinfusion{3.966} [Thaumic Infusion] (ThaumicInfusion-3.966.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThaumicPipes{1.2.00} [Thaumic Pipes] (ThaumicPipes-1.7.10 - 1.2.1b-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TMechworks{0.2.13.96} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.13.96.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TravellersGear{1.15.7} [Traveller's Gear] (TravellersGear-1.7.10-1.15.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	TwilightForest{2.3.4} [The Twilight Forest] (twilightforest-1.7.10-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMiner{0.26.0_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.26.1.unknown.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	VeinMinerModSupport{0.26.0_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.26.1.unknown.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wawla{1.1.1} [What Are We Looking At] (Wawla-1.1.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WitchingGadgets{1.1.5} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	worldedit{6.0.2-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.0.2-SNAPSHOT-dist.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.1.321} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	technom{0.9.0} [Technomancy] (1.7.10 Technomancy 0.10.f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IguanaTweaksTConstruct{1.7.10-2.1.2.101} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MooFluids{1.7.10-1.5.01.19a} [Moo Fluids] (MooFluids-1.7.10-1.5.01.19a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.1.321} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	OpenModsLib crash transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
	CoFHCore: -[1.7.10]3.0.1-254
	AE2 Version: beta rv2-beta-18 for Forge 10.13.2.1291
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.0-176
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Forestry : Info: The following plugins have been disabled in the config: apiculture, arboriculture, energy, food, lepidopterology, storage, buildcraft.fuels, buildcraft.recipes, buildcraft.statements, buildcraft.transport, propolis.pipe, equivelent.exchange, farm.craftory, industrialcraft
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by RiskyKen** [comment]
Woops!

Turning off Battlegear 2 support in the config should stop it for now. Will try and get a fix out tomorrow. :)

**Comment by Alaberti** [comment]
Thanks!
