### ISSUE TITLE
One/Two more RGB controlled channels.

### ISSUE THREAD

**Issue by LordPhrozen** [RiskyKen/Armourers-Workshop#252]
We utilize the Hair/Skin dye channels HEAVILY on FaerunHeroes. But we dont give players dye tables/dye bottles. Because of this we would like to ask for 2 new RGB controlled Dye Channels.

Eyes, and Accessory.

*This will simplify our creation of player editable items.  For example, the little bits on players hair. clips, bows, etc. 
*Easily let players choose their eye color, or if the server would like, a secondary Channel for more accessories.

Please Consider. This should be an easy add.

**Comment by RiskyKen** [comment]
Sadly the skin and hair colour channels are hard coded all over the code. Going to leave this open as I want to add it but it could take a while.

https://github.com/RiskyKen/Armourers-Workshop/blob/master/src/main/java/riskyken/armourersWorkshop/client/render/SkinModelRenderer.java#L312-L316

**Comment by LordPhrozen** [comment]
This has been completed in 1.12.2
