### ISSUE TITLE
Creative Armourer / Removal of Template Item

### ISSUE THREAD

**Issue by LordPhrozen** [RiskyKen/Armourers-Workshop#253]
Template items do not seem to do much. Right now they are an artifical gate making it so non-creative players can build withinout infinate resources. keeping in line for survival gameplay.

I feel that this is not how AW is being used 99.99% of the time. Can we get rid this item/requirement? is it needed?

If it absolutely is needed, can we get a creative version of the Armourer, that doesnt need it? As was done with the library?

**Comment by RiskyKen** [comment]
How about players in creative mode don't need to put a template in?

**Comment by LordPhrozen** [comment]
I think this is fine :)
