### ISSUE TITLE
Exception in server tick loop?

### ISSUE THREAD

**Issue by Gogglesquizz** [RiskyKen/Armourers-Workshop#26]
So, I run an adventurey RPG server and we've been having crashes recently when someone opens their wardrobe menu (I think that's what it is called, just the GUI where you equip things and check renders and all that). It is only crashing the server, client just gets a server closed. It's only started happening in the last update and the new one, prior to that it worked wonderfully. We love AW and have a lot of wonderful dwarf beards and whatnot we'd be sad to lose so I am hoping you can help. :)

Crash log from server: http://pastebin.com/wTrFVdL5
Server log regarding the exception: http://pastebin.com/ThPzTXft

Of course I realise we have a lot of mods and Cauldron and all that so if it's an issue with that we understand fully hehe. Just let us know so we can hold an AW memorial <3 It's also equally likely we've done something stupid so sorry in advance if that is the case!

**Comment by Gogglesquizz** [comment]
Just a bit of follow up info as we're testing. People with no AW items on can log in and open the menu fine. Those wearing it log in, all of it shows on them but their armour isn't hidden. Opening the menu then crashes the server. Occasionally those logging in with AW on crashes the server instantly.

**Comment by RiskyKen** [comment]
Are you running the latest version 1.7.10-0.29.2.76?

**Comment by Gogglesquizz** [comment]
Yes, we are.

**Comment by RiskyKen** [comment]
Is this only happing with one or two players or is it with everyone?

Looks like a skin has maybe went corrupt, not sure how that could happen.

**Comment by Gogglesquizz** [comment]
It is happening with six players, that's all we have on testing at the moment. All six were made a few updates ago and have been running perfectly until suddenly we all started crashing the server.

**Comment by Gogglesquizz** [comment]
We can use our alts if you need us to do anything in game. :) They can get on and get dressed just fine.

**Comment by RiskyKen** [comment]
If you have all your skins saved in the equipment library you can try deleting the equipment-database folder from the server. If you do this you will have to reload everything from the equipment library.

I have added some code for the next update that should stop corrupted skins from loading. So if you just want to wait that should fix it.

**Comment by Gogglesquizz** [comment]
Okay we shall do that! Thank you for your time.
