### ISSUE TITLE
[Suggestion] One handed bow

### ISSUE THREAD

**Issue by Kickiusz** [RiskyKen/Armourers-Workshop#261]
I'm surprised that no one suggested it here before, but it would be great to have an option to "freeze" left arm's animation while firing a bow, because not all ranged weapons need to be strained.

**Comment by LordPhrozen** [comment]
I second this one, FH;s Wands would benefit from this option.

**Comment by LordPhrozen** [comment]
After more thought this is out of scope. the animation will be called from the item. Adding additional mechanics to control player animations is really not applicable to the mod.
