### ISSUE TITLE
Models can't wear armours

### ISSUE THREAD

**Issue by In77** [RiskyKen/Armourers-Workshop#268]
In the newest version, models still can't wear armours :(

**Comment by LordPhrozen** [comment]
in 1.7.10 or 1.12.2 ?

**Comment by Hdm980129** [comment]
> in 1.7.10 or 1.12.2 ?

1.12.2

**Comment by LordPhrozen** [comment]
1.12.2 is incomplete at this time, Ken's aware.

**Comment by Hdm980129** [comment]
> 1.12.2 is incomplete at this time, Ken's aware.

Your reply is really fast :)

**Comment by Yoinker** [comment]
Where did you guys download 1.12.2?

**Comment by RiskyKen** [comment]
@Yoinker Discord https://discord.gg/5Z3KKvU
