### ISSUE TITLE
NPC Container Armor renders as Iron Armor

### ISSUE THREAD

**Issue by kyahco** [RiskyKen/Armourers-Workshop#27]
Containers on NPCs seem to only render as iron armor rather than the Armourers Workshop custom armor.

Here are screenshots showing such:
http://imgur.com/7zZWSjS,sdtyDvo,0iZckTq,W2Ka0NM,2F681Wg,L0IxC3S,19xHt9O,Tc3xOOV#7

As you can see, the containers have and where made from the madoka set and have the correct IDs but do not render as such.

Forge Version: 10.13.2.1291 (Recommended Version for 1.7.10)
Armourers-Wrokshop Version: 0.29.2.76 (latest)
CustomNPCs: 1.7.10d (Lastest for 1.7.10)

Forced Crash: http://pastebin.com/tCW86ssC

I've tested it on Singleplayer and Multiplayer(Vanilla Forge server and Cauldron sever), all in clean installs with ONLY Armourers-Workshop and CustomNPCs installed. 

*[joke] This is clearly needed for humanity to experience the enlightenment of a Hastune miku NPC running in circles yelling popipo. [/joke]*

**Comment by RiskyKen** [comment]
Can you try saving the same skins onto templates and tell me if the armour containers start rendering.

**Comment by kyahco** [comment]
As you can see in the pictures, I have the skins (the default madoka set) in template form in my inventory (both saved before and after) and I have also tried it with me putting the skins on, all to the to the same effect (Only iron armor).

**Comment by kyahco** [comment]
It appears that older containers that where made back in the 75 update still work though, it's only newer ones (made from from the library or the armour block doesn't matter) made in the 76 update. Though making new containers using the new update of those old skins does not work, ONLY containers made in update 75 (or before I assume) work.

Not sure if this is purely cosmetic, but it seem the older ones contain an "author" tag where as the new ones do not no matter how I try to make them.

**Comment by RiskyKen** [comment]
Ah I see what it's doing wrong. This is already fixed in my dev version but it has reminded me that containers will stop working in the next update. Am going to keep this issue open until that's fix too.
