### ISSUE TITLE
With Flan's mod will make some Render error.

### ISSUE THREAD

**Issue by MikuSnow** [RiskyKen/Armourers-Workshop#270]
**To Reproduce**
Steps to reproduce the behaviour:
1. Install Flan's mod
2. Install Armourers-Workshop
3. Join the game and press F5 or take some flans mod 's items in hand.
4.  Your game will be black.

**Screenshots**

![image](https://user-images.githubusercontent.com/7759441/53747551-79e19700-3ede-11e9-9e13-1363ee94b5c2.png)
![image](https://user-images.githubusercontent.com/7759441/53747561-7e0db480-3ede-11e9-8576-255c62b6ee44.png)

**Versions (please complete the following information):**
 - Forge: 14.23.5.2815
 - Flan's Mod:  1.12.2-5.5.2
 - Armourers-Workshop: The lastest code.

**Comment by RiskyKen** [comment]
Fixed in https://github.com/RiskyKen/Armourers-Workshop/commit/231597147fcc3aacb00299c9088210ba443bfcda
