### ISSUE TITLE
Is there any way to get armourer modells i build from a server?

### ISSUE THREAD

**Issue by Dudderle** [RiskyKen/Armourers-Workshop#271]
I know that there is the global skin liary but it is closed beta and i get it if is closed.
So is there any other way, except asking the owner (Server is death)

for exampel.
![2019-04-07_22 07 25](https://user-images.githubusercontent.com/49375752/55689255-9d3aae80-5982-11e9-8e0d-40419e5ca85e.png)
![2019-04-07_22 08 47](https://user-images.githubusercontent.com/49375752/55689256-9f047200-5982-11e9-8faf-e6f2d7b13de8.png)

**Comment by Dudderle** [comment]
it was a one piece server so

**Comment by RiskyKen** [comment]
You would need to get the server owner to change the config option allowClientsToDownloadSkins.

Use the Discord server for questions, bug tracker is for bugs! https://discord.gg/5Z3KKvU

**Comment by Dudderle** [comment]
ty
