### ISSUE TITLE
Skins to small

### ISSUE THREAD

**Issue by conor1234567** [RiskyKen/Armourers-Workshop#273]
Playing a modpack called MCA the forgotten era (found it on technic launcher).
Straight to the point , all the skins are 2 small ,they will clip with my actual skin but when put onto a mannequin its fine, ive tried to change some of the rendering options etc but no change

**Comment by conor1234567** [comment]
tried manequins again they are slightly better but still clipping

**Comment by RiskyKen** [comment]
Need a screenshot

**Comment by LordPhrozen** [comment]
No response, closing ticket.
