### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by XxNugBeastxX830** [RiskyKen/Armourers-Workshop#274]
My Brother try to log and he get kicked, the report is adressing a rendering problem with your mod, but my other brother succesfully log in
[crash-2019-06-17_16.43.36-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/3297577/crash-2019-06-17_16.43.36-client.txt)

**Comment by RiskyKen** [comment]
I don't see anything to do with my mod here. Have you tried without it?

**Comment by XxNugBeastxX830** [comment]
Nope, those errors are basically saying unable to render player, i use your mod since 1.7.10, so i basically know that your mod render A LOT, and especially players, since in 1.7.10 i had a bug where armourer made steve deformed XD so i tought it was your mod

**Comment by RiskyKen** [comment]
Errors are about sky colour, nothing yo do with the player.

**Comment by XxNugBeastxX830** [comment]
I play modded from 6-7 years, you're a programmer, so, HOW IS THIS POSSIBLE??Sky color??seriously?it's the first time in my life that i hear that, you know what can cause this?It's been 8 hours, I'M DESPERATE T. T

**Comment by XxNugBeastxX830** [comment]
Btw, i tried without ur mod, same thing, and i wanted to ask yousomething that i always wanted to know since 1.7.10, Mini Armourer was working quite well, so, why you removed it? It seemed near completition

**Comment by XxNugBeastxX830** [comment]
So basically ur right, nothing to do with your mod, but, can it be java itself?
