### ISSUE TITLE
Getting this message on chat with Armourer's Workshop mod

### ISSUE THREAD

**Issue by Anon28732** [RiskyKen/Armourers-Workshop#276]
Hi, I came here today to figure out why I got this issue I been having with using the armourer's workshop mod and how to get it fixed. So far as I know everything seems a bit fine, but I did this error message on the chat repeatedly saying chat.armourersworkshop:invalidJar

The issue I been getting.. 
![Desktop Screenshot 2019 06 27 - 18 14 20 58](https://user-images.githubusercontent.com/52301051/60307449-4d78dd00-990a-11e9-9235-4905d0a087af.png)

So yeah, I don't know exactly if a person or two discovered this with the mod. Been searching about this issue on the github, didn't find anything much about it. Could you please help me with the issue?

**Comment by RiskyKen** [comment]
Download the mod from curseforge. Don't edit it in any way.
