### ISSUE TITLE
Allow disable annoying message.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [RiskyKen/Armourers-Workshop#279]
As a modpack dev I often rename files to better reflect things with a very basic system - I renamed your Jar now it is annoyingly spamming things effectively messing with my ocd ... can you please add a way to ignore this bs?

This is the name change by the way 

u-Armourers-Workshop-1.12.2-0.49.1-a.jar

If you use my naming system it is not an issue but that means in front of the mod you would have "u- , s- , c-" which is Universal Server and Client also at the end of the name would be "-a , -b , -pa , -r" which is Alpha, beta, pre-alpha or release. Please consider how someone with ocd feels. I meticulously do this to each and every file.

**Comment by RiskyKen** [comment]
Adding a non ASCII character to the name will shut the system off.

**Comment by P3rf3ctXZer0** [comment]
That doesn't actually fix my file naming system.

**Comment by RiskyKen** [comment]
Can't just name it u-🔨-Armourers-Workshop-1.12.2-0.49.1-a.jar

**Comment by P3rf3ctXZer0** [comment]
hammer? 

At any rate I have never in 8 years had this kind of issue (god I am old.)

**Comment by P3rf3ctXZer0** [comment]
Whatever your mod is cool but spam is annoying ...
