### ISSUE TITLE
Armourer's Workshop support for BuildCraft Robots

### ISSUE THREAD

**Issue by asiekierka** [RiskyKen/Armourers-Workshop#28]
Their textures are 6x6 by default, but may be optionally 8x8 once I add player head support.

I'd love to add the necessary APIs to make this work.

**Comment by RiskyKen** [comment]
Do you have a cancelable robot render event in the buildcraft API? If so I could make a cross mod add-on for it. Would be a good test of my new skin API.

**Comment by asiekierka** [comment]
Just renders over the robot. The robot is a 6/16 x 6/16 x 6/16 cube, and then I'd probably add a way for an Item to implement IRobotOverlayItem.
