### ISSUE TITLE
Im having some lag (read pls)

### ISSUE THREAD

**Issue by GruesomeFalconer** [RiskyKen/Armourers-Workshop#280]
the mod is cool and all of that but i am having some lag when i open my inventory and 3rd person mode (F5) also lags me even if i dont have anything from the mod placed or equipped, some of my mods include Nei and optifine and more mods which could be incomptible but i dont know. I know it is in Beta but i would like to get a possible solution for this problem, maybe it is my Ram memory (wich is 2gb and per now i cant get a new one) Pls help me if you can

(Also english is not my first language so there may be a problem with what i am typing)

(I am playing in 1.12.2 KEEP in mind that pls)

**Comment by GruesomeFalconer** [comment]
Just fixed it soon dont worry anymore

**Comment by GariusSAV** [comment]
I have same issue? What did you do?
