### ISSUE TITLE
1.12.2 won't load or save creations

### ISSUE THREAD

**Issue by ThatLasagna** [RiskyKen/Armourers-Workshop#281]
Hi, I can't get my game to save or load any of my creations. It might be a user error, but I don't think so. I have watched many videos to see if I was doing anything wrong and as far as I know I'm not. It might just be a bug but I was wondering if anyone knows a solution?

**Comment by RiskyKen** [comment]
Make sure you type in a name when trying to save.

**Comment by ThatLasagna** [comment]
I thought that was it too, but I tried and it didn't work

**Comment by ThatLasagna** [comment]
Are there restrictions on what the name could be?

**Comment by RiskyKen** [comment]
Anything that is a valid filename should work. If you have the console open when playing, it may gave a clue to what is going wrong.

**Comment by ThatLasagna** [comment]
I did see a message continuously when I first downloaded saying that the mod was an invalid jar file, but when I downloaded it again and replaced the mod it stopped.

**Comment by RiskyKen** [comment]
Don't know where you got that version from but make sure you have the latest one from curse https://www.curseforge.com/minecraft/mc-mods/armourers-workshop/files/all

**Comment by ThatLasagna** [comment]
That's the one I replaced it with, I had the same problem of not being able to save the creation.

**Comment by ThatLasagna** [comment]
No

**Comment by RiskyKen** [comment]
Do they even show in the list?
Are you using the creative library or the normal one?

**Comment by ThatLasagna** [comment]
I see them when I get onto the creative library and I have tried to load them, but they just won't.

**Comment by RiskyKen** [comment]
Can you try loading one out, exit the game then send me your latest.log file.

**Comment by ThatLasagna** [comment]
Wow ok for some reason it's working now even though it's sending a message that it is incompatible.

**Comment by ThatLasagna** [comment]
Is this mod compatible with optifine? I just realized I turned it off and now it works.

**Comment by RiskyKen** [comment]
Make sure optifine is up to date. Older versions make the items invisible in your inventory.

**Comment by ThatLasagna** [comment]
Ok, thank you for helping I really like your mod!

**Comment by RiskyKen** [comment]
Thanks :)
