### ISSUE TITLE
[BUG] [1.12.2] Inconsistent Mannequin Skin Application

### ISSUE THREAD

**Issue by DoomRater** [RiskyKen/Armourers-Workshop#282]
**Describe the bug**
When I place a mannequin on a server, I can rename it to anyone's skin except my own and the skin will show up.  But when I rename it to my own skin, I see Steve.  I'm about to have my testing partner log in and see if she can see the mannequin of me, as well as one of her.  I also attempted to have someone else rename the mannequin to my name, but my skin still did not show up on the mannequin.

This same player tried to make a mannequin of himself and was unable to see it, but when he viewed a mannequin of himself that I made earlier, he was able to see it.

**Debug crash log**
https://pastebin.com/iMdRkUX2

**Additional context**
I saw EntityPlayerSP in the list of mobs for my own username, whilst also seeing EntitryOtherPlayerMP for the plyer I was asking to help me discover the issue.  Could that be the problem somehow?
Also, this problem appears to not be an issue in Single Player testing worlds.

**Mod Version**
1.12.2-0.49.1

**Comment by DoomRater** [comment]
**Screenshots**
https://imgur.com/a/UCMX1f3

**Comment by DoomRater** [comment]
When I log into a single player world and view the various mannequins, then log into the multiplayer server, I see my own mannequin.  This might be behind the inconsistency I see occasionally.

**Comment by RiskyKen** [comment]
Is maybe fixed, can you test dev build 586 or newer to confirm?

**Comment by DoomRater** [comment]
Attempting to join a server with that version of AW resulted in a 27MB log file on my client, filled with NPEs.  I don't think that build is working at all...

**Comment by DoomRater** [comment]
Oops, hang and crash was related to a different mod after all.  Once I resolved that my test environment shows it working on a local server.
![2020-03-19_11 55 45](https://user-images.githubusercontent.com/4010432/77086812-a4fb3380-69d8-11ea-9527-f2e9103fe497.png)

**Comment by DoomRater** [comment]
Just a bit of wonkiness now. https://imgur.com/a/ud1UJjZ

**Comment by RiskyKen** [comment]
I think that should be it.

**Comment by RiskyKen** [comment]
Will be in build 588.
