### ISSUE TITLE
[BUG] Cosmetics disappear when worn while returning from The End

### ISSUE THREAD

**Issue by DoomRater** [RiskyKen/Armourers-Workshop#286]
**Describe the bug**
Any worn items in your wardrobe will be removed when you return from an end portal back to the overworld.  They're just gone.

**To Reproduce**
1. wear item on head
2. travel to end
3. Kill Ender Dragon
4. Return home

**Additional context**
Mod version: 1.12.2-0.49.1

**Comment by DoomRater** [comment]
Additionally, all wardrobe settings are completely reset, including skin color, misc color, eye color, hair color...

**Comment by LordPhrozen** [comment]
This is fixed in an upcoming version, closing this out.
