### ISSUE TITLE
[BUG] Drop of fps

### ISSUE THREAD

**Issue by GariusSAV** [RiskyKen/Armourers-Workshop#288]
I have a drop of fps in third person view and in inventory, maybe, because of character on the screen. I tested without other mods, but it still low fps. Minecraft without all mods has normal fps.

**Comment by GariusSAV** [comment]
This is duplicate of #280

**Comment by RiskyKen** [comment]
Post a debug crash.

**Comment by GariusSAV** [comment]
How to get debug crash? I can only give some screenshots. Sorry for my incompetence. 
![javaw 2019-09-15 13-17-29-685](https://user-images.githubusercontent.com/54775022/64920099-eefe2500-d7bb-11e9-97b4-221216621d43.jpg)
![javaw 2019-09-15 13-18-19-805](https://user-images.githubusercontent.com/54775022/64920100-f291ac00-d7bb-11e9-8aa6-a5571361f09d.jpg)
![javaw 2019-09-15 13-20-00-232](https://user-images.githubusercontent.com/54775022/64920103-f4f40600-d7bb-11e9-89d9-eba432aca6c1.jpg)
![javaw 2019-09-15 13-20-26-018](https://user-images.githubusercontent.com/54775022/64920106-f7eef680-d7bb-11e9-92b7-6b6e50459eab.jpg)

**Comment by RiskyKen** [comment]
Hold F3 + C for 10 seconds.

**Comment by GariusSAV** [comment]
[crash-2019-08-25_22.33.22-client.txt](https://github.com/RiskyKen/Armourers-Workshop/files/3637266/crash-2019-08-25_22.33.22-client.txt)

**Comment by GariusSAV** [comment]
[debug.log](https://github.com/RiskyKen/Armourers-Workshop/files/3637279/debug.log)

**Comment by RiskyKen** [comment]
Looks like an issue with tlaunchers skins.

You either need to turn off tlauncher skin option.
or
Turn off AW texture painting in the config. Setting is in `config\armourers_workshop\client.cfg` change `texturePaintingType` to `-1`.
