### ISSUE TITLE
[BUG]When I switch the world, armourers doesn't display properly.

### ISSUE THREAD

**Issue by ProperSAMA** [RiskyKen/Armourers-Workshop#290]
**Describe the bug**
On my server, I wear armourers in world A. But when I teleport to world B. Armourers will disappear. I had to press "P" again to display it properly.

**To Reproduce**
1. Enter the server
2. Press "P" to wear armourers
3. Teleport to another world
4. armourers disappear

**Expected behavior**
Armourers should not disappear after teleport to another world.

**Screenshots**
Before teleport:
https://sm.ms/image/rXZStcpqRIv1nQl
After teleport:
https://sm.ms/image/QYwB5mZhDs8MFE4
Then I pressed "P".
https://sm.ms/image/z2lBKiy3GPn7eCF
They are normally displayed.
https://sm.ms/image/Ir78QWq2ATeNksD
**Debug crash log**
https://pastebin.com/T1Xup0qm

**Additional context**
I'm not sure if this will help.But when I teleport to another world.These will appear in "lastest. log"
https://pastebin.com/eMJJdxPJ

**Comment by RiskyKen** [comment]
I think this is fixed in the newest dev build, are you able to test this on your server? http://plushie.moe:8080/job/Armourers-Workshop-Dev/

**Comment by ProperSAMA** [comment]
I downloaded "Armourers-Workshop-1.12.2-0.49.1.479.jar".
It seems that the problem has been solved. Thank you for your work!
Should I wait for the next official release?Or use this version directly?

**Comment by RiskyKen** [comment]
That build should be fine to use but a public one will be out soon anyway. :man_shrugging:

**Comment by RiskyKen** [comment]
Fixed in https://github.com/RiskyKen/Armourers-Workshop/commit/73786f512b53abf97356c48965629fe58a145df6

**Comment by LordPhrozen** [comment]
As this is now fixed and in an upcoming version, I'm closing this out.
