### ISSUE TITLE
[Solved] everything works except equipments??

### ISSUE THREAD

**Issue by dokara** [RiskyKen/Armourers-Workshop#291]
it seems like armors blocks and items skins work properly
but all except weapons axes pickaxes etc
yes i did do the override's but is there a limit to how many items we can override ? 
also now we can anvil the skin in items
we can see the skinned items in our hands but can't see others one and when i press F3 i can't see mine

**Comment by dokara** [comment]
FIXED issue was Obfuscate  being  incompatible 

for who want to know if you need obfuscate or not  well you need it for mrcryfish guns vehicles etc
you don't need it for the mr cryfish furniture don't worry

**Comment by RiskyKen** [comment]
Am not able to fix this unless Obfuscate provides dev build of there mod. :(
