### ISSUE TITLE
Question: Doll at world creation

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#293]
Just a question: I've created two or three new worlds to test, I noticed AWS hadn't added a doll in my inventory. Is it holiday dependent? I'm not talking about the gift bag.

(I'm somewhat back from no playing MC for a while)

**Comment by RiskyKen** [comment]
Yes it's holiday dependent, December 1 to 31 I think. https://github.com/RiskyKen/Armourers-Workshop/blob/master/src/main/java/moe/plushie/armourers_workshop/common/holiday/ModHolidays.java#L27

They can also be made in game by dropping an anvil on a mannequin.

**Comment by RiskyKen** [comment]
also holidays are in the config changing `holiday-christmas-season-range` will allow everyone to get one at login.

**Comment by EzerArch** [comment]
> They can also be made in game by dropping an anvil on a mannequin.

Eeck, this is so anvil. (evil... anvil... get it? hmm, k, I'll retire)

Thank you. :)
