### ISSUE TITLE
Question: Any plans for 1.8?

### ISSUE THREAD

**Issue by Zariem** [RiskyKen/Armourers-Workshop#30]
Hey there :) I saw your mod on some youtube videos, and I thought it's really awesome!
I want to create a server (running on Spigot 1.8.3) and I wanted to ask whether you are planning to upgrade this mod to 1.8 (specifically 1.8.3), or if there weren't any plans yet.
Because I'd really like to be able to provide my players with some awesome armor-sets (though I don't want them to be able to craft them themselves), and your mod looks perfect as an easy-to-use and awesome armor creation tool.

**Comment by RiskyKen** [comment]
Sorry but just now I am focusing on getting the mod finished before making ports to other Minecraft versions. :(
