### ISSUE TITLE
[Suggestion] Armor that changes the size of the player

### ISSUE THREAD

**Issue by Cheezarito** [RiskyKen/Armourers-Workshop#300]
Armor that changes the overall size of the character would be cool, personally i'm trying to make a short character, but when you try and make a small model the arms look detached and the head just looks like it floats if you move. I was wondering if it'd be possible to make those types of models in game now or if not could it be possible in the future?
![2019-12-12_16 05 39](https://user-images.githubusercontent.com/40967307/70753566-abec1900-1cfa-11ea-8d1a-51b98d63c9e2.png)

**Comment by DoomRater** [comment]
This seems like the wrong mod for the job.  Gulliver Reborn accomplishes resizing the player and doesn't affect the ability to wear Armourer's Workshop items.

**Comment by LordPhrozen** [comment]
I agree here. This is out of scope.
