### ISSUE TITLE
[BUG] Override models do not work with custom NPCs

### ISSUE THREAD

**Issue by Cheezarito** [RiskyKen/Armourers-Workshop#303]
**Describe the bug**
When using custom npcs, if you use an override model on the npc will not appear on the npc itself.

**To Reproduce**
1. Go to minecraft with custom npcs and armourers workshop.
2. create an npc and an override model.
3. apply the override model onto the npc.

**Expected behavior**
The armor won't override the model.
**Screenshots**
![2020-01-03_20 48 12](https://user-images.githubusercontent.com/40967307/71758944-8ec6e800-2e6b-11ea-951c-fb3ec92c7678.png)
![2020-01-03_20 50 07](https://user-images.githubusercontent.com/40967307/71758945-92f30580-2e6b-11ea-8bf5-b688ac7c129b.png)
![2020-01-03_20 50 23](https://user-images.githubusercontent.com/40967307/71758947-98505000-2e6b-11ea-9bc7-0b35b97fd3f0.png)

**Additional context**
Using version 0.48.3

**Comment by LordPhrozen** [comment]
Less of a bug, more of an issue with how CNPCs render. You need to use a skin with that piece invisible. I personally do this by using a full transparent skin on my CNPCs, and then attach other AW skins as needed.

Be them "steve shaped" or not.
