### ISSUE TITLE
[Feature] Make skins render on NPCs (maybe configurable)

### ISSUE THREAD

**Issue by MajorBarnulf** [RiskyKen/Armourers-Workshop#304]
### My problem :
I manage a server with the mod overlord and armourers workshop, we often though about giving skinned armors to our spires but skins don't render.

(it does works with the skin container but the container doesn't protect like an armor and can't be enchanted)

### My suggestion :
We want armors with skins to render even if worn by NPCs
(maybe turned off by default but toggle-able in the config files)

Alternatively, it would be nice to be able to equip a skin on an NPC by right-clicking on them with the skin (not container) (regardless of what they currently wears) and maybe making them drop it on death.

Thank you for your consideration and have a good day.

**Comment by RiskyKen** [comment]
Have you tried the wand of style?

**Comment by MajorBarnulf** [comment]
> Have you tried the wand of style?

well, I didn't knew this existed;
I just tried, but the right-click opens the menu of the minion with this mod, even with the wand in hand, unless if I shift-rightclick, but the wand doesn't work when sneaking; 

to make it work this way, the wand of style should work while sneaking

**Comment by EzerArch** [comment]
> EDIT: the wand doesn't work at all with this mod :/ (I tried while disabling the menu of the minion)

Tried both right click and left click?

**Comment by MajorBarnulf** [comment]
> @MajorBarnulf, did you try left click?

I just did, doesn't work neither (nothing happens)

**Comment by RiskyKen** [comment]
What is the name of the mod you are trying to get it working with?

**Comment by MajorBarnulf** [comment]
> What is the name of the mod you are trying to get it working with?

the name is "Ovrelord" (the verssion is 1.12.2 - 2.4.14 (latest))
[https://www.curseforge.com/minecraft/mc-mods/overlord]
