### ISSUE TITLE
How to Export models to OBJ[Feature]

### ISSUE THREAD

**Issue by CuteCatGames** [RiskyKen/Armourers-Workshop#305]
Hi,

Me and some friends are making some models on armourers and we want to export them to either OBJ/FMTP/SMTP for modelling the small train model into a bigger train model.

Anyway of exporting models into these model types and if there is, could you explain how to do this

**Comment by RiskyKen** [comment]
I have added a small page to the wiki showing how to do this. https://github.com/RiskyKen/Armourers-Workshop/wiki/%5BGuide%5D-Exporting-Models

Please note this feature is not fully finished and some parts may not work. You must be on the newest dev version of the mod for this option to even work. You can get it from the [Discord Server](https://discord.gg/5Z3KKvU ) or [here](http://plushie.moe:8080/job/Armourers-Workshop-Dev/).
