### ISSUE TITLE
Helmet Hiding API / Interaction with RFP2

### ISSUE THREAD

**Issue by rejahtavi** [RiskyKen/Armourers-Workshop#308]
Please refer to the issue reported on RFP2 here:
[https://github.com/rejahtavi/rfp2/issues/15](https://github.com/rejahtavi/rfp2/issues/15)

RFP2 creates an "immersive first person view" where the player's 3rd-person body and animations are rendered in 1st-person view. As RFP2 calls the vanilla 3rd person renderer to achieve this, any modifications to that rendering path are also applied to RFP2. Most of the time this is a good thing, but in this case AW helmets are blocking the view when used with RFP2.

I've looked at the AW source a bit and it's a bit much to wrap my head around -- I'm not sure how I can get RFP2 to remotely request hiding AW's head slot when it is active. If you can think of a way for me to achieve this, please let me know. Otherwise, I have a crude compatibility API set up ([https://github.com/rejahtavi/rfp2/blob/master/COMPATIBILITY-API.txt](https://github.com/rejahtavi/rfp2/blob/master/COMPATIBILITY-API.txt)) that you could reference from within AW if you think that would be easier. (If you have recommendations for a better way to provide the API, I'd be open to that too.)

Thank you for your consideration.

-- Rejah <3

**Comment by RiskyKen** [comment]
Fixed in https://github.com/RiskyKen/Armourers-Workshop/commit/f0a7367a265cf50249041187f0a3b044b4848820
