### ISSUE TITLE
[Question] Is it possible to localize a skin name?

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#311]
I'm [recording a few videos with mods I have](https://youtu.be/fHHyFp23zcQ?t=643), one of them is AWS.

I normally use *.lang files in my resource pack to localize or customize names of objects in the game. But the skins are different, they are stored outside the mod directory.

**Comment by RiskyKen** [comment]
Sorry no way to do that because the players make the names. Best I can suggest is to save them with a new name in the armourer, I will maybe allow them to be renamed in the anvil.
