### ISSUE TITLE
Import from model file to server skin

### ISSUE THREAD

**Issue by mcqwy** [RiskyKen/Armourers-Workshop#312]
Hello,
Can the model be imported into the skin??
I have some obj and JSON models.
Can I directly import commands to the skin?
In other words, how can I convert JSON or obj files to armour

**Comment by RiskyKen** [comment]
There is a WIP OBJ exporter but there is no way to import models, most models can't be imported because they are not voxel.

**Comment by mcqwy** [comment]
I see your armour file is encrypted.
Can I write a skin directly by myself?
Read your armor file format.
I don't know what encryption to use.

**Comment by RiskyKen** [comment]
Not encrypted it's just a custom format https://github.com/RiskyKen/Armourers-Workshop/wiki/Armour-File-Format
