### ISSUE TITLE
[BUG] Doll can't be mined

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#313]
**Describe the bug**
Once you have placed the doll, you can no longer get it back in survival.

**To Reproduce**
1. Place a doll
2. Switch to survival
3. Use a pickaxe or the hand to mine it.
4. The doll will take 6 seconds to break. And it's gone.

**Expected behavior**
The doll pops up as an item in 1.7.10: https://youtu.be/fHHyFp23zcQ?t=817

Using Armourers-Workshop-1.12.2-0.49.1

**Comment by RiskyKen** [comment]
So it's broken in 1.12?

**Comment by EzerArch** [comment]
> So it's broken in 1.12?

`*Facepalm*` I forgot to add the version. It's 1.12.2.

**Comment by EzerArch** [comment]
Confirmed fix.
