### ISSUE TITLE
Skin-level texture for armored bodyparts

### ISSUE THREAD

**Issue by Zachs-Kappler** [RiskyKen/Armourers-Workshop#32]
I was designing and building a bodysuit for my character, when realized that anything I wanted to be part of the armor had to be a paintable block that could only be placed around bodypart. Would it be possible in a future release to paint the bodypart we build around and store that as a skin for the armor? Maybe allow placing armor blocks inside the bodypart to use them for this feature?

I know something similar is used for the vanilla and mod armors to free up the overlay layer for detail, but don't know if it can be used for something like this.

**Comment by RiskyKen** [comment]
Skin paining or smaller blocks are planned. I am just trying to think want one I want to use and how to implement it.

**Comment by RiskyKen** [comment]
Added in https://github.com/RiskyKen/Armourers-Workshop/commit/0cd42a3ca4a58b7ebf7ffde802d9fe74631aa95c
