### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Warrior155** [RiskyKen/Armourers-Workshop#320]
**Describe the bug**
1.12.2 armors workshop. If I download a skin I cannot access it. when I double click it nothing happens. Also when I create new skins I cannot save skin to skin library. My friends say its a computer issue but I tried reinstalling Minecraft and it didn't fix it. Please help. My friends use the exact same mod copy and it works fine for them. I can spam save but it's like I'm not click save at all. I haven't got it to work yet

**Comment by RiskyKen** [comment]
You must put a skin template or skin in the input slot or use the creative library. You must also type in a name if saving a skin.
