### ISSUE TITLE
Major Lag when looking at a Player

### ISSUE THREAD

**Issue by EnderTeleportation** [RiskyKen/Armourers-Workshop#323]
Is anyone experiencing MAJOR lag when looking at your/other players, it's not the complex models that are causing the lag, because even if i don't wear anything, it lags my game. I tried to put complex outfits on a MANNEQUIN, and it worked, 100 fps, but with players, no...

Is there any setting I can turn off, in order to fix this issue?

**Comment by RiskyKen** [comment]
Post a debug crash. (hold F3 + C for 10 seconds)

**Comment by EnderTeleportation** [comment]
I can't, its too long :(

**Comment by RiskyKen** [comment]
Use a site like pastebin.

**Comment by EnderTeleportation** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/11/20 3:39 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1925)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1925)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['itsCristi'/72, l='MpServer', x=-995.18, y=11.00, z=4.10]]
	Chunk stats: MultiplayerChunkCache: 4813, 4813
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-807,14,-5), Chunk: (at 9,0,11 in -51,-1; contains blocks -816,0,-16 to -801,255,-1), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 113994 game time, 25252 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 54 total; [EntitySlime['Slime'/0, l='MpServer', x=-1002.74, y=4.42, z=-62.36], EntitySlime['Slime'/1, l='MpServer', x=-1004.85, y=4.28, z=-39.77], EntityMannequin['entity.mannequin.name'/2, l='MpServer', x=-994.50, y=11.00, z=10.50], EntityMannequin['entity.mannequin.name'/3, l='MpServer', x=-996.50, y=11.00, z=13.50], EntityMannequin['entity.mannequin.name'/4, l='MpServer', x=-997.50, y=11.00, z=10.50], EntityMannequin['entity.mannequin.name'/5, l='MpServer', x=-994.50, y=11.00, z=6.50], EntityPig['Pig'/15, l='MpServer', x=-982.22, y=11.00, z=-28.21], EntityMannequin['entity.mannequin.name'/16, l='MpServer', x=-991.50, y=11.00, z=3.50], EntityMannequin['entity.mannequin.name'/17, l='MpServer', x=-991.50, y=11.00, z=7.50], EntitySlime['Slime'/18, l='MpServer', x=-995.68, y=14.00, z=60.65], EntitySlime['Slime'/20, l='MpServer', x=-971.73, y=12.17, z=-20.85], EntitySpider['Spider'/21, l='MpServer', x=-968.23, y=11.00, z=-18.89], EntityCreeper['Creeper'/22, l='MpServer', x=-963.86, y=11.00, z=-2.28], EntitySlime['Slime'/26, l='MpServer', x=-958.18, y=4.12, z=-55.79], EntitySlime['Slime'/27, l='MpServer', x=-945.06, y=11.00, z=-19.09], EntitySlime['Slime'/28, l='MpServer', x=-952.67, y=11.00, z=-27.93], EntityWolf['Wolf'/29, l='MpServer', x=-936.55, y=11.00, z=-15.49], EntityItem['item.item.bone'/30, l='MpServer', x=-944.05, y=11.00, z=-14.37], EntitySlime['Slime'/31, l='MpServer', x=-955.97, y=12.17, z=-11.51], EntitySlime['Slime'/36, l='MpServer', x=-938.34, y=4.00, z=-48.12], EntityItem['item.item.arrow'/37, l='MpServer', x=-943.80, y=11.00, z=-14.26], EntitySlime['Slime'/38, l='MpServer', x=-923.53, y=11.00, z=-27.20], EntityPig['Pig'/39, l='MpServer', x=-933.79, y=11.00, z=17.17], EntityPig['Pig'/42, l='MpServer', x=-927.32, y=11.00, z=-27.79], EntityChicken['Chicken'/43, l='MpServer', x=-916.29, y=4.00, z=-47.33], EntityCow['Cow'/44, l='MpServer', x=-917.48, y=4.00, z=-44.48], EntityCow['Cow'/45, l='MpServer', x=-915.57, y=11.00, z=-22.80], EntityPig['Pig'/46, l='MpServer', x=-926.76, y=11.09, z=47.29], EntitySlime['Slime'/191, l='MpServer', x=-1070.93, y=4.00, z=18.45], EntitySpider['Spider'/77, l='MpServer', x=-1041.23, y=4.00, z=-17.77], EntityItem['item.item.arrow'/78, l='MpServer', x=-1047.76, y=4.00, z=-17.86], EntitySlime['Slime'/80, l='MpServer', x=-1066.94, y=4.00, z=-10.87], EntitySlime['Slime'/86, l='MpServer', x=-1045.93, y=4.00, z=-37.54], EntitySlime['Slime'/87, l='MpServer', x=-1050.21, y=4.28, z=-43.96], EntitySlime['Slime'/89, l='MpServer', x=-1007.40, y=12.25, z=52.71], EntitySlime['Slime'/90, l='MpServer', x=-1053.08, y=5.25, z=-29.78], EntityCreeper['Creeper'/91, l='MpServer', x=-1029.50, y=11.00, z=73.50], EntitySlime['Slime'/92, l='MpServer', x=-1019.92, y=5.25, z=-72.44], EntitySlime['Slime'/94, l='MpServer', x=-1069.92, y=4.00, z=-46.74], EntityWolf['Wolf'/95, l='MpServer', x=-1002.69, y=11.00, z=43.43], EntityItem['item.item.arrow'/97, l='MpServer', x=-1023.33, y=11.00, z=18.80], EntityItem['item.item.bone'/98, l='MpServer', x=-1022.41, y=11.00, z=18.92], EntityItem['item.item.arrow'/99, l='MpServer', x=-1021.87, y=11.00, z=31.20], EntityItem['item.item.arrow'/100, l='MpServer', x=-1013.23, y=11.00, z=28.69], EntityItem['item.item.bone'/101, l='MpServer', x=-1012.72, y=11.00, z=28.36], EntitySlime['Slime'/102, l='MpServer', x=-1027.62, y=11.00, z=16.21], EntitySlime['Slime'/104, l='MpServer', x=-1045.43, y=4.00, z=8.59], EntitySlime['Slime'/105, l='MpServer', x=-1017.40, y=11.00, z=-0.05], EntitySlime['Slime'/106, l='MpServer', x=-1042.93, y=5.25, z=10.26], EntityWolf['Wolf'/107, l='MpServer', x=-1032.55, y=11.00, z=21.63], EntitySlime['Slime'/110, l='MpServer', x=-1073.83, y=4.50, z=28.38], EntityWitch['Witch'/111, l='MpServer', x=-1051.39, y=4.00, z=1.29], EntitySlime['Slime'/112, l='MpServer', x=-1045.63, y=4.50, z=13.29], EntityPlayerSP['itsCristi'/72, l='MpServer', x=-995.18, y=11.00, z=4.10]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105689648 bytes (100 MB) / 801009664 bytes (763 MB) up to 7261650944 bytes (6925 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx6937M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version       | Source                               | Signature                                |
	|:------ |:-------------------------- |:------------- |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2        | minecraft.jar                        | None                                     |
	| LCHIJA | mcp                        | 9.42          | minecraft.jar                        | None                                     |
	| LCHIJA | FML                        | 8.0.99.99     | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2838  | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | armourers_workshop         | 1.12.2-0.50.1 | Armourers-Workshop-1.12.2-0.50.1.jar | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4           | tlskincape_1.12.2-1.4.jar            | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Armourer's Workshop: 
		Baking Queue: 9
		Request Queue: 0
		Texture Paint Type: TEXTURE_REPLACE
		Multipass Skin Rendering: true
	Render Layers:
		 Render Class: net.minecraft.client.renderer.entity.RenderPlayer
			moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
			net.minecraft.client.renderer.entity.layers.LayerBipedArmor
			net.minecraft.client.renderer.entity.layers.LayerArrow
			net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
			net.minecraft.client.renderer.entity.layers.LayerCape
			net.minecraft.client.renderer.entity.layers.LayerCustomHead
			net.minecraft.client.renderer.entity.layers.LayerElytra
			net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
			net.optifine.player.PlayerItemsLayer
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
		 Render Class: net.minecraft.client.renderer.entity.RenderPlayer
			moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
			net.minecraft.client.renderer.entity.layers.LayerBipedArmor
			net.minecraft.client.renderer.entity.layers.LayerArrow
			net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
			net.minecraft.client.renderer.entity.layers.LayerCape
			net.minecraft.client.renderer.entity.layers.LayerCustomHead
			net.minecraft.client.renderer.entity.layers.LayerElytra
			net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
			net.optifine.player.PlayerItemsLayer
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
			moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ItemBound+v1.8.zip, Sunete, Passenger plane 1.12  - By Gshn28 (RESOURCE PACK).zip
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz

(This one?)

**Comment by V972** [comment]
`tlauncher_custom_cape_skin` -- **this** is the source of the problem, caused by TLaucher.
More specifically, it's fake version, 2.x, that you're using.

1. Delete `tlskincape_1.12.2-1.4.jar` from your game directory;
2. Delete TLaucher and it's leftover files;
3. Check your PC with antivirus (I'm not joking);

"But I need a launcher to play"
Sure, for example, you can always switch to original TL:
- [Windows version](https://tlaun.ch/latest/exe) (Windows 7+, needs .NET)
- [Cross-platform version](https://tlaun.ch/latest/jar) (any OS, works with Java 8+)

They also have a [Discord server](https://discord.gg/8vfGByE) if you have any questions.

And if want to know what the heck is with this fake version and why it's fake then [here's the article](https://minecraftmain.ru/2018/02/tlauncher-story) about it and here is [google-translated version](https://translate.google.fr/translate?hl=ru&tab=rT&authuser=0&sl=ru&tl=en&u=https%3A%2F%2Fminecraftmain.ru%2F2018%2F02%2Ftlauncher-story).

**Comment by EnderTeleportation** [comment]
That can't be :(, i got it from the [official page](https://tlauncher.org/en/).

**Comment by V972** [comment]
.org isn't the official page.
It's those very people who stole the TL and made it into block-chain mining, account stealing, money sucking (both from players and what's more -- from server owners) piece of software, while abandoning the original dev (who initially helped THEM not to disappear) and making his life hard in every possible way.
Their crappy skin system is what breaks not just AW, but many other mods.

And it's not just about Minecraft, they tried similar scheme with Terraria launcher.

It's all in the article, with screenshots, links etc.
I gave you everything I could. It's your choice to believe me or not, but it's also your obligation to deal with the consequences of 2.x TL's presence in you system -- from not working mods to data theft.

**Comment by EnderTeleportation** [comment]
...woooow...     ...ok... thanks a lot! Do they have an official page anymore?

**Comment by V972** [comment]
They have, but it's used mostly as a repo and their base of operations is situated in the Russian social network. (Because original dev and staff are Russian-speaking). [Here it is](https://tlaun.ch), if you're still interested tho.

For English speaking folks they use Discord server I linked above.
