### ISSUE TITLE
[BUG] Compatibility with obfuscate

### ISSUE THREAD

**Issue by Hydraheads** [RiskyKen/Armourers-Workshop#325]
**Describe the bug**
Having both mods installed, items with skins do not render held in the players hand in third person.

**To Reproduce**
1. install both obfuscate (coremod for mr crayfish vehicle mod, etc) and armour's workshop
https://www.curseforge.com/minecraft/mc-mods/obfuscate
2. Hit F5 while holding an item with skins

**Expected behavior**
The item actually rendering

**Screenshots**
N/A

**Debug crash log**
N/A

**Additional context**
Obfuscate modifies rendering of players. However, it does not actually do anything that is visually different with the player model, so there may be a way to fix this? I have asked Crayfish and he just shrugged it off, but both mods (this and vehicles) are beautiful and it'd be awesome to have both on a server.

**Comment by RiskyKen** [comment]
This is a known bug, I can't do anything about it unless Obfuscate makes an API and some deobf jars. It can be fixed just now but that would make Obfuscate a hard dependency, not something I am willing to do.
