### ISSUE TITLE
[BUG] Invalid Jar File

### ISSUE THREAD

**Issue by Qobu** [RiskyKen/Armourers-Workshop#329]
While trying to download the mod and get it all together it but I keep on getting the same message in chat. "Armourer's Workshop has detected an invalid jar file click here" (https://www.curseforge.com/minecraft/mc-mods/armourers-workshop) Then it goes on to say stuff about mod reposts. The problem is that I've already downloaded it from curseforge but it still happens. I've searched around and cant find anything. Help would be greatly appreciated.

**Comment by SownAthlete** [comment]
same error here

**Comment by DoomRater** [comment]
AW's jar file is notorious about what the name of the JAR file should be.  Any changes to the name of the file, even a superfluous (1) tagged on the end of it, will trigger the repost warning.  Make sure the file name has not changed from what you downloaded it from Curse.
