### ISSUE TITLE
armor not showing up

### ISSUE THREAD

**Issue by ghostbuster3210** [RiskyKen/Armourers-Workshop#33]
i like the mod, it worked great the first time i used it, but the next time i opened minecraft  it wouldnt work. the blocks, tools, and gui's all work, but the armor wont appear when i put it on.  the sword works fine still,

but could someone please help?

**Comment by RiskyKen** [comment]
What version of the mod are you using?
What other mods do you have installed?

**Comment by ghostbuster3210** [comment]
i have armourers workshop
carpenters blocks
coroutil
crystalpowers ( a mod i made myself )
galacticraft
and malisisdoors,

but  would those even matter? i had them all installed when i  first used the mod and it worked fine..

**Comment by RiskyKen** [comment]
What version of Armourer's Workshop?

**Comment by ghostbuster3210** [comment]
Armourers-Workshop-1.7.10-0.32.0.83

**Comment by RiskyKen** [comment]
Did you update from an older version when it stopped working?
Are the skins rendering in inventory slots?
Have you tried loading new the skins out of the library?

**Comment by ghostbuster3210** [comment]
yes, i've tried everything, they render in the inventory slots.  didnt update ( i hardly ever do unless its ABSOLUTELY necessary ) i tried  loading them from the library.

the sword still works . so thats one good thing

**Comment by ghostbuster3210** [comment]
i'm starting up minecraft now. i'll check if it works

**Comment by ghostbuster3210** [comment]
started it up, the armors works. sorry to bother you.

but everything your doing in this mod.. you're doing a good job of it.
keep doing what you do best dude.

**Comment by RiskyKen** [comment]
There is a very rare bug that sometimes stop the skins from rendering on the player may have been that. :S

**Comment by ghostbuster3210** [comment]
Uh I'm not Ken,  i'm just some random guy who played the mod,  That comment
is 3 years old
