### ISSUE TITLE
[BUG] [1.12.2] Skins for weapons and tools from mods

### ISSUE THREAD

**Issue by LoopRich161** [RiskyKen/Armourers-Workshop#344]
**Describe the bug**
If you put a skin on a weapon and pick up a diamond sword or a shovel, you will see the skin that is selected.
If you put on a skin and pick up weapons or tools from the mods, then the skins will not be visible, but the usual weapons from the mod will be visible.
Please correct this, as there is no point in skins for weapons and tools.
But everything is fine with the armor, it works great

**Comment by DoomRater** [comment]
Armourer's Workshop does not know by default which skin to apply to modded tools.  Also, some modded items are more than one tool at a time- the intended solution is to tell Armourer's which skin to apply to the tool yourself using the following command: `/armourers setItemSkinnable <add|remove>`

**Comment by RiskyKen** [comment]
Yes what DoomRater said, there is also a guide on the wiki https://github.com/RiskyKen/Armourers-Workshop/wiki/%5BGuide%5D-Skinning-Modded-Items
