### ISSUE TITLE
Player-held skins disappear randomly. [BUG]

### ISSUE THREAD

**Issue by VanguardDawn** [RiskyKen/Armourers-Workshop#348]
After a seemingly random amount of time of using the mod, skins will fail to load when used by players. This affects both singleplayer and multiplayer. I am using MultiMC, playing on version 1.12.2. The version of Armourer's Workshop used is 1.12.2-0.50.5. I have found no method to reproduce this, nor have I found one to resolve it. Attached are screenshots of a player, a mannequin, and an NPC from Noppes' Custom Npcs mod all attempting to use the same skin. If need be, I will post my mod list in case any incompatibilities are present that I am unaware of.
![2020-10-08_19 34 48](https://user-images.githubusercontent.com/29845489/95535469-63929b80-099d-11eb-8af6-955e31121e5a.png)
![2020-10-08_19 34 53](https://user-images.githubusercontent.com/29845489/95535471-64c3c880-099d-11eb-9363-eb74ce17f8f0.png)

**Comment by RiskyKen** [comment]
Sorry for the delay.

Can you post a debug crash. (hold f3 + c for 10 seconds)

**Comment by VanguardDawn** [comment]
[Here's the crash log.](https://pastebin.com/UGgE7S37) The only method I've ever found to fix this is by creating an entirely new instance, but I don't really want to do that every week or two. I'm honestly hoping I'm doing something wrong somewhere so it can be fixed easily.

**Comment by RiskyKen** [comment]
The mod is not compatible with obfuscate. Am guessing that's what the issue is.

**Comment by VanguardDawn** [comment]
Disabled Obfuscate (and MrCrayfish's Vehicle Mod, since Obfuscate is the core for it) and the skin loaded perfectly fine. I can't begin to thank you enough for helping me out. Armourer's Workshop not working properly was the sole factor in my losing motivation to play Minecraft.
