### ISSUE TITLE
Mannequin Weapon Rendering Issue

### ISSUE THREAD

**Issue by LordEpos** [RiskyKen/Armourers-Workshop#35]
I've already explained this issue here (Third post from top as of right now):
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2309193-wip-alpha-armourers-workshop-weapon-armour-skins?page=22
But wanted to be sure that it would come to your attention. That's really all I'm writing this for.

**Comment by RiskyKen** [comment]
Sorry just been really busy. Will fix it when I can. :)
