### ISSUE TITLE
[BUG] Error message in chat every 30 seconds

### ISSUE THREAD

**Issue by DevLarge** [RiskyKen/Armourers-Workshop#357]
![image](https://user-images.githubusercontent.com/71059839/108634021-d184be80-7477-11eb-9700-427e117f47cf.png)

Annoying message pops up in chat every minute or so. It pops up for all players. 

![image](https://user-images.githubusercontent.com/71059839/108634039-fb3de580-7477-11eb-9ff1-827790925111.png)

My version ^

**Comment by DoomRater** [comment]
The file has been renamed from whatever it is actually expecting.  Pretty sure that's what's happened.
