### ISSUE TITLE
[BUG]A compatibility issue with Oculus on 1.19.2

### ISSUE THREAD

**Issue by ghost** [RiskyKen/Armourers-Workshop#408]
**Describe the bug**
A black screen issue will happen if you place skinnable block in the End dimension when shaders are enabled.

**To Reproduce**
1. Install "oculus-mc1.19.2-1.6.4"(the latest version)
2. Enable shaders
3. Enter the End
4. Place a skinnable block
5. Black screen issue appears

You can still operate the game after this problem happens,but the game will display nothing.

**Screenshots**
https://github.com/Armourers-Workshop/Armourers-Workshop/assets/129179911/87562b88-20ae-4869-958c-0043a06ef38a

**Comment by SAGESSE-CN** [comment]
are your using what's shaders pack?

i tested BSL is normal.

**Comment by SAGESSE-CN** [comment]
try 2.0.0-beta.24

**Comment by SAGESSE-CN** [comment]
i need more details, possible in [qq](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=o2L0-5lABPgFum97lC4nXmtW5TMZ_R76&authKey=HIGluqp1xWMAjPKc5%2BZ7SMh5PwIY%2FhZildDCWCcmoAovnBfGw%2B%2FpIiLapE50Y7m%2F&noverify=0&group_code=540297010) or [discord](https://discord.gg/5Z3KKvU) to discuss?
