### ISSUE TITLE
[Feature Request?] Ambidextrous mannequins?

### ISSUE THREAD

**Issue by alucard87pl** [RiskyKen/Armourers-Workshop#42]
It'd be awesome if I could place a skinned sword or bow into either hand of a mannequin. I'm currently working on a build where I have mannequins holding long staves and they are standing on two sides of a walkway. the mannequin on the right side should be able to hold the staff in its left hand for symmetry :)

**Comment by RiskyKen** [comment]
This was a bug and has been fixed. It will be in the next build.

https://github.com/RiskyKen/Armourers-Workshop/commit/2e4fda11c3bd919e5e55f5f73b8077d78a313e47

**Comment by alucard87pl** [comment]
My Botania temple thanks you :)
