### ISSUE TITLE
TMI stopping skin types dropdown menu working

### ISSUE THREAD

**Issue by Pokemonmaster826** [RiskyKen/Armourers-Workshop#45]
I cant change the equipment to anything all i have is the head option. PLZ FIX THIS!!

**Comment by RiskyKen** [comment]
Press the down arrow next to the head option. The other skin types should show up in a list.

**Comment by RiskyKen** [comment]
Are you using TMI?

**Comment by Pokemonmaster826** [comment]
yes *faceplams*

**Comment by Pokemonmaster826** [comment]
Oh you just changed it.

**Comment by Pokemonmaster826** [comment]
Thanks ;)

**Comment by Pokemonmaster826** [comment]
Also. Let me know when you fix it! :)

**Comment by RiskyKen** [comment]
GitHub should send you an email when this issue is closed.
