### ISSUE TITLE
Colored lights core issues

### ISSUE THREAD

**Issue by KyeDuo** [RiskyKen/Armourers-Workshop#46]
When I use CLC and this mod, the armor's don't render right:
the chest armor only renders the left arm.
Glowing armor blocks don't look quite right.
Uncolored armor blocks will take on the color of player's model wherever the block is located and does pick up the skin color if the option to show skin is active.
I know CLC's mod author has quit, but the code is out there and the mod is usable despite the issues.

**Comment by RiskyKen** [comment]
I may be able to fix the coloured lighting issue, will take a bit of time. I have move the smart moving bug into it's own issue.
