### ISSUE TITLE
[BUG] models COVERING my screen when shaders are enabled...

### ISSUE THREAD

**Issue by ayblxo** [RiskyKen/Armourers-Workshop#465]
yeah no for some reason whenever i turn shaders on, everything that has to do with armourers workshop that is in my view, completely covers my screen. is this common? is it because of my shader pack? i'm using the Insanity Shaders, on MC 1.20.1 Fabric, and using iros/sodium/etc i tried looking through the issues page but couldn't find anything exactly like this. hopefully someone can help

**Comment by ayblxo** [comment]
![image](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/170896372/6cf8e8c9-ff11-4be2-b4ed-6d91fe7182f9)
this

**Comment by SAGESSE-CN** [comment]
mod versions?

**Comment by ayblxo** [comment]
> mod versions?

the armorer's workshop version is 3.0.0
does the mod need to be on the latest for it to work with shaders?

**Comment by SAGESSE-CN** [comment]
fixed in 3.0.0-dev12 in the discord

**Comment by ayblxo** [comment]
> fixed in 3.0.0-dev12 in the discord

is there a link to the discord?

**Comment by SAGESSE-CN** [comment]
https://discord.gg/5Z3KKvU

**Comment by ayblxo** [comment]
i can't find whatever file that is in the discord, i was guessing it was an update but i'm not so sure now

**Comment by SAGESSE-CN** [comment]
fixed in next 3.0 release
