### ISSUE TITLE
Npc incompatability in multiplayer[BUG]

### ISSUE THREAD

**Issue by HeartSteeler** [RiskyKen/Armourers-Workshop#466]
When using custom npc the style wand works fine with putting skins onto npcs but when i tried moving the npc to my multiplayer server the skins stop showing on the npc (game version 1.16.5)

1. Download Custom npcs mod and Armorers workshop
2. Try to put a skin on an npc in a multiplayer server
3. See error

**Expected behavior**
for the skins to stay displayed on the npc

**Comment by SAGESSE-CN** [comment]
aw version and cncpc version?

**Comment by SAGESSE-CN** [comment]
we required CustomNPCs-1.16.5.20220728snapshot and latest.

you can found  snapshot version in the CNPC discord.
