### ISSUE TITLE
Bliss Shaders incompat

### ISSUE THREAD

**Issue by KDFireHero** [RiskyKen/Armourers-Workshop#467]
**Describe the bug**
when using Bliss shaders all tools modified by AW skins cover half the screen

**Screenshots**
![2024-06-06_09 41 44](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/143463953/9fad79fe-ad6b-48b4-928c-e88bb6bbf2b9)
![2024-06-06_09 41 53](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/143463953/7cd53236-0419-4de8-bfb9-b7176efbeb83)
![2024-06-06_09 41 56](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/143463953/991629c9-9c1b-4a66-a6cc-b3bf9c95f616)

**Debug crash log**
[latest.log](https://github.com/user-attachments/files/15631116/latest.log)

with Distant Horizons

**Comment by KDFireHero** [comment]
it is fixed when shaders is disabled

**Comment by SAGESSE-CN** [comment]
already fixed in 2.1.4
