### ISSUE TITLE
compatability request for 1.16.5 cnpc[Feature]

### ISSUE THREAD

**Issue by HeartSteeler** [RiskyKen/Armourers-Workshop#468]
inability to show skins on npcs in  Custom npc version  1.16.5.20220515

would be cool to be able to use the custom aw skins on the bosses and npcs of our project

as of the moment all the possible version of cnpc that are compatible with aw are different game versions and or snapshot versions which we cant use on the project server

**Comment by SAGESSE-CN** [comment]
we required CustomNPCs-1.16.5.20220728snapshot and latest.

This is a cnpc bug, and have been fixed.

you can found snapshot version in the CNPC discord.
