### ISSUE TITLE
Problems and solutions for the appearance of some functional blocks 关于部分功能方块的外观问题及解决方案

### ISSUE THREAD

**Issue by ghost** [RiskyKen/Armourers-Workshop#470]
> English

As a kind of _"exquisite and practical decoration"_, some functional blocks in Armourer's Workshop always stand out from other indoor furnishings - they are too short, and even normal chairs are not much shorter than those tabletops! [See 01. png] Plus, there's also the issue of Z-fighting in the `skinning-table` ~and the mystery of "SB" texture in `advanced-skin-builder`  ...~ It's time to clean up these old bugs!

MySolution: [BlockbenchModels.zip](https://github.com/user-attachments/files/16127199/BlockbenchModels.zip)
Before modification: [see 02. png]
After modification: [see 03. png]

> 简体中文

作为一种“精致而实用的装饰物”，时装工坊的部分功能方块总是与室内的其它陈设格格不入——它们太矮了，甚至正常的椅子都比桌面矮不了多少！[见01.png] 此外，这里还有`镶嵌工作台`的深度冲突问题、~`高级时装工作台`的“SB”材质之谜……~ 是时候来清扫一下这些陈年臭虫了！

我认为的解决方案：[BlockbenchModels.zip](https://github.com/user-attachments/files/16127199/BlockbenchModels.zip)

改动前：[见02.png]
改动后：[见03.png]

> Attachments 附件

![01](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/79563897/517d0c02-e57d-481d-9111-72aba52dcf04)
⬆01.png (chair from MrCrayfish's Furniture Mod)
![02](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/79563897/6cfa0f53-0c76-4988-8b18-68a6a360862b)
⬆02.png  : \
![03](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/79563897/fa80ee12-e6c6-4cc4-a3cc-367a815a33ad)
⬆03.png  : )
[BlockbenchModels.zip](https://github.com/user-attachments/files/16127199/BlockbenchModels.zip)
⬆modified block models **(CONTENT FOR LEARNING AND REFORENCE ONLY)**

**Comment by SAGESSE-CN** [comment]
可以麻烦你再提供一个高级时装台的吗

**Comment by SAGESSE-CN** [comment]
https://github.com/SAGESSE-CN/Armourers-Workshop/blob/develop/common/src/main/resources/assets/armourers_workshop/models/block/advanced-skin-builder.json

这个是目前的版本，非临时的

**Comment by ghost** [comment]
[advanced-skin-builder.zip](https://github.com/user-attachments/files/16137050/advanced-skin-builder.zip)
交差！（手动狗头
不过我总觉得高级时装工作台应该大致长这个样子⬇（一个带有四块全面屏的酷炫投影装置）
![Screenshot](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/79563897/f1ff29fb-b982-4051-bc9c-11cb7b3b119d)
毕竟它可以在空中投影模型、~通过震撼我妈一百年的天顶星科技~把.bbmodel带入游戏、还有蕴含着无限可能的大香蕉……此外，作为比普通时装工作台更加高级的存在，一个简易的小木桌貌似确实有些对不起它的名号🤔

> 我的想法

将具有小木桌类模型的功能方块用于对时装的后期处理（如时装的下载、储存、应用），因为相关操作可以直接在GUI内完成而不需要开阔场地；考虑到制作编辑时装对场地的要求，制作时装制作编辑类的功能方块（如时装工作台、调色器）时使用其它模型，让玩家明白它们的特殊性，以及不会傻乎乎地把它们放在狭小的室内。

或者，把目前的这个高级时装工作台模型用于”对生存玩家友好的时装工作台“，让生存玩家可以在GUI内直接使用方块搭建时装，就像blockbench一样。~如果我没记错的话这又是一个上古神坑（~

**Comment by SAGESSE-CN** [comment]
你也可以提供一个你的方案，那个高级时装台子还是我还一位群友做的 只能说比sb好。
高级时装台的作用更多的是组装，例如多部件拼装，平移旋转缩放，动画设置，一些其他参数设置

**Comment by SAGESSE-CN** [comment]
人个感觉拉高之后桌子的腿有点细了不太协调?

**Comment by ghost** [comment]
[BlockbenchModelsV2.zip](https://github.com/user-attachments/files/16157956/BlockbenchModelsV2.zip)
如你所愿 ![R-C2](https://github.com/Armourers-Workshop/Armourers-Workshop/assets/79563897/e82cba3e-964f-40ac-87f8-aa7da2614568)
~以后打死也不布线力~

**Comment by SAGESSE-CN** [comment]
好！！ 下个版本换上！

但你给的新版本高级时装台好像没有纹理?

**Comment by ghost** [comment]
呃，，，那个还是超级半成品，而且我现在愈发确信这个高级时装工作台就是一个带有世界投影功能的类blockbench编辑器，所以投影和交互终端的外观表现应该是重点，估计后面还得大改一下。（就算最后没搞出来，我们也能获得一台酷炫的全息投影仪，至少😏）PS：我这几天在外面，估计是改不了模型了 :(

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://github.com/user-attachments/assets/7578b488-d748-4aea-9c3d-db8e99faf1ea">

**Comment by SAGESSE-CN** [comment]
relaesed in the 3.0.0-beta.12
