### ISSUE TITLE
[BUG] I use a shader but there is a display bug

### ISSUE THREAD

**Issue by luluryback** [RiskyKen/Armourers-Workshop#471]
I use embedium and oculuse for my shaders but there is a problem which displays the blocks in front of me is in me
![Capture d'écran 2024-07-11 213945](https://github.com/user-attachments/assets/dc159528-efd3-4821-a98c-aacc04c15f20)
![Capture d'écran 2024-07-11 214001](https://github.com/user-attachments/assets/55e05ad9-7f68-4dc4-80e9-5bd0c065acd3)

**Comment by SAGESSE-CN** [comment]
aw mod version

**Comment by SAGESSE-CN** [comment]
pls use latest version.
