### ISSUE TITLE
[CRASH][1.21neoforge_client]MixinTransformerError

### ISSUE THREAD

**Issue by ootwclyhe** [RiskyKen/Armourers-Workshop#472]
**To Reproduce**
Steps to reproduce the crash:
1. onstart crash

**Crash log**
https://pastebin.com/JLGHw3Jf

**Screenshots**
noscreen

**Additional context**
seem like this one：
https://github.com/TeamLapen/Vampirism/issues/1394
https://github.com/TeamLapen/Vampirism/commit/81116b828916c0ef856d536f5857890c00d56195

**Comment by SAGESSE-CN** [comment]
no same, because the sponge, remove a forge field

**Comment by SAGESSE-CN** [comment]
oh wait, maybe is forge removed

**Comment by SAGESSE-CN** [comment]
fixed in the 3.0.0-dev.72

**Comment by ootwclyhe** [comment]
dev.72在哪，discord？

**Comment by SAGESSE-CN** [comment]
yep
