### ISSUE TITLE
Less a [BUG], more of a question I cannot get an answer to in Discord

### ISSUE THREAD

**Issue by JaceRidley** [RiskyKen/Armourers-Workshop#473]
Hello! 
I hope this is the proper place to ask this. I need a little "tech support" and I'd be appreciative if someone could answer. 

I'm trying to use the mannequins on a larger scale. Like... Kaiju scale. Maybe a little smaller. But with scaling in the game now(Armor Poser scaling them up by 10x, I believe, for instance), I was hoping someone could help me with what commands I would use to increase the Mannequin scale size, since they apparently count as Entities. 

I'm aware of the Giant size mannequins that are like 3x the size, and if that's the only option, then okay. I'm just hoping someone can tell me a way to make them even larger. 

Thanks

**Comment by SAGESSE-CN** [comment]
1.16-1.21
`/data modify entity <uuid> Scale set value 10f`

1.16-1.20
`/give @p armourers_workshop:mannequin{EntityTag:{Scale:10f}}`

1.21
`/give @p armourers_workshop:mannequin[minecraft:entity_data={id:"armourers_workshop:mannequin",Scale:10f}]`
