### ISSUE TITLE
Non-op players can't use armorer workshop in server

### ISSUE THREAD

**Issue by Valentin3832** [RiskyKen/Armourers-Workshop#474]
So, i play in a server, we use armorer workshop, and as the title suggests, non op players cannot use the mod at all, they cannot, for example, open their wardrobes, or interact with the skin library, etc, we tried to check if it was a plugin issue but apparently it wasn't, what could be the issue?

**Comment by SAGESSE-CN** [comment]
forge 1.16+ use permission system. but bukkit sever change the default permission to op, so you need use lp or disabled permission check in the config 

https://github.com/Armourers-Workshop/Armourers-Workshop/wiki/Permission-System
