### ISSUE TITLE
[BUG]advanced skin builder invisible left pane AND unable to right click on items in upper right list

### ISSUE THREAD

**Issue by DougStoker** [RiskyKen/Armourers-Workshop#475]
<img width="1437" alt="Screen Shot 2024-08-12 at 4 29 22 PM" src="https://github.com/user-attachments/assets/7272ae76-eeeb-4c23-b884-8af60b33edb2">
**Describe the bug**
advanced skin builder invisible left pane AND unable to right click on items in upper right list
tested on 1.20.1 forge and 1.18.2 fabric
on macos

**To Reproduce**
open advanced skin builder

**Expected behavior**
behavior like in the tutorial page

**Debug crash log**
[Linking a debug crash log can help track down bugs. Holding down F3 + C for 10 seconds in game will force the a crash making a debug crash log. Please link your log using a site like https://pastebin.com/](https://pastebin.com/bHsv3BYT)

**Additional context**

**Comment by SAGESSE-CN** [comment]
mod version？

**Comment by DougStoker** [comment]
3.0.0-beta.12

**Comment by SAGESSE-CN** [comment]
> 3.0.0-beta.12

Impossible, pls retry with beta.13

**Comment by DougStoker** [comment]
ok it does seem to work on that version
