### ISSUE TITLE
Mannequin[CRASH]

### ISSUE THREAD

**Issue by KingForeverP4** [RiskyKen/Armourers-Workshop#476]
Steps to reproduce the crash:
1. Go to the creative tab
2. pick the mannequin in your hand
3. crashes

**Crash log**
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-08-14 17:35:38
Description: Unexpected error

java.lang.IllegalStateException: Not building!
	at net.minecraft.class_287.method_60802(class_287.java:76)
	at net.minecraft.class_287.method_60805(class_287.java:95)
	at net.minecraft.class_287.method_22912(class_287.java:156)
	at net.minecraft.class_4588.method_22918(class_4588.java:532)
	at net.minecraft.class_4588.method_56824(class_4588.java:125)
	at net.minecraft.class_761.method_3278(class_761.java:2203)
	at net.minecraft.class_265.method_1106(class_265.java:92)
	at net.minecraft.class_251.method_1052(class_251.java:181)
	at net.minecraft.class_251.method_1064(class_251.java:129)
	at net.minecraft.class_265.method_1104(class_265.java:92)
	at net.minecraft.class_761.method_3291(class_761.java:2194)
	at net.minecraft.class_761.method_22712(class_761.java:2147)
	at net.minecraft.class_761.method_22710(class_761.java:1190)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_60802(class_287.java:76)
	at net.minecraft.class_287.method_60805(class_287.java:95)
	at net.minecraft.class_287.method_22912(class_287.java:156)
	at net.minecraft.class_4588.method_22918(class_4588.java:532)
	at net.minecraft.class_4588.method_56824(class_4588.java:125)
	at net.minecraft.class_761.method_3278(class_761.java:2203)
	at net.minecraft.class_265.method_1106(class_265.java:92)
	at net.minecraft.class_251.method_1052(class_251.java:181)
	at net.minecraft.class_251.method_1064(class_251.java:129)
	at net.minecraft.class_265.method_1104(class_265.java:92)
	at net.minecraft.class_761.method_3291(class_761.java:2194)
	at net.minecraft.class_761.method_22712(class_761.java:2147)
	at net.minecraft.class_761.method_22710(class_761.java:1190)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 148.186s
	Wall uptime: 128.494s
	High-res time: 122.229s
	Client ticks: 2186 ticks / 109.300s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['KingForever_P4'/1, l='ClientLevel', x=0.50, y=-60.00, z=-9.50]]
	Chunk stats: 1024, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 443 game time, 443 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, armourers_workshop, betterconfig, bridgingmod, cherishedworlds, clientcommands, cloth-config, colorfulhearts, continuity, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, held-item-info, indium, inventoryprofilesnext, libipn, lighty, litematica, lithium, malilib, no_despawn, no_fog, notebook, shulkerboxtooltip, sodium, toggleableitemframes, visuality, wurst, file/Mace3D.zip, file/Simple Grass Flowers v1.8.1.zip, file/enchant icons 1.21 v1.3.zip, file/animated-items-1_21 - 1_3_1.zip, file/Watch of Undying.zip, file/coração roxo.zip, file/Scythe from RogueCraft.zip, file/Animated-Ore+0.5.2-1.16.5-1.21.zip, file/Glowing-OF_v0.4.1-mc1.21.zip, dynamic/armourers_workshop

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 173896192 bytes (165 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5244
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 30.0.100.9864
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 32891.33
	Virtual memory used (MiB): 27500.69
	Swap memory total (MiB): 16728.03
	Swap memory used (MiB): 1913.83
	Space in storage for jna.tmpdir (MiB): available: 48317.38, total: 487497.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 48317.38, total: 487497.00
	Space in storage for io.netty.native.workdir (MiB): available: 48317.38, total: 487497.00
	Space in storage for java.io.tmpdir (MiB): available: 48317.38, total: 487497.00
	Space in storage for workdir (MiB): available: 48317.38, total: 487497.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		armourers_workshop: Armourer's Workshop 3.0.0-beta.13
		bridgingmod: Bridging Mod 2.4.0+1.21
		cherishedworlds: Cherished Worlds 10.0.1+1.21
		clientcommands: Client Commands 2.9
			betterconfig: BetterConfig 1.3
			clientarguments: clientarguments 1.9
			net_fabricmc_mapping-io: mapping-io 0.5.1
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		colorfulhearts: Colorful Hearts 10.0.0
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		continuity: Continuity 3.0.0-beta.5+1.21
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		fabric-api: Fabric API 0.100.4+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.15+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.2+78017270d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.9+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.11+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.23+78017270d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.80+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 7.0.0
		held-item-info: Held Item Info 1.7.0
		indium: Indium 1.0.33+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		java: OpenJDK 64-Bit Server VM 21
		libipn: libIPN 6.0.2
		lighty: Lighty 3.0.0-beta.3
		litematica: Litematica 0.18.999-sakura.19
		lithium: Lithium 0.12.7
		malilib: MaLiLib 0.19.999-sakura.7
		minecraft: Minecraft 1.21
		mousetweaks: Mouse Tweaks 2.26
		no_despawn: NoDespawn 1.21
		no_fog: No Fog 1.3.6+1.16.5-1.21
		notebook: Notebook 4.0.5
		shulkerboxtooltip: Shulker Box Tooltip 5.0.4+1.21
		sodium: Sodium 0.5.9+mc1.21
		toggleableitemframes: Toggleable Item Frames 5.0.0-1.21
		visuality: Visuality 0.7.7+1.21
		wurst: Wurst Client v7.45-MC1.21
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 552.44, NVIDIA Corporation
	Window size: 1920x1057
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 8/8 chunks
	Resource Packs: vanilla, fabric, armourers_workshop, betterconfig, bridgingmod, cherishedworlds (incompatible), clientcommands (incompatible), cloth-config, colorfulhearts, continuity, enhancedblockentities, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, held-item-info, indium, inventoryprofilesnext, libipn, lighty, litematica, lithium, malilib, no_despawn, no_fog, notebook, shulkerboxtooltip, sodium, toggleableitemframes, visuality, wurst, file/Mace3D.zip, file/Simple Grass Flowers v1.8.1.zip, file/enchant icons 1.21 v1.3.zip, file/animated-items-1_21 - 1_3_1.zip, file/Watch of Undying.zip, file/coração roxo.zip, file/Scythe from RogueCraft.zip, file/Animated-Ore+0.5.2-1.16.5-1.21.zip, file/Glowing-OF_v0.4.1-mc1.21.zip
	Current Language: en_us
	Locale: pt_BR
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['KingForever_P4'/1, l='ServerLevel[Armourer's Workshop]', x=0.50, y=-60.00, z=-9.50]]
	Active Data Packs: vanilla, fabric, armourers_workshop, fabric-convention-tags-v2
	Available Data Packs: armourers_workshop, bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 7149047901705296930

**Additional context**
I'm using the 1.21 fabric version

**Comment by SAGESSE-CN** [comment]
pls use latest fabric api

**Comment by KingForeverP4** [comment]
i tried to use the latest fabric api but my Minecraft does not want to cooperate and crashes with the latest fabric api if i try to lauch
i dont really need the mannequin anyways

**Comment by SAGESSE-CN** [comment]
this is a bug of fabric. we can't fix it
