### ISSUE TITLE
[BUG] Vanilla skin overwriting

### ISSUE THREAD

**Issue by wyrda-001** [RiskyKen/Armourers-Workshop#477]
**Describe the bug**
AW skin overwrites the vanilla sword's skin (Not skinned, I tried using soap )
It doesn't overwrite sword's icon in inventory, Overwritten skin appears only when in hand, and in REI

**To Reproduce**
   When sword is in a hand or on REI tab,
   AW skin appears instead of vanilla one.

**Expected behavior**
Vanilla skin should be displayed if the sword is not skinned

**Screenshots**
![AW Bug Report (REI) 2](https://github.com/user-attachments/assets/dca9de36-f4ec-48fe-94c3-f4ebc46b8dca)
![AW Bug Report (REI)](https://github.com/user-attachments/assets/b034f7a6-1123-4bbc-98ac-ca248239395b)

**Additional context**
I'm not native English speaker, so please forgive me if the text is not accurate.

**Comment by SAGESSE-CN** [comment]
look like is a big issue, the mod version? and the wardrobe setting?

**Comment by wyrda-001** [comment]
Fabric ver.1.21
I'm a beginner so not sure what the wardrobe setting is, but all config is set default

**Comment by SAGESSE-CN** [comment]
I mean, do you have any skin equipped?

**Comment by wyrda-001** [comment]
Yes, a few tools and blocks are equipped.
Also, bugged skin has already been deleted from the download folder.

**Comment by SAGESSE-CN** [comment]
fixed in next release
