### ISSUE TITLE
[CRASH] Dawncraft crash

### ISSUE THREAD

**Issue by ewahn** [RiskyKen/Armourers-Workshop#479]
**To Reproduce**
Steps to reproduce the crash:
1. Go to '(https://www.curseforge.com/minecraft/modpacks/dawn-craft/files/5571738)' and download
2. add armourersworkshop-forge-1.18.2-3.0.0-beta.14
3. equip a outfit or piece of custom armour and a paraglider 
4. jump up atleast one block with paraglider in hand and jump off to use the paraglider
5. crash happens almost instantly after paraglider comes out

**Crash log**
https://pastebin.com/EAR7NXDU

**Additional context**
When using the armour hider your armour becomes visible when using paraglider but doesn't crash.

**Comment by SAGESSE-CN** [comment]
Can you reduce the number of mods to identify specific conflicting mods?

**Comment by SAGESSE-CN** [comment]
conflict comes from [DawnCraft-Tweaks](https://github.com/SmileycorpMC/DawnCraft-Tweaks).

fixed in next release.
