### ISSUE TITLE
I was making an armor to go with my skin but when i tried to put it on it didn't show up. I tried other armors but i had the same problem please help!

### ISSUE THREAD

**Issue by kozar23** [RiskyKen/Armourers-Workshop#48]

**Comment by kozar23** [comment]
I was making an armor to go with my skin but when i tried to put it on it didn't show up. I tried other armors but i had the same problem please help!

**Comment by RiskyKen** [comment]
How did you put it on? In the equipment wardrobe by pressing P or did you add the skin to a piece of armour in the skinning table?
What version of AW are you using?
What other mods do you have installed?

Have you tried restarting your game? There is a very rare bug that sometimes stop skins from showing on players, restarting normally fixes it.

**Comment by kozar23** [comment]
I used the equipment wardrobe and the version of the mod is the most recent version and the other mods didn't do anything

**Comment by RiskyKen** [comment]
I need a version number, most people that say they are using the latest are not.

"other mods didn't do anything" How do you know, did you try removing them?

Do skins render on mannequins?

If you are using the latest version you could try going into the config file and setting "Safe Model Render Override" to true, you will find it in the debug section.

Please let me know if that fixes it.

**Comment by RiskyKen** [comment]
No info
