### ISSUE TITLE
[CRASH] 1.20.1 Incompatablity with the recent version of Epic Fight.

### ISSUE THREAD

**Issue by alarmgoose** [RiskyKen/Armourers-Workshop#480]
Load the mods together and start the game. World will crash and crash utilities is mentions this mod, epic fight and maybe Embeddium. 

[crashlog.txt](https://github.com/user-attachments/files/16990448/crashlog.txt)

**Comment by SAGESSE-CN** [comment]
pls upgrade to 3.0.0-beta.14

**Comment by alarmgoose** [comment]
Okay and thanks!
