### ISSUE TITLE
[CRASH] Opening Skin Library crashes server.

### ISSUE THREAD

**Issue by ajitama9** [RiskyKen/Armourers-Workshop#481]
**To Reproduce**
Steps to reproduce the crash:
1. Open Skin Library in my server.

**Crash log**
https://pastebin.com/0qYF5WDW

**Screenshots**

**Additional context**
It works fine in singleplayer but it crashes the server when I try to interact with Skin Library in my dedicated server.

**Comment by SAGESSE-CN** [comment]
is not a crash log

**Comment by ajitama9** [comment]
Are crash logs not the same as crash reports? That's the only thing I could find in my server files.

**Comment by SAGESSE-CN** [comment]
try upgrade to beta.17

**Comment by ajitama9** [comment]
I found the lines in debug.log that shows the time of crash and the info.
https://pastebin.com/SpvMKC0r

**Comment by SAGESSE-CN** [comment]
> I found the lines in debug.log that shows the time of crash and the info.
> https://pastebin.com/SpvMKC0r

it fixed in the beta.17

**Comment by ajitama9** [comment]
Just tried it. It works fine now, Thank you.
