### ISSUE TITLE
Skin textures glitch when dyed

### ISSUE THREAD

**Issue by SomeCascadianGuy** [RiskyKen/Armourers-Workshop#483]
Whenever I apply a dye to a skin, the texture glitches out and doesn't fully render. If I have multiple copies of the same skin with a different dye for each one, only one of the dyes is applied to all the skins (see the third screenshot).

1. Load any world
2. Apply a dye to a dyeable skin.

**Expected behavior**
The dye isn't rendered in the skin texture properly. It usually doesn't apply the dye color to all dyeable pixels, but if there's more than one of the same skin in the inventory with a different color for each skin, a color for one skin is applied to the rest of them.

![2024-10-01_20 22 56](https://github.com/user-attachments/assets/56266aa0-a43f-43ac-a5de-dd1f4637c9b5)
![2024-10-01_20 23 16](https://github.com/user-attachments/assets/b586b99b-7e90-4be5-89e5-90aa2eeac2c6)
![2024-10-01_20 24 55](https://github.com/user-attachments/assets/97bf73c9-93ff-4317-aef6-5ee37915b133)

I am using the 3.0.0 beta-18 version of the mod on Minecraft 1.20.1, with Forge version 47.3.0.

**Comment by SomeCascadianGuy** [comment]
[list.txt](https://github.com/user-attachments/files/17219492/list.txt)
I also have a modlist here if that helps.

**Comment by SAGESSE-CN** [comment]
<img width="854" alt="image" src="https://github.com/user-attachments/assets/77c261ba-d5ed-4151-b81c-bc84a65a7c4b">

it works

**Comment by SomeCascadianGuy** [comment]
Noticing the screenshot was taken running NeoForge in MC 1.21. I'm using Forge for MC 1.20 (unless the modloader being used doesn't matter).

I'm finding the issue is continuing for me in beta 19.

**Comment by SAGESSE-CN** [comment]
pls test it only aw mod

**Comment by SomeCascadianGuy** [comment]
Did it with just aw running. The issue is still persisting.
![2024-10-10_11 50 04](https://github.com/user-attachments/assets/4899dba6-f525-4a9a-9503-d9343af3e351)
![2024-10-10_11 49 49](https://github.com/user-attachments/assets/3c9a7d76-0303-468b-9e86-78af611f582a)

**Comment by SAGESSE-CN** [comment]
sorry it dely so long. can you provide a video? maybe i not understand your question correctly.

**Comment by SAGESSE-CN** [comment]
try with latest version (3.1.0-beta)
