### ISSUE TITLE
[CRASH][Forge][1.18] Crash when hitting Alex's mobs Mimicube with a skinned weapon

### ISSUE THREAD

**Issue by V972** [RiskyKen/Armourers-Workshop#484]
**To Reproduce**
Steps to reproduce the crash:
1. Spawn/get Mimicube
2. Hit him with a weapon that has AW skin applied to it

**Crash log**
[https://pastebin.com/GP0AbTxu](https://pastebin.com/GP0AbTxu)

**Additional context**
If a sword skin is applied via a wardrobe, no crash happens, the skin is just not applied to the cube.
![image](https://github.com/user-attachments/assets/7fbfb237-2feb-4022-82ed-660bd1bb983b)

**Comment by SAGESSE-CN** [comment]
fixed by [3f29c26](https://github.com/Armourers-Workshop/Armourers-Workshop/commit/3f29c2695425d35549bd83ed4d542c40633e839c)
