### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ssAtlas** [RiskyKen/Armourers-Workshop#487]
hello!
so my brother just made his first server and he really wanted to try out this mod, only problem is when ever he starts up the server we get a new giant from the little bag every time; all players do. I was just wondering if there was a way I could help get that to stop  happening cause at this point we have a army of giants. I've looked through the mods configuration settings and I cant find any way to get this to stop if anyone has the time to help that would be great. thanks. :)

**Comment by SAGESSE-CN** [comment]
set disableAllHolidayEvents to true in the config
