### ISSUE TITLE
Every time I try to paint a single block with the paintbrush most blocks around get painted after I break or place a block

### ISSUE THREAD

**Issue by Ultramatteo22** [RiskyKen/Armourers-Workshop#488]
When I try to paint a block at first nothing happens, it doesn't paint or change. When I break any type of block the paint is applied to most blocks and I don't understand why. I tried with all the brushes but it's the same but with the effect that brush has. The blocks on the inventory also get painted. 

https://github.com/user-attachments/assets/51e48fb6-84fe-4c40-8417-ee8340299026

Minecraft Version: 1.20.1 (Forge 47.2.20)
Mod version: armourersworkshop-forge-1.20.1-3.0.0-beta.23

If you can give me a solution I would really appreciate it.

**Comment by calybee** [comment]
i'm having a similar issue. i don't need to break blocks for them to update but they display differently in the armorer in single player, in a server it doesn't even change at all.

**Comment by SAGESSE-CN** [comment]
fixed in next release
