### ISSUE TITLE
[BUG] Moving body parts cause both Y and Z to rotate together

### ISSUE THREAD

**Issue by Heropsyne2022** [RiskyKen/Armourers-Workshop#489]
**Describe the bug**
Whenever I Try to move the Y or Z on a Mannequin, the other moves with it

**To Reproduce**
1. Get a mannequin in 1.20.1
2. Open the wardrobe of the Mannequin
3. Move either the Y slider or Z slider in the Rotation tab

**Expected behavior**
One moves seprarate of the other

**Screenshots**
![Minecraft Forge_ 1 20 1 - Singleplayer 11_13_2024 3_38_32 PM](https://github.com/user-attachments/assets/d16e4df3-c653-45bb-bd19-1e27ba8af13c)

**Comment by SAGESSE-CN** [comment]
Fixed in beta.25
