### ISSUE TITLE
[BUG]why this animation dosen't play?

### ISSUE THREAD

**Issue by MechRW** [RiskyKen/Armourers-Workshop#490]
i learn form official teaching and making a wings with animation,named it like idle，run，fly，
but ingame i cant see any animation playing.
here is my BB modle ,just download it and use it in game.
[wings.zip](https://github.com/user-attachments/files/17784100/wings.zip)
![2024-11-16_17 13 14](https://github.com/user-attachments/assets/f29ebc41-2805-48f5-bf23-445812254bb4)
whatever you done like fly and run cant let the animation play.
![QQ20241116-171455](https://github.com/user-attachments/assets/be5bdb73-fde0-4259-9d3f-0e3f92007411)

**Comment by SAGESSE-CN** [comment]
it work normal.

<img width="854" alt="image" src="https://github.com/user-attachments/assets/ad6a9afa-32fe-4dcf-ad75-3d6c8dbc19f2">

**Comment by MechRW** [comment]
> it work normal.
> 
> <img alt="image" width="854" src="https://private-user-images.githubusercontent.com/6903353/386836355-ad6a9afa-32fe-4dcf-ad75-3d6c8dbc19f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTEyMTksIm5iZiI6MTczMTc1MDkxOSwicGF0aCI6Ii82OTAzMzUzLzM4NjgzNjM1NS1hZDZhOWFmYS0zMmZlLTRkY2YtYWQ3NS0zZDZjOGRiYzE5ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMDk1NTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRmM2IyM2I3YzI3YTI3ZjFhOGY2NGRiZGVmOWVjMTNmMWRiYTViMWRkZmE4ZTljOGNkOTZhZmQ0NTYxMzhkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q4hg4fu0KrlsoU-Jel-dXXy8nL6bfJYE3KeYNLt-a4g">

所以说是我的mod版本不对还是其他mod在导致的，是不是不兼容史诗战斗的动画渲染，
我用的是1.20.1的环境，时装工坊mod版本是forge-1.20.1-3.0.0-beta.7

**Comment by SAGESSE-CN** [comment]
update to beta.25

**Comment by MechRW** [comment]
> update to beta.25

所以说我需要再次手动加入这个mod对epicfight NPC的渲染支持，还是说官方已经加完了

**Comment by SAGESSE-CN** [comment]
`epicfight NPC ` 渲染支持是什么意思

PS:  你可以添加q群 819945681,  来找到我

**Comment by MechRW** [comment]
> `epicfight NPC ` 渲染支持是什么意思
这个mod提供的史诗战斗模型本身是不能被风格棒操作的，相关解决办法是别人甩我B站底下的，
就是改文件
我不知道官方有没有处理这个

![QQ20241116-180318](https://github.com/user-attachments/assets/ba5d588c-16b1-4219-9c48-57cd3a6fb6d0)

我看到qq群号了，谢谢

**Comment by SAGESSE-CN** [comment]
beta.25你仍然需要修改, 在后续版本会支持数据包修改

**Comment by MechRW** [comment]
> beta.25你仍然需要修改, 在后续版本会支持数据包修改

你有试过beta.25和史诗战斗20.7.4的兼容的吗，我这里莫名其妙的出现了这个报错：
我看了一眼全是mixin相关的，我也不知道为什么，目前因为epicfight NPC停止更新了，我没能找到解决办法（）
![QQ20241116-182100](https://github.com/user-attachments/assets/03fe347e-430c-4c8c-922f-3b4750d09a9a)
