### ISSUE TITLE
[BUG] Emmisive textures don't work properly with Complementary Shaders

### ISSUE THREAD

**Issue by calybee** [RiskyKen/Armourers-Workshop#492]
**Describe the bug**
When using Armourer's Workshop to apply emissive textures to custom weapons, the light emission only works at certain viewing angles when using Complementary Shaders. In contrast, BSL Shaders handles emissive lighting as expected, with the emission visible from all angles.

**To Reproduce**
1. Use Armourer's Workshop to create a custom weapon with emissive textures.
3. Load the custom weapon into the server.
4. Use Complementary Shaders to view the weapon in-game.
5. Observe that the emissive light from the weapon only activates at specific angles.
6. Switch to BSL Shaders and observe that the emissive light works correctly from all angles.

**Expected behavior**
The emissive textures should emit light from all viewing angles, similar to how they function with BSL Shaders, when using Complementary Shaders.

**Screenshots**
![2024-11-18_17 10 15](https://github.com/user-attachments/assets/71ea1d0d-5213-4268-a612-1be3cd8d71d7)
![2024-11-18_17 10 12](https://github.com/user-attachments/assets/96a66542-c972-4af9-ae1f-c7259aae3f40)
Just **slightly** switching angles turns off the glowing/emmisive effect.

![2024-11-18_17 14 33](https://github.com/user-attachments/assets/79382f7d-cf89-4bd6-b193-5d9d36a72471)
Emmision works just fine from every angle with BSL.

**Debug crash log**
No crash log.

**Additional context**

- Emissive textures work as expected with BSL Shaders but not with Complementary Shaders.
- The issue occurs consistently with different custom weapons using emissive textures.
- Complementary Shaders seem to have specific angle-dependent light emission behavior that differs from BSL's handling of emissive textures.

**Comment by calybee** [comment]
Just tested more with BSL, and turns out BSL has the same issue. The emmisive texture doesn't emit light from certain angles as well, but it's better than Complementary Shaders. Photon Shaders does the same thing. For context, I'm using the advanced skin builder.

**Comment by SAGESSE-CN** [comment]
sound like is Complementary Shaders issue, for shaders, we nothing can do.

**Comment by calybee** [comment]
It seems like it's the same with other shaders like BSL and Photon. I'll try more shaders later on to see if the issue still persists.
