### ISSUE TITLE
[Feature] Upgrade for AW Blocks And Linking Tool

### ISSUE THREAD

**Issue by Aoimina** [RiskyKen/Armourers-Workshop#496]
**Is your feature request related to a problem? Please describe.**
I would really appreciate the Linking Tool To be Not Just A right click redirection 
And AW blocks have more functional features that interact with other mods
don't get me wrong some of the stuff you can pull with it is utterly amazing while others not so much

**Describe the solution you'd like**
Make it When an AW block is linked to a storage block Via a Linking Tool be it a chest a barrel or a fancy storage controller block, allow AW block to inherit that block IE AW Block and that Block are one Best Example Would Be This Mod ( https://modrinth.com/mod/entangled ) , this would allow the ability for AW blocks to become that Block I am not asking to copy the block behavior as this would cause duping I'm asking for AW block to be that block and that block to be AW block Quantum entanglement to put it simply This Feature Would Add Endless possibilities And make AW a mainstream mod imo as this would allow the mod to be end all be all one stop shop for customizing any other block without requiring textures nor resource packs hell i would say it would be better then texture and resource packs,

**Describe alternatives you've considered**
An alternative that is simpler but not as much features as the first one would be to just allow AW blocks storage ones to import and export items using other methods then manually right clicking them (i know hopper exist but the biggest reason and the reason i fell in love with AW is its ability to customize features from other mods and hiding ugly factory stuff for more aesthetic pleasing without compromising functionality, so having weird hoppers on top of  beautiful AW blocks is something that would take away some of its beauty)

**Additional context**
If you ever consider adding this as a feature please do add it for 1.20.1 forge aswell as thats the version most players is at including me
Screenshot and more details of the first suggestion

![image](https://github.com/user-attachments/assets/6f8b5094-6345-4194-97d3-c2709c9ca3f0)

AWB = ArmourerWorkshop Block

Block 2 = Storage Controller Block

screenshots of the second alternative

![image](https://github.com/user-attachments/assets/c58e68d0-3915-46ed-b2e8-a2411e14c7d6)
here i am using 2 methods to import and export items both don't work

Lasty I am not asking for a change of how Linking Tool Work But a adding feature to it Much Love to everyone who worked at this amazing mod and Marry Christmas

**Comment by Aoimina** [comment]
If something doesn't make sense do please tell and il try to explain more as English is not my first language


Edit : i just learned AW have multiblock support thats insane in a good way

it mean if the first suggestion were to be added we would have the ability for custom fluid tanks as well

**Comment by SAGESSE-CN** [comment]
added in next version
