### ISSUE TITLE
Add options to show hidden armour when in combat.

### ISSUE THREAD

**Issue by RiskyKen** [RiskyKen/Armourers-Workshop#50]
PVP servers may want armour to be visible when a player enters combat. There should also be an option to stop players from turning off the armour render or only turn it off if there is a skin in that slot.

Planned Options
Show player armour in PVP combat.
Show player armour in PVE combat.
Time to hide armour after combat.
Allows players to hide armour.
Only hide armour if skin is in slot.
Hide skin if armour is in slot.

**Comment by LordPhrozen** [comment]
I dont think I've heard anyone actually request this, and wouldnt look great in any case. Closing for now, please re-open if you disagree Ken :)
