### ISSUE TITLE
Server Crash (NPE) when I open menu on server

### ISSUE THREAD

**Issue by Alaberti** [RiskyKen/Armourers-Workshop#55]
http://pastebin.com/474vXcfd

Version 0.34.1.87, Forge 1492, Fastcraft 1.22 [Edit: Fastcraft is only on the client]

I opened the AM menu and it took out the entire server (but did not crash the client). 

...Whoops?

**Comment by RiskyKen** [comment]
Do you have the normal server log file from just before the crash?

**Comment by Alaberti** [comment]
https://www.dropbox.com/s/wu68witypkyf1zr/fml-server-latest.log?dl=0

Here you go.

**Comment by RiskyKen** [comment]
Looks like it's related to https://github.com/RiskyKen/Armourers-Workshop/issues/53 should be fixed in the next update.
