### ISSUE TITLE
Prevent Loading from Client

### ISSUE THREAD

**Issue by Nentify** [RiskyKen/Armourers-Workshop#58]
Hey

I was wondering if it'd be possible to prevent users from loading models from client and have them created and stored using the armourer and equipment library on the server itself? This would be similar to `B:"Allow Clients To Save Skins"=false` I believe.

**Comment by RiskyKen** [comment]
Strange I thought I had a config for this. :S Guess I added support but forgot to add the option to the config file.

**Comment by Nentify** [comment]
```
    # Allow the mod to auto download new skins.
    B:"Allow Auto Skin Downloads"=true
```

Is this it? Maybe you already had. I wasn't quite sure if this meant something slightly different, such as downloading new official skins that come with the mod.

**Comment by RiskyKen** [comment]
Yeah that option is for download new skins when they come out. Will add the other option for the next update.
