### ISSUE TITLE
Crash with 35.0.90

### ISSUE THREAD

**Issue by BBoldt** [RiskyKen/Armourers-Workshop#61]
When starting up:
https://gist.github.com/c63148d12b6a3bcdd29e

**Comment by RiskyKen** [comment]
Can you try turning off the config option to unpack official skins to see if that fixes it?

**Comment by BBoldt** [comment]
That did fix it.

**Comment by RiskyKen** [comment]
k Will try and get a fix out tomorrow.

**Comment by RiskyKen** [comment]
FYI You will need to set extractOfficialSkins back to true so the mod can delete any corrupted skins, that got left from that crash.

Build will be on curse forge whenever they approve the file. http://jenkins.rx14.co.uk/job/RiskyKen/job/Armourers-Workshop/
