### ISSUE TITLE
[Feature request] Mannequins that can be skinned to look like blocks

### ISSUE THREAD

**Issue by BBoldt** [RiskyKen/Armourers-Workshop#64]
Basically, I would like to be able to do this:

![](http://imagizer.imageshack.us/a/img833/7291/m7oj.png)

Example is from the statues mod which is now depreciated.

**Comment by RiskyKen** [comment]
I don't normally like copying features exactly out of other mods but I think I remember @asiekierka saying statues was not getting updated anymore. I will check with @asiekierka first then think about adding this.

**Comment by asiekierka** [comment]
It's not my mod, for one; for two, it's terribly buggy; for three, I won't
update it anymore and haven't for over a year.

2015-08-23 20:36 GMT+02:00 RiskyKen <notifications@github.com>:

**Comment by LordPhrozen** [comment]
IMO this can easily be acomplished with AW and CNPCs. Closing this, if you feel this doesnt address this ancient ticket, please open a new one, with screenshots.
