### ISSUE TITLE
Some skins occasionally do not load at random

### ISSUE THREAD

**Issue by Febilian** [RiskyKen/Armourers-Workshop#65]
I don't really know how to sum it up other than the title.

When I launch Minecraft and join one of my worlds where skins previously worked fine(some of the worlds are ones where they were initially created), sometimes skins won't load their data from the Library, while others work just fine. The skins that load or don't load does not seem to be consistent in any way, and while the skin item itself(or the item with the skin applied, like armor or swords) is *there*, it is perpetually stuck as the loading/generic icon for its item type. It's hard to consistently recreate the issue, because sometimes it works just fine after a restart of Minecraft.

I was going to grab a screenshot of the loading text that states it is "downloading" the skin, for example, but when I re-launched Minecraft just now, it wasn't having any issues loading skins whatsoever.

Seems odd that it says "Downloading skin ID" or something similar when the files are right there in the folder on my computer...

Using version 1.7.10-0.36.0.92 of Armourer's Workshop.

Other mods installed(I am working on a private modpack, and sometimes while fixing things up between restarts of MC I've noticed the issue at hand):

Antique Atlas - 4.2.2
Baby Animals - 1.7.10-2
Baubles - 1.7.10-1.0.1.10
Bibliocraft - 1.10.6
Biomes O Plenty - 1.7.10-2.1.0.1387
Botania - r1.7-212
Carpenter's Blocks - v3.3.6
Chisel2 - 2.4.1
CodeChickenCore - 1.7.10-1.0.6.43
Dense Ores - 1.5
Extra Utilities - 1.2.10
Fastcraft - 1.21
Fast Leaf Decay - 1.7.10-1.0
Fluxed Crystals 2 - 1.0.6
Grimoire of Gaia 3 - 1.7.10-1.1.2
Hardcore Questing Mode - 4.2.4
InfiniBows - 1.3.0.20
Iron Chests - 1.7.10-6.0.62.742
IvToolkit - 1.2
JABBA - 1.2.1a_1.7.10
JustAnotherSpawner - 0.17.2
Kawaii Crops - 0.5.10b
LibSandstone-1.0.0
Lore Expansion - 1.7.10-1.0.5.B29
MineTweaker 3 - 1.7.10-3.0.9C
MobProperties - 1.7.10-0.4.0
ModTweaker - 2-0.9.2
Not Enough Items - 1.7.10-1.0.4.107
Optifine - 1.7.10 HD B7
Progression - 1.7.10-0.4.1
Quadrum - 1.7.10-1.2.0B13
Recurrent Complex - 0.9.6.3
Reliquary - 1.2.257
Thaumcraft 4 - 1.7.10-4.2.3.5
Thaumcraft NEI Plugin - 1.7.10-1.7a
WAILA - 1.5.10_1.7.10
Witchery - 1.7.10-0.24.1
WorldEdit - mc1.7.10-6.0-beta-01
Ztones - 1.7.10-2.2.1

**Comment by RiskyKen** [comment]
Have your worlds been updated from older versions of Armourer's Workshop?

**Comment by Febilian** [comment]
It's possible, but I don't think so. I will make new worlds to test in and see if the problem persists.

**Comment by Febilian** [comment]
I have not had any further issues thus far since spending most of my time in the new world. I'll leave a comment if something does show up, but it seems that it's quite possible upgrading was the issue.

**Comment by Febilian** [comment]
Okay, it's happening again. It gets stuck and says "Downloading Skin ID" when I mouse over any item affected with the default icon/loading circle thing. This was in a brand new world I created around maybe... ten minutes ago? So it isn't because of an upgrade from a previous version.

**Comment by RiskyKen** [comment]
Next time this happens can you note down the ID then check in <mc instance>\saves\<world name>\skin-database and see if there is a file with a matching name.

Can you also send me your logs from one of the days that it happened, they are in <mc instance>\logs. If you play with the launcher open there may also be something output to the console when the skins fail to load, please copy me any lines you see that looks suspicious.

One last thing, next time this happens can you press F3 to open the debug screen and note down the number at rq=. Normal this should be zero if it's not it should drop to zero after a minute, if it's above zero for more than a minute please let me know.

**Comment by Febilian** [comment]
I will definitely keep those things in mind, I will attempt to provide relevant information if/when it happens again.

**Comment by Febilian** [comment]
Okay. Since it's happening right now with at least one skin I'll find the info for it:

The ID of the item(the "Skin ID", right?) is indeed in the skin-database folder, but it isn't loading into the game.

How would I go about giving you the fml-client-latest log file(assuming that's the one you want), should I try to upload the text somewhere, or do you want the file itself on a file sharing website? Kinda new to this, sorry.

The only strange-looking line regarding this mod I can find by searching "armour" in the text of my console output(I use MultiMC) is the following:

[14:22:33] [Armourer's Workshop Server Skin Thread/ERROR] [Armourer's Workshop]: Equipment id:1151834663 was requested by <PROFILE NAME> but was not found.

The debug screen number after rq= is 3.

Does any of this help?

**Comment by RiskyKen** [comment]
Just copy paste it into pastebin or something like that then post the link. http://pastebin.com/

Have you tried it without other mods btw? I think am going to try the same mod setup you have tomorrow and see I can can reproduce the issue.

**Comment by Febilian** [comment]
Pastebin won't let me copy all the text, its file size is too big it seems. Alternative sites appear to have a similar limitation. I uploaded the file itself to Google Drive, hopefully you can get it from there for now(please tell me if that doesn't work): 
https://drive.google.com/file/d/0ByRDHOxs0DRHSGV2TGxKeDBsNTg/view?usp=sharing

I have not admittedly tried it without other mods(as it is not a consistent issue and I haven't had the time to spare to try it on its own thus far), but using a previous version of the mod in a pre-packaged modpack(with a different selection of mods) that hasn't been updated for a while appears to have the same issue occasionally. I will see if it occurs with no other mods installed and several Minecraft restarts in a little bit.

It's also worth mentioning that I had searched for the issue beforehand and tried changing some config options that change rendering, which seems to *help* with the frequency at which skins properly load, but it has not completely solved the issue(as I am still here).

Also, I was having the issue *before* I tried this particular subject, but would putting any skin or specific skinned item into HQM quests/icons/rewards cause issues? Or would that cause more problems? It appears to sometimes work, but sometimes it doesn't load - so I'm assuming for now that it's not related to that. Thought it was worth bringing up just in case, though.

Going out on a limb here, do you think it's possible the issue has anything to do with me running the mod on OS X? I don't know which OS environment you use for development, so perhaps there are some compatibility issues.

**Comment by Febilian** [comment]
Okay, um. This is unrelated to this particular issue, but I am getting some REALLY bizarre graphical occurrences with nothing but Forge 10.13.4.1448-1.7.10 and Armourer's Workshop installed. If I remove AW, nothing's wrong, and everything looks normal.

When I load up nothing but AW with it, THIS kind of thing happens, where text becomes weird boxes and blocks/items get really odd combinations of textures:

http://i.imgur.com/ZaIpUWa.png?1

Oddly enough, upon installing Optifine(as I have in my modpack and I usually have it anyways) seems to eliminate the issue.

Back to business….

I haven’t had any issues with just AW and Optifine installed after restarting three times and loading into different worlds, using the same .armour files I have in my modpack’s instance folder.

Might be a mod conflict of some kind after all. I will try to add in mods one at a time to see if anything changes, but it will take some time to effectively test… I suppose I should count myself lucky that I don’t have as big a modpack as many other people play with.

**Comment by RiskyKen** [comment]
If you go into the config and change clientModelCacheTime and serverModelCacheTime to something like 200 it should accelerate the issue if it's going to happen, should allow you to find out if removing the other mods has fixed it.

It will hurt performance thought!

**Comment by Febilian** [comment]
I have currently tried using the following mods without issue, using the config options you suggested:

Optifine
Fastcraft
Antique Atlas
Baby Animals
Bibliocraft
Biomes O Plenty
Botania
Baubles
Carpenter's Blocks
Chisel 2
CodeChickenCore
Not Enough Items
Dense Ores
Extra Utilities
Fast Leaf Decay
Fluxed Crystals 2

I need a break from adding mods one at a time and restarting Minecraft, that's about just less than half of them that I checked one at a time. I'll work on the others later; so far, those ones do not appear to cause issues while installed with AW.

**Comment by RiskyKen** [comment]
Well I have tried setting up a instance with all the mods you have listed and am not able to reproduce the issue. If you have custom configs/scripts can you send them to me.

About the HQM question, am guessing you are setting up a modpack that will give AW items as rewards? It should work fine as long as the skin-database inside the world folder is shipped with the pack. If the players are loading a pre-made world then it's not really an issue, if not you will have to find a way to copy the skin-database folder into the world folder when they make a new world.

**Comment by Febilian** [comment]
I do have a variety of customized configs and some minetweaker scripts, I'm not sure which ones would be relevant, are there any mods in particular that are more suspicious than others or do you want ALL of them?

That's exactly what I was doing with the rewards - however I was under the impression that if the ArmourersWorkshop folder in the minecraft directory where the skins are saved to disk was supplied, then any subsequent worlds would be able to have them added dynamically. Could this misunderstanding possibly be the issue?

**Comment by RiskyKen** [comment]
Yes that could be the issue. The armourersWorkshop folder is only used by the library block, most of the mods workings use the skin-database folder.

I will try and give a short explanation of how it works.

When a skin is loaded from the library or created with the armourer, the mod will give it a unique ID then save it into the skin-database folder with the ID as the file name. The mod will then create a new equipment skin item in the library or armourer and add the skin ID onto the items NBT data. When a client tries to render the skin it gets the ID from the items NBT and checks if it has the model, if not it will request the model for that skin ID from the server. When the server get a request for a model it will check for a matching file name in the skin-database folder and send it back to the client. The same process is used for skinning weapons and armour an ID number is added to the items NBT so the mod knows what model to render.

I hope that explanation was not too technical. :confused:
So in short if you create an skin in one world then somehow copy that item into another world without using the library, it will not work unless the skin-database folder is also copied to that world.

If you have a pre-made world for players to play on then this is not really an issue as the skin-database folder will already be in the world folder.

If you are allowing players to make their own world but want to give skinned items with something like HQM, the skin-database folder from the world that you setup the HQM quest rewards will need to be copied into the players new world. AW can actually do this, you just need to make a folder inside your instance folder called "equipment-database" and copy the contents of the skin-database folder into it. When the player creates a new world all the files in equipment-database folder will be copied into the worlds skin-database folder, This only happens when the world is first created.

Let me know if my explanation if awful!

**Comment by Febilian** [comment]
Creating the 'equipment-database' folder seems to be exactly what I needed to do, and works just great. Thanks so much for being patient with me throughout all of this!

Perhaps it would be beneficial to mention this somewhere for people who have similar intentions? I don't know if there's any place with up-to-date documentation on the mod or not.

**Comment by RiskyKen** [comment]
I will add some info to the forum post next time I update it. Remember if you add new skins you will need to copy the files over again.
