### ISSUE TITLE
Making Statues able to be interfaced by Computer-based Mods

### ISSUE THREAD

**Issue by edenprojectde** [RiskyKen/Armourers-Workshop#66]
It would be really cool to control Statues like this, it would give Computer Mods the ability to create Moving NPC's.

The implementation should not be really complicated on AW's side but would really be handy for those who like to play around with Lua. Also in the future when there could programs helpful to make Videos, and automated Scenes like in other animation Programs. One thing that would be additionally needed is an absolute offset(in a range of 1-2 blocks) so you can make the Statues lie on the ground or fly upwards slightly.

When mentioned on Videos where this mod would then be used, it would definitive help getting this mod more Users than it already has. I love this more and i love the possibilities it gives the User, and i also love the Idea of Ingame NPC manipulation. This would be a really really great addition to be endless possibilities of our well beloved Minecraft game.

**Comment by RiskyKen** [comment]
Rotating the mannequin body is definitely a feature that will be getting added, along with the mannequin changing it height based in the lowest limb and a height offset option for jumping/sitting poses.

I will look into adding support for computer mods.

Mannequin's will be getting a big rewrite soon so I will look into it then.

**Comment by RiskyKen** [comment]
Seems Computronics already adds this http://wiki.vex.tty.sh/wiki:computronics
