### ISSUE TITLE
Render Size of Skins & Item Icon

### ISSUE THREAD

**Issue by Zendrex** [RiskyKen/Armourers-Workshop#78]
Would be really nice if we could downscale the size of blocks/skins that we make. For example, I have a sword that is the right dimension sword wise however its giant on the player and doesn't fit in the screen.

Example
http://i.imgur.com/MjmKg6W.png

In turn with that, would be nice if we could manually change the bounding box size of the build zone as well for those larger weapons.

Also, would be nice if the skin shown in the hotbar (before applied to weapon), would show up on the weapon/item icon in the inventory but at a angle so it fits properly.

**Comment by LordPhrozen** [comment]
If you're changing the scale of things, you're really breaking art style consistency. The voxel size we have wasn't chosen at random, its the same size of the pixel on the player skin. Working within these limitations is what art consistency and and art direction is.

Seeing is this is very close to asking for half blocks, etc, im going to close this, as that feature was denied.

**Comment by Zendrex** [comment]
Old post, some comments regarding it still since it was brought up. (dont really care at this point as im far beyond it but good to discuss anyways);

At the time, I was looking to get something like this added mostly to do with making an RPG like server. Some "weapons" for example could really have benefited from being able to have more detail. I feel that you saying "its an artistic style choice" is somewhat of a turn of the nose because minecraft has always been more then just a 16 bit game. Its about creativity, breaking the boundaries and going outside the lines. Not staying in them.

I really liked the concept of this mod and its what pushed me to eventually make custom texturepacks and assets that took advantage of voxels. Seeing however that you are hardstuck on not wanting to allow people to expand beyond what you believe should be the art limitations of minecraft really make me feel sorry for those who dont have the capabilities of making custom textures/assets outside the game.

Again, I'm well past this, however you kinda pulled a string when you stated that there should be limitations for minecraft. Thats the complete opposite of what the game is about.

I'm not here to start a fight, just posting my opinion since you brought it up nearly 3 years later. I'm no mod dev though and even though I don't consistently play the game anymore, I speak for those who do and have been wanting something like this. I eagerly waited for a response for several months then gave up to be honest. Seems like a lazy excuse to me, but that's just my opinion.

-Zendrex
