### ISSUE TITLE
Server crash when someone with a armour equiped disconect

### ISSUE THREAD

**Issue by firex20** [RiskyKen/Armourers-Workshop#80]
Here is the crash log of the server: http://pastebin.com/ywzFwvPc

Its a modpack, someboyd can help me :(?

Edit: it only crash with default and pre-loaded skins, with the in-game create skins its all okay.

**Comment by RiskyKen** [comment]
Fix will be in the next build.

Related to https://github.com/RiskyKen/Armourers-Workshop/issues/72 fixed in https://github.com/RiskyKen/Armourers-Workshop/commit/44cd86341c03d9ba8eb457dfd31e16f7f6746271

**Comment by firex20** [comment]
Okay thanks ^^!
