### ISSUE TITLE
[Suggestion]Add a custom image URL for Mannequins

### ISSUE THREAD

**Issue by ProgrammedSoul** [RiskyKen/Armourers-Workshop#83]
I'm hosting a small server and as player suggested I added Armourers Workshop mod recently. It gave me a good idea that I can use this mod alone with other decorative mods to set up a series very neat looking static movie senses and make the buildings looks much more alive. The problem is, I(and all my builders) do not want to buy a Minecraft account for each of characters just to use their skins on mannequins.
I'm not sure what did the FAQ means in MCF about Custom NPC mod. If Armourers Workshop do work with Custom NPC mod, it brings a number of problems. As I remember add skin to custom NPC mod requires update all the client. Also you cannot setup a NPC to stay their and not move at all, you cannot setup a NPC's position in much detail, custom NPC's mod has a very complex UI that requires a long while to get used to, and custom NPC mod added too much unnecessary features. So if it is possible, being able to add a image URL for mannequins' skin would be a absolutely awesome idea, and not only the people in my server, but all the people interested in making good looking builds will love it.
I'm not sure if it is possible to do this on your side through...I tried modify mannequins NBT data, modify the base64 skin uri into my own url, it does not seems to work,
Thanks!

**Comment by RiskyKen** [comment]
A big rewrite for mannequins will be coming in the future and most of this is already planned.Only thing that is not is the custom URLs, will see about adding it closer to the time.

**Comment by ProgrammedSoul** [comment]
Thanks : D. Sorry for the late response(final exam strike). It is fine as long as there is a way to use custom skin, and it will be even better if the skin can be shared server-wide.
