### ISSUE TITLE
Server Crash When Attempting to rename equiptment skin

### ISSUE THREAD

**Issue by Badcholo** [RiskyKen/Armourers-Workshop#84]
so i create a any item with your mod and don't name it in the machine. I then place the equptment skin item into an anvil and attempt to rename it. Crash.
http://pastebin.com/Y1184BX1

**Comment by RiskyKen** [comment]
Related to https://github.com/RiskyKen/Armourers-Workshop/issues/72 will be fixed in the next update.

**Comment by Badcholo** [comment]
Thank You.

**Comment by Badcholo** [comment]
Can we add a curse link to the main github page please.
