### ISSUE TITLE
Smart moving not respecting limit limb movement option

### ISSUE THREAD

**Issue by MinecraftGirl123** [RiskyKen/Armourers-Workshop#85]
Well, i made a really cute prom dress and its frilly. But every time i walk my feet go through it! I want my feet to be still while i walk in my dress so it wont look weird. What do i do?

**Comment by RiskyKen** [comment]
Check the limit limb movement option in the equipment wardrobe screen. If you have a skirt equipped it should limit how far your legs can swing.

**Comment by MinecraftGirl123** [comment]
Okay Thx

**Comment by MinecraftGirl123** [comment]
It didnt work. What else can i do?

**Comment by RiskyKen** [comment]
Do you have smart moving installed? It's currently broken with it.

**Comment by MinecraftGirl123** [comment]
I do but even when i disabled Smart Moving the legs went through it.

**Comment by RiskyKen** [comment]
You need to completely remove smart moving for it to work.

**Comment by MinecraftGirl123** [comment]
remove it? But Little Kelly still had Smart Moving when she did it

**Comment by MinecraftGirl123** [comment]
Hold on let me see...

**Comment by MinecraftGirl123** [comment]
Okay i removed Smart Moving form the mods folder now im going to see if it works

**Comment by MinecraftGirl123** [comment]
OMG! It worked! Thx Soooo much for helping me! :D

**Comment by RiskyKen** [comment]
I will see if I can fix the smart moving support.

btw do you have a link to the video?

also remember you can share your creations on the forum if you want :)

**Comment by MinecraftGirl123** [comment]
Let me give you the link to the video, and that is a good idea i will definitely share my dresses!

Link: https://www.youtube.com/watch?v=uv5t59zEc8A

**Comment by MinecraftGirl123** [comment]
If you skip to 906 you can see the dresses :D

**Comment by MinecraftGirl123** [comment]
Have you fixed it? And i have another problem. When i put on the dresses and stuff, it doesnt show it on me. ? What happened?

**Comment by RiskyKen** [comment]
No it's not fixed yet, fixing other stuff just now.

Are you using the latest version? 1.7.10-0.38.0.97 http://minecraft.curseforge.com/projects/armourers-workshop/files
Skins not showing on the player was an old bug it should be fixed now.

**Comment by MinecraftGirl123** [comment]
For some reason it only happened on one world im on my other world now and its working. I must have hit a button or something.
