### ISSUE TITLE
Skin Preview in Equipment Library

### ISSUE THREAD

**Issue by Alaberti** [RiskyKen/Armourers-Workshop#86]
I didn't see this mentioned anywhere else on here. Is there a way we could have a preview of the skin in the library? I assume it's already something on your radar though. Thanks!

**Comment by RiskyKen** [comment]
Yip it's planned just not got around to adding it.

I should upload my todo notes somewhere but cba converting them from notes. http://pastebin.com/u4NiRUXd

**Comment by RiskyKen** [comment]
Added in https://github.com/RiskyKen/Armourers-Workshop/commit/7324dfa86b24c6a889fd0d440fb5354ad6c0a2c9
