### ISSUE TITLE
problem with the equipment cubes

### ISSUE THREAD

**Issue by Wolfangel3** [RiskyKen/Armourers-Workshop#87]
Hello I have a problem is that when I play and try to build a weapon or suit the skin of equipment cubes become transparent. I also appears transparent color mixer and do not know how to fix it. Can you help me.
![2015-12-25_12 47 39](https://cloud.githubusercontent.com/assets/16438787/12004145/3afe8d42-ab14-11e5-80a8-748d9de94a3c.png)
![2015-12-25_12 48 30](https://cloud.githubusercontent.com/assets/16438787/12004147/3f21d9d8-ab14-11e5-92c1-a89891dfc8bf.png)

**Comment by MrPotatoGaming** [comment]
Does this modpack have FastCraft or Opitfine?

**Comment by Wolfangel3** [comment]
yes optifine

**Comment by MrPotatoGaming** [comment]
Try removing Opitfine and see if the issue still happens

**Comment by RiskyKen** [comment]
Mod list/mod pack please.

**Comment by Wolfangel3** [comment]
Thank a remove optifine and the problem solved
