### ISSUE TITLE
Skins for tools?

### ISSUE THREAD

**Issue by SHIuSH** [RiskyKen/Armourers-Workshop#91]
Is there gonna be skins for tools like pickaxe, axe, shovel, hoe etc.?

**Comment by RiskyKen** [comment]
Yes the sword skin will become generic and should be usable on any time. Just not got around to it yet.

**Comment by RiskyKen** [comment]
Added in 0.48.0 https://github.com/RiskyKen/Armourers-Workshop/commit/241ea1c28ff80a8cf77c83a09f9e9e6827ff39d0
