### ISSUE TITLE
Mine Little Pony support

### ISSUE THREAD

**Issue by CaptainKyros** [RiskyKen/Armourers-Workshop#92]
what im suggesting is support for the Mine Little Pony player model so bronies (and pegasisters) can create pony armor for their pony characters and npcs

**Comment by TheChronomancer** [comment]
anyone here?

**Comment by RiskyKen** [comment]
I am here just been busy. Will look into it.

**Comment by TheChronomancer** [comment]
ok

**Comment by IrritatedVillager** [comment]
anyone else imagining how funny it would be to see applejack in dark souls armour

**Comment by TheChronomancer** [comment]
any progress?

**Comment by RiskyKen** [comment]
Not yet, first I need to answer this important question! https://i.imgur.com/JFhw6qzl.jpg

**Comment by EthanJJC** [comment]
LOL

**Comment by TheChronomancer** [comment]
2nd option

**Comment by LordPhrozen** [comment]
This is consolidated into issue #249
