### ISSUE TITLE
What version?

### ISSUE THREAD

**Issue by Daeleus** [RiskyKen/Armourers-Workshop#93]
Hi there! I need a little help, is there any way of seeing which version of Forge I should use for which Mod update? If so, can someone please tell me! Thanks you!

**Comment by RiskyKen** [comment]
I build the mod on 10.13.4.1448 but any newer version should work fine.

**Comment by Daeleus** [comment]
Thanks man! Love the mod BTW <3

**Comment by Badcholo** [comment]
I use it on 1614 and it works fine. i would just update to the latest version

**Comment by RiskyKen** [comment]
Am guessing it works then? Closing this issue.
