### ISSUE TITLE
[Suggestion] Skinable Blocks

### ISSUE THREAD

**Issue by IrritatedVillager** [RiskyKen/Armourers-Workshop#94]
Sorry to bother you again but here's another suggestion.
Is it possible to make the skining table work for blocks blocks like Crafting tables,Enchanting tables,Chests ect

**Comment by Badcholo** [comment]
It would be cool to design your own custom blocks for building. i wonder if that is even possible

**Comment by RiskyKen** [comment]
It's planned.

**Comment by RiskyKen** [comment]
Added block inventory skin option in https://github.com/RiskyKen/Armourers-Workshop/commit/c86a778d951b84776d381db38e90ca36626060e0

Other options will be added in time
