### ISSUE TITLE
Bow skins aren't working. (At least for me.)

### ISSUE THREAD

**Issue by TsunamiCoRyan** [RiskyKen/Armourers-Workshop#95]
![2016-02-11_20 14 19](https://cloud.githubusercontent.com/assets/11284644/12998728/17955256-d0fc-11e5-85f4-54d72823da6b.png)

The bow option is completely blanked out, as you can see in the picture provided. Not sure if it's a bug or if I might have disabled it somehow. What do you think?

**Comment by RiskyKen** [comment]
You are using an older version get the new one here http://minecraft.curseforge.com/projects/armourers-workshop/files

**Comment by TsunamiCoRyan** [comment]
Ah, okay. Thanks!
