### ISSUE TITLE
AW affecting resource pack's clouds 

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#96]
I don't know how or why, but as long as I have AW running, the vanilla clouds (they look like ones) overrides the clouds from resource pack that I use, which are a very subtle transparent, almost invisible.

What I did to reproduce the bug:
* To guarantee that nothing affected the test, I removed all content from minecraft directory and reinstalled MC from scratch.
* Installed MC 1.7.10.
* Installed the resource pack (if you want to try it yourself, just [Aeon Main Pack](http://ezerarch.blogspot.com/p/resource-pack.html) is enough).
* Installed forge-1.7.10-10.13.4.1614.
* Installed OptiFine 1.7.10 HD U D1.
* Run the game. Result without AW:
![2016-02-14_02 35 57](https://cloud.githubusercontent.com/assets/6743303/13031903/cfa0b578-d2c5-11e5-96cb-33b541ce111e.png)
* Installed Armourers Workshop 1.7.10 0.38.1.98
* Run the game. Result with AW:
![2016-02-14_02 37 46](https://cloud.githubusercontent.com/assets/6743303/13031906/cfa4f44e-d2c5-11e5-94f8-dafa16f2e131.png)
![2016-02-14_02 38 14](https://cloud.githubusercontent.com/assets/6743303/13031908/cfa75270-d2c5-11e5-8569-18441ce0c4c7.png)
* I have no other mod installed:
![2016-02-14_02 38 34](https://cloud.githubusercontent.com/assets/6743303/13031907/cfa58c9c-d2c5-11e5-8e8e-2da40368ab12.png)

Now without OptiFine (that means, no Better Sky feature):
* With Forge only, no mods. Result: 
![2016-02-14_02 48 13](https://cloud.githubusercontent.com/assets/6743303/13031904/cfa2d7b8-d2c5-11e5-92fa-999e0124fefc.png)
* With Forge and AW, no other mods. Result:
![2016-02-14_02 50 14](https://cloud.githubusercontent.com/assets/6743303/13031905/cfa45098-d2c5-11e5-91bd-c857ceb55e2b.png)
* I have no other mod installed:
![2016-02-14_02 59 16](https://cloud.githubusercontent.com/assets/6743303/13031937/f57744aa-d2c6-11e5-8fd5-e42f2eef49c3.png)

And as final test, I recovered my backup with forge, all mods, optifine, worlds etc, tested with and without AW: the same happens.

Tested with Clouds ON, Fancy.

**Comment by EthanJJC** [comment]
it looks Harmless :)

**Comment by EzerArch** [comment]
> it looks Harmless :)

Except for resource pack maintainers. ;)

**Comment by RiskyKen** [comment]
This was intentional, it only happens on valentines day and you can turn the holiday events off in the config file if you really don't want it.
