### ISSUE TITLE
Command for summoning in items saved on a server?

### ISSUE THREAD

**Issue by BigRedScarf** [RiskyKen/Armourers-Workshop#99]
I don't know if this is the correct place to post this, but I was wondering if there was a way to summon in a skin you have made previously using a custom /summon command.

**Comment by RiskyKen** [comment]
You can use
"/armourers giveSkin <Player Name> <Skin Name>"
to give a skin item to a player or
"/armourers setSkin <Player Name> <Skin Name>"
to equip a skin onto a player.

Note it's currently bugged with command blocks.
